### ISSUE TITLE
请问可以增加搜索文件夹名的功能吗

### ISSUE THREAD

**Issue by yilksd** [danny0838/firefox-scrapbook#10]
如果一件事建一个文件夹，将收集到的网页内容放入其中，这样很容易产生很多文件夹，因此需要搜索，请问可以在标题搜索和全文搜索加上搜索文件夹名的功能吗？

**Comment by danny0838** [comment]
自 1.13.0b5 開始支援將一般項目轉為資料夾。如需要可搜索的資料夾，可建立筆記頁面並轉為資料夾。
