### ISSUE TITLE
cache.rdf doesn't update

### ISSUE THREAD

**Issue by i-macdonald** [danny0838/firefox-scrapbook#103]
Just installed Scrapbook-x 1.12.31 and added about three pages to the store, everything was working fine. I closed FF, restarted and added another 6 pages. A Search wouldn't find any of the 6 recently added pages. Looking at my data store I could see that cache.rdf hadn't been updated.

I deleted cache.rdf, did another search which forced a re-index and cache.rdf was re-created. Search would then find one of the 6 newly added pages. I then added another 3 pages and again cache.rdf wasn't updated.

Using:
Scrapbook-x 1.12.31
FF ESR 45.2.0
NoScript 2.9.0.11 (but also tried with NS disabled)
Debian Jessie x64

**Comment by danny0838** [comment]
ScrapBook does not update the cache just after items are added (or deleted), but only a periodic update if there's no update in 5 days. You have to manually update the cache after adding items if you want the fulltext search to include them.

**Comment by i-macdonald** [comment]
Many thanks for the super fast reply and for creating Scrapbook-X.

It looks like my enthusiasm for testing SX caught me out ;-)

Is there a menu item to update the cache file, I haven't found one?

**Comment by danny0838** [comment]
Yes, here it is.
![screenclip](https://cloud.githubusercontent.com/assets/531417/16557438/5ea442d8-4212-11e6-8c3f-579f2e79c256.png)

**Comment by i-macdonald** [comment]
Ach, I hadn't noticed that was a drop-down menu, cool.

Now I see there is also: search by field, match case and regex - brilliant.
