### ISSUE TITLE
No Release Notes information in Add-ons Manager

### ISSUE THREAD

**Issue by Przbl** [danny0838/firefox-scrapbook#104]
The Firefox Add-ons Manager provides a prominent spot to see the changelog of Add-ons.
See Add-ons Manager > Available updates. When an Add-on update is available in the center of each row theres a column "Release Notes" that can be toggled shown or hidden.

Scrapbook X does not provide information for this area so it's a pain to find this piece of information but it should.

**Comment by danny0838** [comment]
It seems to be related with the release notes written on the Firefox Addon site, and I have been too lazy to fill in it :'(

I added them just now, which should have solved this issue.

**Comment by Przbl** [comment]
Great, thanks!
