### ISSUE TITLE
Scrapbook X for Vivaldi (Chromium)

### ISSUE THREAD

**Issue by bytos** [danny0838/firefox-scrapbook#105]
Chromium browsers badly need this extension.

You almost always need to edit before saving as MHT (to clean up the extra garbage).

PDF is not an option.

And Scrapbook X allows text editing, which the original doesn't.

**Comment by danny0838** [comment]
I have been trying to port ScrapBook X to Chromium, but it's extension system does not seem to offer some essential features for ScrapBook X to work. This is a request I cannot help until Chromium did some change.

**Comment by bytos** [comment]
Thanks for trying, I only have FF because of this extension. With webpages getting bigger and full of crap, a nice tool like this one becomes necessary.

I can't understand why isn't there a simple application to edit MHT files to remove text & elements (with highlighter).

Same thing for cleaning unused CSS elements to reduce file size, with visual feedback in case a necessary CSS element is removed by mistake (easier than using Stylizer).

**Comment by danny0838** [comment]
We have a "port" as [Web ScrapBook](https://github.com/danny0838/webscrapbook).
