### ISSUE TITLE
Close sidebar issue with Pale Moon

### ISSUE THREAD

**Issue by githmw** [danny0838/firefox-scrapbook#106]
Danny: 
My problem exists in the 'Close Sidebar' feature of the Sidebarheader Toolbar. I think that Scrapbook X controls the features in that Toolbar. If that is correct, please read on. If not, can you tell me what program does control the Sidebarheader Toolbar?

I have Scrapbook X 1.12.32, which I updated today from 1.12.17. The problem I describe occurs on both versions.  Attached is an image of the problem. I recently updated my Pale Moon browser from 26.2.2 to 26.3.3. In version 26.2.2, there is only one 'x' indicated on the toolbar, whereas in 26.3.3 there are 4 'x', as shown in the attached image. So Pale Moon must have made some change which created this problem. Any idea what might be causing this problem?

I also have Firefox 42.0 with Scrapbook X.1.12.17. The problem does NOT occur there. 

Thanks,

Harry
![scrapbookcloseproblem](https://cloud.githubusercontent.com/assets/17102180/16626786/731066e0-4378-11e6-99f7-7e38863740bc.png)

**Comment by danny0838** [comment]
I guess it's due to a change of the xul relating with the sidebar and ScrapBook X might have to add some ad hoc codes for Pale Moon. But unfortunately I am out of time and resource to support additional platforms currently, which is likely to make this issue pending.

Yet another option is to contact the Pale Moon team and request a fix for the sidebar.

**Comment by githmw** [comment]
Danny:

I sent an Email to Pale Moon today. I just discovered that the problem also occurs in the Find (CTRL+F) function, so I doubt that it is caused by Scrapbook X.

I'll let you know what they say.

Harry

**Comment by githmw** [comment]
Danny:

The problem is in the All In One Sidebar add-on that I use. Pale Moon made a change, which created the problem, and the 'fix' is changing the All In One Sidebar code. Very convoluted. If any of your other users complain, send this to this thread:
https://forum.palemoon.org/viewtopic.php?f=3&t=12457

I don't know what the fix is for the Find All toolbar I use.

Harry

**Comment by danny0838** [comment]
It seems that it's not a problem of ScrapBook X. Thank you for the investigation.
