### ISSUE TITLE
[Req] Adapting the metadata for a capture from a .maff open in a Firefox window:

### ISSUE THREAD

**Issue by pascallothar** [danny0838/firefox-scrapbook#107]
When I open a .maff created by the add-on _"Mozilla Archive Format, with MHT and Faithful Save" (by Christopher Ottley & Paolo Amadini)_ [https://addons.mozilla.org/fr/firefox/addon/mozilla-archive-format/] containing one or several tabs (for example the second tab of `file:///Users/pascallothar/Homebrew_Cask.html.maff` ), and when I capture the page, I will see in the **"Properties"** the date of the capture by Scrapbook X and the Source URL == _file:///Users/pascallothar/Homebrew_Cask.html.maff?web_archive_page=2_ , meaning that Scrapbook X was able to see that the page was coming from inside a .maff .

So would it be possible for you to change the behavior so, when Scrapbook X detect that the Source URL is a .maff file, it would take for Modification date, the date of the capture by Scrapbook X, for Creation date, the date stored in the `index.rdf` inside the .maff and for the URL, the URL stored in this `index.rdf`?

Actually, capturing with Scrapbook X a page that was previously captured by _"Mozilla Archive Format, with MHT and Faithful Save" (by Christopher Ottley & Paolo Amadini)_ can be used as a work-around for #96 .

It is also a way to import to Scrapbook X a (single tab) .maff you were reading, that is much quicker than **_"File Converter"_**.

**Comment by danny0838** [comment]
This feature is too ad hoc to MAFF, and we are unlikely to implement it. Please use ScrapBook X  Converter if the metadata in a .maff file is needed.
