### ISSUE TITLE
Feature request: an option to hide or auto-hide the ScrapBookToolbox

### ISSUE THREAD

**Issue by yfdyh000** [danny0838/firefox-scrapbook#111]
Use as a repository, I don't need an edit toolbar is always displayed.

All along, I use this style:
`#ScrapBookToolbox {display: none!important;}`

**Comment by danny0838** [comment]
We already have this function. Just uncheck "Edit Toolbar" in the ScrapBook X toolbar dropdown list.
![screenclip](https://cloud.githubusercontent.com/assets/531417/16711850/eeef6fa4-46a2-11e6-8f34-273c4d78b563.png)

**Comment by yfdyh000** [comment]
Thank you, I have never noticed it. Its visibility will be better, if it is on toolbar itself.

**Comment by danny0838** [comment]
I agree that the UI could be improved. But we have not come up with an ideal design yet. One thing we are considering is to install the ScrapBook X toolbar button at the first time the user installs ScrapBook X so that they are more likely to notice these functions.

**Comment by comonp** [comment]
Can there be a way to hide the 'Edit Toolbar' without using the 'ScrapBook X toolbar icon' as I don't wish to display it in my main toolbar?

**Comment by comonp** [comment]
Can there be an option to "auto-hide" the 'Edit Toolbar', i.e. have it disappear when the mouse cursor is not near it and have it appear when the mouse cursor is near.

![](http://cdn.ilovefreesoftware.com/wp-content/uploads/2016/04/automatically-hide-bookmarks-toolbar-of-Firefox.gif)
