### ISSUE TITLE
[req] Download linked files for all extensions

### ISSUE THREAD

**Issue by AceLewis** [danny0838/firefox-scrapbook#114]
In the file types you can put in a long list of file types of what you want to download e.g doc, docx, ppt, pptx however there is not a button to just download all file types. Maybe you can do a wild card however I tried in Scrapbook Plus and checking the code manually looks like there is not a wild card check.

This could be achieved via a wild card or by adding a new button, the wild card would be easiest to implement as you only need to change a bit of code around line 777 of saver.js.

**Comment by danny0838** [comment]
We are exactly working on this feature. Try the beta version (currently [1.13.0b5](https://addons.mozilla.org/en-us/firefox/addon/scrapbook-x/versions/?page=1#version-1.13.0b5)) and give us some feedback.

**Comment by AceLewis** [comment]
Do you have any form of instant contact e.g (Telegram, irc, Skype, Steam, ect) as I want to ask you a few questions, I have some problems that are very hard to address. I think the fact that the site is using force downloads messes it up and it seems to not download the file and just display a link to the original file. I would be glad to help you with testing as I think this extension is amazing.

**Comment by danny0838** [comment]
Which OS/Firefox/ScrapBook X version do you use?

You can send email or use Google Hangout via: danny[dot]0838[at]gmail[dot]com

**Comment by danny0838** [comment]
It seems to work as expected, and thus we close this issue.
