### ISSUE TITLE
Strip whitespace on custom extensions to correct for user input.

### ISSUE THREAD

**Issue by AceLewis** [danny0838/firefox-scrapbook#115]
I would recommend that this line:
`(", " + this.option["custom"] + ", ").indexOf(", " + ext + ", ") != -1 )`
should be changed so that [whitespace characters are stripped](http://stackoverflow.com/questions/360491/how-do-i-strip-white-space-when-grabbing-text-with-jquery) from `this.option["custom"]` and then you look at `indexOf("," + ext + ", ")` this would alow users who forget to put a space or accidentally type two spaces in to download what they intended.

**Comment by danny0838** [comment]
We'll probably rework the whole download linked file functionality. See #114 for detail.
