### ISSUE TITLE
Since 1.12.32, "Create MAF" and "Copy Page Info" are non responsive:

### ISSUE THREAD

**Issue by pascallothar** [danny0838/firefox-scrapbook#116]
1°) "**_Create MAF_**" was already not working in the "_**Manage**_" window.

Since Version 1.12.32 of Scrapbook X, it is not working anymore from the _**Sidebar**_ (nothing happen when you use it).

2°) I made a screen-shot of "**_MAF Creator Options..._**" dialog. I tried to resize it, but it is not resizable. Is a "OK" button missing? (It is very minor, only cosmetic, since the settings were saved and you could leave the dialog by escape key or by clicking the "Help" button inside the dialog.)

Since Version 1.12.32 of Scrapbook X, the **"Browse..." button** is not responsive anymore.

![maf options dialog](https://cloud.githubusercontent.com/assets/20140037/16903850/fea76894-4c78-11e6-9113-90d5b96aa75e.png)

3°) Since Version 1.12.32 of Scrapbook X, "**_Copy Page Info_**" doesn't work anymore (nothing happen when you use it). And when you want to open its configuration dialog the following error window pops up:

![copy page info error message](https://cloud.githubusercontent.com/assets/20140037/16903855/1ce3cc1c-4c79-11e6-9ea8-0dde5099c03b.png)

**Comment by danny0838** [comment]
[ScrapBook X MAF Creator 1.1.11](https://addons.mozilla.org/firefox/addon/scrapbookx-maf-creator/versions/?page=1#version-1.1.11) and [Scrapbook X CopyPageInfo 1.3.10](https://addons.mozilla.org/firefox/addon/scrapbook-copypageinfo/versions/?page=1#version-1.3.10) should have fixed the issues. Thank you for report.

**Comment by pascallothar** [comment]
Works for me.

Have a nice day.

Pascal.
