### ISSUE TITLE
[enhanc] "Twisty" for empty "non-folder-type folder":

### ISSUE THREAD

**Issue by pascallothar** [danny0838/firefox-scrapbook#117]
I have to congratulate you on your awesome idea of the "non-folder-type folder". I can see it as a real enhancement on the way to classify and organize stuff. Simple, but efficient.

---

When you "Convert to Folder" an item, you will not distinguish this new "status" until it is not empty anymore. I propose to show the "twisty" even for empty units. Or, even better ,a twisty with an other colour (why not the white one with black border you use for the "html tree"), or and other shape (square, cercle).

I don't know if it would be difficult to implement.

**Comment by danny0838** [comment]
We'd like to if possible. However, the twisty is internally handled by Firefox, and we currently cannot find a way to show a twisty for a "folder" having no subitems.

**Comment by pascallothar** [comment]
Oh! I see!

And putting a hidden item inside it like in the filesystem? Probably not possible! A dummy? A separator?

Anyway! We will not die because of this ... I hope so :-)
