### ISSUE TITLE
The text "Highlighter" is distracting in the 'Edit Toolbar'

### ISSUE THREAD

**Issue by comonp** [danny0838/firefox-scrapbook#118]
The text "Highlighter" is distracting in the 'Edit Toolbar', could there be an option not to have this text?

![](https://raw.githubusercontent.com/wiki/danny0838/firefox-scrapbook/images/gomita/InfoToolbar-3.png)

(Also, is there a way to disable the ['Edit Toolbar'](http://www.xuldev.org/scrapbook/features2.php#EditToolbar) without activating the Scrapbook Toolbar icon.)

**Comment by danny0838** [comment]
We will not implement this due to same reason for #119. You can create a new user style with something like this if you really want to hide it:

	#ScrapBookEditor #ScrapBookHighlighterPreview {
	  display: none;
	}

**Comment by comonp** [comment]
Is there a way to change the text of "Highligher" to "H", so that you can still see what way the highlighting will be?

**Comment by comonp** [comment]
There are 8 Highlighter options. Could 'white text' be an option?

**Comment by danny0838** [comment]
@comonp We will not implement a change for only an aesthetic reason. The style of highlighters can be customized in the options, or in the user preference for a more advanced purpose.
