### ISSUE TITLE
Background image missing when capturing certain webpages

### ISSUE THREAD

**Issue by comonp** [danny0838/firefox-scrapbook#121]
Saving this page with Scrapbook X
https://www.publicjobs.ie/candidateportal/
does not work properly.

**Comment by danny0838** [comment]
I don't have an accout of the site. Could you please provide:

1. Which aspect is not working properly? (You can provide a few screenshots for better illustration.)

2. Which ScrapBook X version do you use?

**Comment by comonp** [comment]
Menu Bar -> ScrapBook X -> Capture Page
gives
![screenshot](https://cloud.githubusercontent.com/assets/20687266/17374905/aa838636-59a6-11e6-9a1a-55867566875a.png)

ScrapBook X  1.12.38

**Comment by danny0838** [comment]
Oh, you find a special case that causes wrong URL resolution. We'll fix it in 1.13.*

**Comment by danny0838** [comment]
Fixed in 20fc7139f3c7443fd221d53ad83ccb2606c2302d.
