### ISSUE TITLE
Shortcut to Toggle focus between Scrapbook-X sidebar and Main Webpage Frame

### ISSUE THREAD

**Issue by 3dxpoint** [danny0838/firefox-scrapbook#125]
In Firefox if you do (SHIFT + F6) you can easily toggle focus between the URL bar and Main Webpage.
Similarly I'd like a shortcut to toggle between Scrapbook-X sidebar and the Main Webpage.

Thanks!

**Comment by danny0838** [comment]
We probably are not going to do that. However, it seems that most Firefox native sidebar pages, such as Bookmarks (Ctrl+B) or History(Ctrl+H), automatically sets focus to an element in it when it's opened. We would implement the same behavior for ScrapBook X sidebar: when it is toggled opened, automatically sets focus on the data tree, and when it's toggled closed, the focus will automatically go back to the main window.
