### ISSUE TITLE
Shortcut for Locate In Side Bar

### ISSUE THREAD

**Issue by 3dxpoint** [danny0838/firefox-scrapbook#126]
We have shortcuts for DOM eraser, save, undo etc. when we open a captured page.
Need a shortcut that'll locate the page in sidebar tree.

**Comment by danny0838** [comment]
Added "L" accesskey for locate of the editor toolbar in [1.13.0b11](https://github.com/danny0838/firefox-scrapbook/releases/tag/1.13.0b11). Have a test and see if it's as expected.

**Comment by 3dxpoint** [comment]
Not working.
Pressing L just brings up the "Select Folder" dialog which (on given a folder) just creates a bookmark(with URL as on-disk captured page).

**Comment by danny0838** [comment]
I cannot reproduce the case you mentioned. Note that this is an accesskey and you have to press it with the modifier your browser used to use for accesskeys (e.g. on Windows it's Alt or Alt+Shift). Also it only works when the editor toolbar is shown.

Please provide more detail about what you have done if it still happen.

**Comment by nodiscc** [comment]
Works as expected for me.
Access key on both Windows and Linux is `Alt`. So

 * `Alt+K` opens Scrapbook in the sidebar
 * `Alt+C` locates the current saved page in the sidebar.
 * ...
