### ISSUE TITLE
1.13.0b11 beta cannot clip this simple webpage properly

### ISSUE THREAD

**Issue by 3dxpoint** [danny0838/firefox-scrapbook#127]
http://www.circuit-magic.com/sinusoidal_circuits_analysis.htm
Capture page As with following options:
Images, media, styles
save data uri as file
keep linking
reorganize styles

The captured page remains in bold in the side bar.
The page is properly captured if we select contents of page manually.

Best of luck!

**Comment by danny0838** [comment]
I cannot reproduce the issue. Were you capturing other pages when you capture this page?

**Comment by 3dxpoint** [comment]
Cannot reproduce it now. Will report back if I see this again.

I was not capturing other pages when the issue occurred. I tried with different Capture page options before reporting this.

**Comment by danny0838** [comment]
OK. Let's wait and see. If it happens to occur again, you can press Ctrl+Alt+J to open the browser console and report if there are error messages of the scripts.
