### ISSUE TITLE
[Enhanc] Shortcut key to Manage Window

### ISSUE THREAD

**Issue by Fred969keMWft4** [danny0838/firefox-scrapbook#128]
Greetings.

Using keyconfig, it can bind a key to some functions like "capture selected" using:

`sbBrowserOverlay.execCapture(1, true , true , event.originalTarget.id);`

But to open Manage Window, it failed. I tried to bind a key with 
```
sbCommonUtils.openManageWindow(aRes, null);
or
sbCommonUtils.openManageWindow();
```

It did not work. Manage Window is often used but right now, I need to open the sidebar, click Tools, then Manage.

**Comment by danny0838** [comment]
It seems that we currently have a bug causing this. We'll fix it in the next release. Additionally we'll add manage window to the hotkey customization list.

**Comment by danny0838** [comment]
Done in [1.13.0rc1](https://github.com/danny0838/firefox-scrapbook/releases/tag/1.13.0rc1).
