### ISSUE TITLE
[bug] Copying an item doesn't work

### ISSUE THREAD

**Issue by pascallothar** [danny0838/firefox-scrapbook#131]
When you open the copied item, "file not found" is displayed.
I have found the reason:

![copy do not work](https://cloud.githubusercontent.com/assets/20140037/17644961/9c536e54-6186-11e6-9ddc-b9001a7993f1.png)

**Comment by danny0838** [comment]
I cannot reproduce this issue. Could you provide a procedure to produce it?

**Comment by pascallothar** [comment]
Here is the repertory (`ScrapBook/data/20160622153224/`) of the item to be copied:

![original directory](https://cloud.githubusercontent.com/assets/20140037/17660929/76b4f0a0-62cb-11e6-9be4-390262d4ae6a.png)

and here is the content of the index.dat (`ScrapBook/data/20160622153224/index.dat`) inside it:

![dat original](https://cloud.githubusercontent.com/assets/20140037/17660997/fb19e878-62cb-11e6-8b9c-3de90ac4f85c.png)

In the Sidebar, I right-click this item and click "Copy...".

![rightclicktocopy](https://cloud.githubusercontent.com/assets/20140037/17661079/767f4a4e-62cc-11e6-979e-beb7d3bee730.png)

A drop-down dialog shows up. I click "OK".

![choose folder](https://cloud.githubusercontent.com/assets/20140037/17661141/e46e5338-62cc-11e6-87d8-95fd0fcbaaaf.png)

A new item is created in the Sidebar. I right-click this new item and click "Open".

![open](https://cloud.githubusercontent.com/assets/20140037/17661216/4d670c0e-62cd-11e6-8105-0784b207d2ef.png)

In the window, "File not found" is displayed:

![file not found](https://cloud.githubusercontent.com/assets/20140037/17661260/934cb002-62cd-11e6-8206-b8530ad99da3.png)

Here is the repertory (`ScrapBook/data/20160622153225/`) of the newly created item:

![new directory](https://cloud.githubusercontent.com/assets/20140037/17661311/e7746d64-62cd-11e6-88a1-d73b7965c481.png)

As you can see, the original directory (`ScrapBook/data/20160622153224/`) has a copy (`ScrapBook/data/20160622153225/20160622153224/`) of itself in the new directory (`ScrapBook/data/20160622153225/`).

Also, there is a new index.dat (`ScrapBook/data/20160622153225/index.dat`). Here is its content:

![dat copy](https://cloud.githubusercontent.com/assets/20140037/17661480/f94b8f1c-62ce-11e6-8acd-889cf060f2c7.png)

As you can see the ScrapBook ID inside it has been successfully incremented. The remains is the same as in the original index.dat .

To make a comparison, here are the the two repertories:

![comparison](https://cloud.githubusercontent.com/assets/20140037/17661590/9a604de8-62cf-11e6-9609-57d22016392d.png)

Now, to correct the stuff, I made the following steps:
- delete `ScrapBook/data/20160622153225/20160622153224/index.dat`
- move all the files inside `ScrapBook/data/20160622153225/20160622153224/` and put them inside `ScrapBook/data/20160622153225/`
- delete the now empty directory `ScrapBook/data/20160622153225/20160622153224/`

Here is how it looks after having doing it:

![after moving](https://cloud.githubusercontent.com/assets/20140037/17661749/aea863c0-62d0-11e6-82d9-56ad9c93af1b.png)

Now I open again the new item (the one witch was displaying "File not found"):

![open](https://cloud.githubusercontent.com/assets/20140037/17661706/56910a34-62d0-11e6-89f5-ba452045f508.png)

Now, the page is correctly displayed:

![now it works](https://cloud.githubusercontent.com/assets/20140037/17661722/7880b7fc-62d0-11e6-935c-604b4b7eb20b.png)

**Comment by danny0838** [comment]
I don't see such issue. Your SBX, Fx, and OS version? Could you reproduce it on another machine?

**Comment by pascallothar** [comment]
I have found the reason.

[http://doxygen.db48x.net/mozilla/html/interfacensIFile.html#a0f23e8d6baa340aec9081208402f315f]
==> « **_copyTo_** may fail if the file already exists in the destination directory. »

So I have edited `scrapbook_x-1.13.0b13-fx.xpi` 
In the file `/modules/datasource.jsm` , I have changed the lines 213 and 214:

- Old:

        // copy content
        var oldDir = sbCommonUtils.getContentDir(oldID);
        var newDir = sbCommonUtils.getContentDir(newID);
        oldDir.copyTo(newDir.parent, newID);

- New:

        // copy content
        var oldDir = sbCommonUtils.getContentDir(oldID);
        // line deleted
        oldDir.copyTo(oldDir.parent, newID);     // 'newDir' edited to 'oldDir'


### Now, it works perfectly.

I conclude that **_copyTo_** has no specification when it comes to overwrite an existing directory (what about a normal file?) and, because of that, different implementations have different behaviors. They probably follow the philosophy of their own platform.

So one should always test (or be sure) that the file doesn't already exist in the destination directory. One could also remove the file.

**Comment by danny0838** [comment]
It seems that this issue is platform related. As the fix seems resonable, we'll implement it in the next release.

**Comment by pascallothar** [comment]
<h6 id="Exceptions_thrown" name="Exceptions_thrown">Exceptions thrown</h6>
<dl>
 <dt>
  <code>NS_ERROR_FILE_DESTINATION_NOT_DIR</code></dt>
 <dd>
  If the "newParentDir" is not a directory.</dd>
 <dt>
  <code>NS_ERROR_FILE_TARGET_DOES_NOT_EXIST</code></dt>
 <dd>
  Indicates that the current file path does not exist. It is not possible to copy a file that does not exist.</dd>
 <dt>
  <code>NS_ERROR_FILE_ALREADY_EXISTS</code></dt>
 <dd>
  Indicates that there is already a file named "newName" in the destination directory.</dd></dl>

**Comment by pascallothar** [comment]
Yes and no, as you can see at [https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIFile#copyTo()].

The method `nsIFile::copyTo` is cross-platform, but when it comes to the exceptions thrown, it is handled differently on different platforms (or, to be more precise, there is a lack of specifications to handle them in a standard way).

We can see the fact that on Windows, it creates a desirable behavior in the present case as a good luck. But, there is no safeguard to prevent a important directory to be overwritten in other cases.

**Comment by danny0838** [comment]
We've implemented the change in [1.13.0b14](https://github.com/danny0838/firefox-scrapbook/releases/tag/1.13.0b14). Please check if it works right on Mac.

**Comment by pascallothar** [comment]
Great! Thank you.
