### ISSUE TITLE
[bug] PARTIAL html tree isn't displayed correctly and "twisties" icons not responsive

### ISSUE THREAD

**Issue by pascallothar** [danny0838/firefox-scrapbook#132]
In the dialog showing up, the full tree is preselected. The resulting HTML Tree output is correct:

![html tree normal](https://cloud.githubusercontent.com/assets/20140037/17646153/3f3b57be-61ad-11e6-9efe-c32a91fa433b.png)

But if you deselect one ore more folders in this dialog, the resulting output is not correct:

![html tree 1](https://cloud.githubusercontent.com/assets/20140037/17646156/77e0048e-61ad-11e6-9ce6-8b7b2f9380eb.png)

![html tree 2](https://cloud.githubusercontent.com/assets/20140037/17646157/810bfda6-61ad-11e6-8c14-fea72b89e99b.png)

And more important, the twisties are not responsive. Only the top "expand/collapse all" icon is responsive

I made a multi-file diff of the `Scrapbook/tree/` directory.

- In `Scrapbook/tree/index.html`, I replaced all the `class="depth`**_`n`_**`"` by `class="depth`**_`n+1`_**`"`. It didn't work :-(

- In `Scrapbook/tree/index.html`, the only other stuff that could have an effect, was to replace the first `<ul>` by `<ul id="container-root">`. It worked :-) .

**Comment by danny0838** [comment]
I cannot reproduce this issue. Could you provide that:

1. Which browser do you use to view the HTML output page?

2. Which ScrapBook X version do you use to output the page?

3. What do you mean by saying "select"?

**Comment by pascallothar** [comment]
I have fixed it. See below.

---

Here are the answers to your questions:

1. Firefox 47.0.1 (actually it is the HTML output page itself, not even a capture).
2. SB X 1.13.0b13
3. When the _"Folder pick-up"_ dialog shows up, there is a pre-checked check-box saying **_"complete_** (or entire or whole or _**full**_, I don't know exactly, I am translating from the French dialog) _**tree output"**_. So all the folders are pre-**_selected_**. If you _deselect_ several Folders or even only one, the check-box is automatically unchecked. And the tree output becomes _PARTIAL_ (or NOT complete). So, I was talking about that when I was using the words pre- and de- _selected_. And when I was talking about _full/partial_ tree.

---

Here is the process used:

### Sidebar -> **"Tools"** -> **"HTML tree ..."**:

![sidebar - tools - html tree](https://cloud.githubusercontent.com/assets/20140037/17717022/0dc9c18e-63fb-11e6-817c-dded98edb4ce.png)

### Dialog when it shows up (Entire tree pre-selected). The HTML output will be CORRECT.

![complete tree](https://cloud.githubusercontent.com/assets/20140037/17717204/1dd51636-63fc-11e6-9210-c21d8abdcab7.png)

### And here, the dialog when I deselect one or more Folders. The HTML output will be CORRUPTED. And the TWISTIES will NOT be RESPONSIVE. But the "expand/collapse all" icon in the top banner is responsive.

![partial tree](https://cloud.githubusercontent.com/assets/20140037/17717238/5a4246ca-63fc-11e6-838a-9b0d3e3e806b.png)

---
---

To output the ENTIRE tree, the method `sbOutputService::execAll` is used and gives a correct result.

To output the PARTIAL tree, the method `sbOutputService::exec` is used and gives a CORRUPTED result.

I have edited **_scrapbook_x-1.13.0b13-fx.xpi//chrome/content/scrapbook/output.js_** at line 55:

- Old:

        this.content += "<ul>\n";

- New:

        this.content += '<ul id="container-root">' + "\n";


## Now, it works! :-)

Try again to see if, for a _**PARTIAL tree**_, it works on your computer. Because, I don't "feel" it could be different in an other browser or on an other platform. I would be very estonished if it were working on your computer.

**Comment by danny0838** [comment]
@pascallothar You are right. It is really something we have missed about. We'll implement this fix in the next release. Thank you.

**Comment by danny0838** [comment]
Implemented in 1.13.0b15.
