### ISSUE TITLE
Capture detail options design

### ISSUE THREAD

**Issue by danny0838** [danny0838/firefox-scrapbook#136]
This is probably the last of the most important thing we are going to do for 1.13.0.

As mentioned before, 1.13.0 implemented the feature that a capture, including a normal capture, a capture again, a link capture, a multiple capture, and combine and internalization, loads previously used options in the capture detail dialog as its options.

However, the current implementation still has several issues to be solved:
### Which options will be loaded is unclear and confusing

Will the currently selected folder to capture into apply to the next capture? Will the current check of "Save data URI as file" apply to the next page combine? Will the current setting of capture depth with 3 apply to the next link capture? ... Questions like them are difficult for the user to figure out...

Some capture modes cannot (or are undesirable to) support some specific capture options and will ignore them. There are also options bind the loaded document (such as the title and comment) and thus cannot and should not apply to future captures. As a result, we cannot simply apply ALL options to future non-detail capture.

So here comes our first challange: How to design the GUI so that the user can easily be sure that which option will apply to which type of future capture?
### It's annoying to perform a capture just for modifying capture options

For example, the previous capture detail dialog has "Frames" checked, and the user wants to perform a multiple capture without "Frames" be saved. How can he do?

The answer in the current implementation is to perform a dummy "Capture As" with "Frames" unchecked, delete the dummy captured item, and them perform the multiple capture....

Here is the second challenge: Is there a way to design the GUI so that the user doesn't have to perform a dummy capture just for changing the capture options?
### Big or small options?

The current implementation only have rough class such as "images", "media". However, there may be a user who wants to capture images but not background images. There may be a user who wants to capture <audio>s but not <vedio>s or <embed>s. 

To fulfill such demand we probably have to design "smaller" options such as "capture foreground images" and "capture background images", or "capture AUDIO", "capture VEDIO", "capture APPLET", "capture OBJECT", "capture EMBED", etc. However, such small options would be annoying for a user that simply wants to capture all media or not to capture any media since he has to check or uncheck lots of options for a small change.

There could be further demands like "remove all <img> tags instead of blanking them", "do not save fonts but link to the sources", etc. A way to fulfill such requirement is to modify the current yes-no type options into more detail options, such as:
- images: save, link to source, blank, comment-out, remove, ...
- media: save, link to source, blank, comment-out, remove, ...
- fonts: save, link to source, blank, comment-out, remove, ...
- frames: save, link to source, blank, comment-out, remove, ...
- links: save merged, save, link to source, blank, comment-out, remove, ...
- ......

This satisfies users with such demands, but could also confuse more other users. 

The third challenge: How to design the GUI to satisfy a user who just wants rough options and one who wants very detail control?

---

We currently have no good idea about them, and we are seeking for any good idea.

**Comment by danny0838** [comment]
Partially solved by adding a dialog for default save (capture) option in [1.13.0](https://github.com/danny0838/firefox-scrapbook/releases/tag/1.13.0). We'll seek for further optimization in the future.

**Comment by shyangs** [comment]
☑ 專家模式 (Expert Mode)


考慮到不是每個人都會正則表達式(RegExp), 應仿照一些軟體在介面上做一個「專家模式」的勾選方塊.

一般人模式(傳統介面)下用勾選方塊 ☑圖片 來隱藏 專家模式(新版介面)對應的正則  bmp|gif|ico|jp(e?g|e|2)|png|tiff? 詳細內容.

如果以後有更細緻的專家模式功能(需要填寫正則、腳本), 也可以考慮不在一般人模式提供.

**Comment by danny0838** [comment]
看起來是可行的方向，不過專家模式恐怕無法使用和一般模式相同的設定值，這樣所有相關功能反而要針對兩種模式寫兩套設定值，會讓系統變得更複雜且容易出錯。
