### ISSUE TITLE
option to remove heading in 'Output Tree as HTML...'

### ISSUE THREAD

**Issue by comonp** [danny0838/firefox-scrapbook#137]
Can there be an option to remove the 'ScrapBook' heading (and green arrow source links), just like the original ScrapBook.

![untitled](https://cloud.githubusercontent.com/assets/20687266/17820734/29270106-6646-11e6-8c04-de40bfdfa473.png)
(Also, when I click the search icon, I get _Unable to load database: ./cache.rdf_

**Comment by danny0838** [comment]
We probably are not going to implement micro-options for output. You can use custom.css and custom.js to modify it if you really really need it.

Which browser do you use to browse the output page? Some browser like Chrome and Safari are paranoid about security and does not allow local AJAX access to external xml files unless specifically configured (and in somes such as Android Chrome it seems to be unavailable). You can check [this document](https://github.com/mrdoob/three.js/wiki/How-to-run-things-locally) for more detail.

**Comment by comonp** [comment]
> Which browser do you use to browse the output page?

I am using Firefox.

(I even set security.fileuri.strict_origin_policy to false as per [that document](https://github.com/mrdoob/three.js/wiki/How-to-run-things-locally), and it also didn't work.)

**Comment by danny0838** [comment]
Have you created the fulltext cache before performing the output?

**Comment by danny0838** [comment]
Close stale issue without further response.
