### ISSUE TITLE
UnMHT stopped working on sidebar with right click

### ISSUE THREAD

**Issue by g-user** [danny0838/firefox-scrapbook#139]
I used scrapbook and UnMHT for creating single snapshots of a webpage: I captured the page and in the sidebar I used UnMHT with a right click.
UnMHT right click stopped working with 1.12.32, on the right click nothing happens.  This behavior started with Version 1.12.33. Tested with various versions of UnMHT and firefox 45, 47 and 48. Are there incompatibilities from the mentioned version?

**Comment by danny0838** [comment]
I didn't get what exactly you mean by mentioning about "in the sidebar I used UnMHT with a right click" and "UnMHT right click". Could you describe them a bit further and/or provide a few screenshots?

**Comment by g-user** [comment]
I open the scrapbook-x sidebar, right click on a previously captured entry and then choose MHT.

**Comment by danny0838** [comment]
I understand. It seems to be due to some change in 1.12.32. In 1.13.0 it should work again.

**Comment by g-user** [comment]
Ok, 1.13.0 works again! 
Sorry for bothering you, but I tried a 1.13 Beta some days before and then it takes some time to find out on which version the errors started (I tried several versions of firefox, UnMHT and scrapbook x in different combinations)
