### ISSUE TITLE
Navigation keys misbehaviour in 1.13 and 1.13.1

### ISSUE THREAD

**Issue by Herb0yk** [danny0838/firefox-scrapbook#141]
In following installations all the standard navigation keys including spacebar of FF are acting like pressing Alt+K : PaleMoon 26.4, FF 45.3 ESR, FF and Cyberfox 48.0.2, FF 49b8, FF Developer latest.
Also entering aan address manually has the effect. Pretty annoying, please elabourate.

Reverting to 1.12.38 solves the problem so far.
The nightly is not affected.

**Comment by danny0838** [comment]
Does customizing the hotkey make a difference?

**Comment by danny0838** [comment]
Also, your OS?

**Comment by Herb0yk** [comment]
The systems are Win 10 both 64 and 32 bit show the same behaviour. Not sure if it is relevant, all my Foxes are Portableapps versions.
A VM-XP-Installation doesn't show the issue.

Removing the hotkey or changing it makes no difference.

I would have expected that a lot of other people have this too, but nobody showed up so far, odd?

**Comment by danny0838** [comment]
Have you restarted Firefox after changing the hotkey?

Could you check what value of `extensions.scrapbook.key.sidebar` in the `about:confg` is?

**Comment by Herb0yk** [comment]
The key is changed to Shift+A and works. However the behaviour with all Navigation keys and addressbar is still there. I found also any entry in the searchbox confirmed with Enter results in this issue.

**Comment by danny0838** [comment]
I'll be busy and may not survay this issue quickly. Could you check if it happens on Win8 or Win7? (Also check if changing the hotkey solves the issue)

**Comment by Herb0yk** [comment]
Changing the hotkey doesn't solve the issue. A changed hotkey works however the navigation keys and Enter and Spacebar still act wrong.

I have no Win7 or Win8 anymore and can't check. Going back to 1.12.38solves it so far.

**Comment by danny0838** [comment]
I don't have Win8 and Win10 and this issue doesn't seem to be reproducible on Win7. You may have to test by yourself.

First, install this [test version](https://github.com/danny0838/firefox-scrapbook/releases/tag/1.13.1.1-shortcuttest). (Note: It is not signed and you have to disable signature requirement for your Firefox first to install it)

Second, restart Firefox, press `Ctrl+Shift+J` to enter Browser Console, check only the "Logging" tab and report the result. Like this:

![1](https://cloud.githubusercontent.com/assets/531417/18416750/5d60822e-784f-11e6-83c9-9e06c92c0af3.jpg)

Please do this on Win10, Win10 with all other addons disabled, WinXP, WinXP with all other addons disabled.

**Comment by Herb0yk** [comment]
The Konsole Key  throws me also into Scrapbook window, but here it goes


Could not read chrome manifest 'file:///C:/Users/Herb/Desktop/!PFF/FirefoxPortableStd/App/firefox/chrome.manifest'.
Warning: attempting to write 11163 bytes to preference extensions.xpiState. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.
NS_ERROR_FILE_NOT_DIRECTORY: Component returned failure code: 0x8052000c (NS_ERROR_FILE_NOT_DIRECTORY) [nsILocalFile.directoryEntries]
datasource.jsm:70
Warning: NetUtil.asyncFetch() requires the channel to have one of the security flags set in the loadinfo (see nsILoadInfo). Please create channel using NetUtil.newChannel()
No chrome package registered for chrome://bamboo/skin/img/feed.png
[Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIIOService2.newChannelFromURI2]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: resource://app/modules/WindowsPreviewPerTab.jsm :: _imageFromURI :: line 78"  data: no]
(unbekannt)
No chrome package registered for chrome://bamboo/skin/img/feed.png
Warning: NetUtil.asyncFetch() requires the channel to have one of the security flags set in the loadinfo (see nsILoadInfo). Please create channel using NetUtil.newChannel()
No chrome package registered for chrome://bamboo/skin/img/feed.png
Warning: NetUtil.asyncFetch() requires the channel to have one of the security flags set in the loadinfo (see nsILoadInfo). Please create channel using NetUtil.newChannel()
1473657589938	Browser.SelfSupportBackend	ERROR	_loadSelfSupport - Non HTTPS URL provided: ""
Log.jsm:753
Tastenereignis ist in manchen Tastaturlayouts nicht verfügbar: Taste="c" Modifikatoren="accel,alt"browser.xul
Tastenereignis ist in manchen Tastaturlayouts nicht verfügbar: Taste="i" Modifikatoren="accel,alt,shift"browser.xul
DEPRECATION WARNING: toggleSidebar() is deprecated, please use SidebarUI.toggle() or SidebarUI.show() instead
You may find more details about this deprecation at: https://developer.mozilla.org/en-US/Add-ons/Code_snippets/Sidebar
chrome://browser/content/browser-sidebar.js 324 toggleSidebar
chrome://browser/content/browser.xul 1 oncommand

Deprecated.jsm:79
SidebarFocusedscrapbook.js:1059:5
No chrome package registered for chrome://bamboo/skin/img/feed.png
Async execution error (11): database disk image is malformed
WindowsJumpLists.jsm:442
Async execution error (11): database disk image is malformed
WindowsJumpLists.jsm:442
1473657826309	addons.update-checker	WARN	Update manifest for e10srollout@mozilla.org did not contain an updates property
1473657826909	addons.update-checker	WARN	Update manifest for BlockAutorefreshWhitelist@abx did not contain an updates property
1473657827447	addons.update-checker	WARN	Update manifest for firefox@getpocket.com did not contain an updates property
1473657827496	addons.update-checker	WARN	Update manifest for {972ce4c6-7e08-4474-a285-3208198ce6fd} did not contain an updates property
1473657827634	addons.update-checker	WARN	Update manifest for {F32A21DF-2CD3-48d6-9EE1-2C17F988541F} did not contain an updates property
Signature Verification Error: the signature on this .jar archive is invalid because the certificate used to sign this file has an unrecognized issuer.
Warning: attempting to write 11158 bytes to preference extensions.xpiState. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.
Async execution error (11): database disk image is malformed
WindowsJumpLists.jsm:442
`Could not read chrome manifest 'file:///C:/Users/Herb/Desktop/!PFF/FirefoxPortableStd/App/firefox/chrome.manifest'.
Warning: attempting to write 11163 bytes to preference extensions.xpiState. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.
NS_ERROR_FILE_NOT_DIRECTORY: Component returned failure code: 0x8052000c (NS_ERROR_FILE_NOT_DIRECTORY) [nsILocalFile.directoryEntries]
datasource.jsm:70
Warning: NetUtil.asyncFetch() requires the channel to have one of the security flags set in the loadinfo (see nsILoadInfo). Please create channel using NetUtil.newChannel()
No chrome package registered for chrome://bamboo/skin/img/feed.png
[Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIIOService2.newChannelFromURI2]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: resource://app/modules/WindowsPreviewPerTab.jsm :: _imageFromURI :: line 78"  data: no]
(unbekannt)
No chrome package registered for chrome://bamboo/skin/img/feed.png
Warning: NetUtil.asyncFetch() requires the channel to have one of the security flags set in the loadinfo (see nsILoadInfo). Please create channel using NetUtil.newChannel()
No chrome package registered for chrome://bamboo/skin/img/feed.png
Warning: NetUtil.asyncFetch() requires the channel to have one of the security flags set in the loadinfo (see nsILoadInfo). Please create channel using NetUtil.newChannel()
1473657589938	Browser.SelfSupportBackend	ERROR	_loadSelfSupport - Non HTTPS URL provided: ""
Log.jsm:753
Tastenereignis ist in manchen Tastaturlayouts nicht verfügbar: Taste="c" Modifikatoren="accel,alt"browser.xul
Tastenereignis ist in manchen Tastaturlayouts nicht verfügbar: Taste="i" Modifikatoren="accel,alt,shift"browser.xul
DEPRECATION WARNING: toggleSidebar() is deprecated, please use SidebarUI.toggle() or SidebarUI.show() instead
You may find more details about this deprecation at: https://developer.mozilla.org/en-US/Add-ons/Code_snippets/Sidebar
chrome://browser/content/browser-sidebar.js 324 toggleSidebar
chrome://browser/content/browser.xul 1 oncommand

Deprecated.jsm:79
SidebarFocusedscrapbook.js:1059:5
No chrome package registered for chrome://bamboo/skin/img/feed.png
Async execution error (11): database disk image is malformed
WindowsJumpLists.jsm:442
Async execution error (11): database disk image is malformed
WindowsJumpLists.jsm:442
1473657826309	addons.update-checker	WARN	Update manifest for e10srollout@mozilla.org did not contain an updates property
1473657826909	addons.update-checker	WARN	Update manifest for BlockAutorefreshWhitelist@abx did not contain an updates property
1473657827447	addons.update-checker	WARN	Update manifest for firefox@getpocket.com did not contain an updates property
1473657827496	addons.update-checker	WARN	Update manifest for {972ce4c6-7e08-4474-a285-3208198ce6fd} did not contain an updates property
1473657827634	addons.update-checker	WARN	Update manifest for {F32A21DF-2CD3-48d6-9EE1-2C17F988541F} did not contain an updates property
Signature Verification Error: the signature on this .jar archive is invalid because the certificate used to sign this file has an unrecognized issuer.
Warning: attempting to write 11158 bytes to preference extensions.xpiState. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.
Async execution error (11): database disk image is malformed
WindowsJumpLists.jsm:442
Could not read chrome manifest 'file:///C:/Users/Herb/Desktop/!PFF/FirefoxPortableStd/App/firefox/chrome.manifest'.
Warning: attempting to write 11163 bytes to preference extensions.xpiState. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.
NS_ERROR_FILE_NOT_DIRECTORY: Component returned failure code: 0x8052000c (NS_ERROR_FILE_NOT_DIRECTORY) [nsILocalFile.directoryEntries]
datasource.jsm:70
Warning: NetUtil.asyncFetch() requires the channel to have one of the security flags set in the loadinfo (see nsILoadInfo). Please create channel using NetUtil.newChannel()
No chrome package registered for chrome://bamboo/skin/img/feed.png
[Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIIOService2.newChannelFromURI2]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: resource://app/modules/WindowsPreviewPerTab.jsm :: _imageFromURI :: line 78"  data: no]
(unbekannt)
No chrome package registered for chrome://bamboo/skin/img/feed.png
Warning: NetUtil.asyncFetch() requires the channel to have one of the security flags set in the loadinfo (see nsILoadInfo). Please create channel using NetUtil.newChannel()
No chrome package registered for chrome://bamboo/skin/img/feed.png
Warning: NetUtil.asyncFetch() requires the channel to have one of the security flags set in the loadinfo (see nsILoadInfo). Please create channel using NetUtil.newChannel()
1473657589938	Browser.SelfSupportBackend	ERROR	_loadSelfSupport - Non HTTPS URL provided: ""
Log.jsm:753
Tastenereignis ist in manchen Tastaturlayouts nicht verfügbar: Taste="c" Modifikatoren="accel,alt"browser.xul
Tastenereignis ist in manchen Tastaturlayouts nicht verfügbar: Taste="i" Modifikatoren="accel,alt,shift"browser.xul
DEPRECATION WARNING: toggleSidebar() is deprecated, please use SidebarUI.toggle() or SidebarUI.show() instead
You may find more details about this deprecation at: https://developer.mozilla.org/en-US/Add-ons/Code_snippets/Sidebar
chrome://browser/content/browser-sidebar.js 324 toggleSidebar
chrome://browser/content/browser.xul 1 oncommand

Deprecated.jsm:79
SidebarFocusedscrapbook.js:1059:5
No chrome package registered for chrome://bamboo/skin/img/feed.png
Async execution error (11): database disk image is malformed
WindowsJumpLists.jsm:442
Async execution error (11): database disk image is malformed
WindowsJumpLists.jsm:442
1473657826309	addons.update-checker	WARN	Update manifest for e10srollout@mozilla.org did not contain an updates property
1473657826909	addons.update-checker	WARN	Update manifest for BlockAutorefreshWhitelist@abx did not contain an updates property
1473657827447	addons.update-checker	WARN	Update manifest for firefox@getpocket.com did not contain an updates property
1473657827496	addons.update-checker	WARN	Update manifest for {972ce4c6-7e08-4474-a285-3208198ce6fd} did not contain an updates property
1473657827634	addons.update-checker	WARN	Update manifest for {F32A21DF-2CD3-48d6-9EE1-2C17F988541F} did not contain an updates property
Signature Verification Error: the signature on this .jar archive is invalid because the certificate used to sign this file has an unrecognized issuer.
Warning: attempting to write 11158 bytes to preference extensions.xpiState. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.
Async execution error (11): database disk image is malformed
WindowsJumpLists.jsm:442
Could not read chrome manifest 'file:///C:/Users/Herb/Desktop/!PFF/FirefoxPortableStd/App/firefox/chrome.manifest'.
Warning: attempting to write 11163 bytes to preference extensions.xpiState. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.
NS_ERROR_FILE_NOT_DIRECTORY: Component returned failure code: 0x8052000c (NS_ERROR_FILE_NOT_DIRECTORY) [nsILocalFile.directoryEntries]
datasource.jsm:70
Warning: NetUtil.asyncFetch() requires the channel to have one of the security flags set in the loadinfo (see nsILoadInfo). Please create channel using NetUtil.newChannel()
No chrome package registered for chrome://bamboo/skin/img/feed.png
[Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIIOService2.newChannelFromURI2]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: resource://app/modules/WindowsPreviewPerTab.jsm :: _imageFromURI :: line 78"  data: no]
(unbekannt)
No chrome package registered for chrome://bamboo/skin/img/feed.png
Warning: NetUtil.asyncFetch() requires the channel to have one of the security flags set in the loadinfo (see nsILoadInfo). Please create channel using NetUtil.newChannel()
No chrome package registered for chrome://bamboo/skin/img/feed.png
Warning: NetUtil.asyncFetch() requires the channel to have one of the security flags set in the loadinfo (see nsILoadInfo). Please create channel using NetUtil.newChannel()
1473657589938	Browser.SelfSupportBackend	ERROR	_loadSelfSupport - Non HTTPS URL provided: ""
Log.jsm:753
Tastenereignis ist in manchen Tastaturlayouts nicht verfügbar: Taste="c" Modifikatoren="accel,alt"browser.xul
Tastenereignis ist in manchen Tastaturlayouts nicht verfügbar: Taste="i" Modifikatoren="accel,alt,shift"browser.xul
DEPRECATION WARNING: toggleSidebar() is deprecated, please use SidebarUI.toggle() or SidebarUI.show() instead
You may find more details about this deprecation at: https://developer.mozilla.org/en-US/Add-ons/Code_snippets/Sidebar
chrome://browser/content/browser-sidebar.js 324 toggleSidebar
chrome://browser/content/browser.xul 1 oncommand

Deprecated.jsm:79
SidebarFocusedscrapbook.js:1059:5
No chrome package registered for chrome://bamboo/skin/img/feed.png
Async execution error (11): database disk image is malformed
WindowsJumpLists.jsm:442
Async execution error (11): database disk image is malformed
WindowsJumpLists.jsm:442
1473657826309	addons.update-checker	WARN	Update manifest for e10srollout@mozilla.org did not contain an updates property
1473657826909	addons.update-checker	WARN	Update manifest for BlockAutorefreshWhitelist@abx did not contain an updates property
1473657827447	addons.update-checker	WARN	Update manifest for firefox@getpocket.com did not contain an updates property
1473657827496	addons.update-checker	WARN	Update manifest for {972ce4c6-7e08-4474-a285-3208198ce6fd} did not contain an updates property
1473657827634	addons.update-checker	WARN	Update manifest for {F32A21DF-2CD3-48d6-9EE1-2C17F988541F} did not contain an updates property
Signature Verification Error: the signature on this .jar archive is invalid because the certificate used to sign this file has an unrecognized issuer.
Warning: attempting to write 11158 bytes to preference extensions.xpiState. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.
Async execution error (11): database disk image is malformed
WindowsJumpLists.jsm:442

**Comment by danny0838** [comment]
It seems to be an issue of other addons, especially the one called Bamboo. Please uninstall or disable those addons and try again.

**Comment by Herb0yk** [comment]
Doesn't make a difference, I'll stick with the previous version.
Thanks for your effort.

**Comment by danny0838** [comment]
Could you install the test version and report the result in the Browser Console (with other addons disabled, of course)? It's essential for us to investigate the issue.

**Comment by mrdc** [comment]
Can confirm on W7 SP1 x86, FF 48.0.2, tried Reset preferences - nothing changes.
How to reproduce in my case: close FF, open FF in Private window, press any key - side bar pops-up
![scrb1](https://cloud.githubusercontent.com/assets/16876990/18508247/1a676b0c-7a7c-11e6-8bf5-f30d1671158e.png)
![scrb2](https://cloud.githubusercontent.com/assets/16876990/18508246/1a6473fc-7a7c-11e6-95f1-b39680c15084.png)
![scrb3](https://cloud.githubusercontent.com/assets/16876990/18508248/1a6a3eb8-7a7c-11e6-9e4c-a180699fe3d9.png)

**Comment by mrdc** [comment]
Was not able to install the test build, because of it's not signed, turned off signing check in `about:config` - no changes, installed Developer Build - checking now.

**Comment by Herb0yk** [comment]
Cannot support anything currently, wife is in hospital 400km away, sorry.

**Comment by mrdc** [comment]
Oh, we are not in a hurry - do your best to help your family first.

**Comment by Herb0yk** [comment]
A complete virgin setup 48.0.2 portable and testversion Scrapbook X, everything works fine but it doesn't identify my Standard Scrapbookfolder, which is a share over multiple different browser versions.

Here is the initial Konsole report:

`Could not read chrome manifest 'file:///C:/Users/Herb/Desktop/Workbench/FirefoxPortableStd/App/firefox/chrome.manifest'.
Warning: NetUtil.asyncFetch() requires the channel to have one of the security flags set in the loadinfo (see nsILoadInfo). Please create channel using NetUtil.newChannel()
Content Security Policy: Die Direktive 'frame-src'  sollte nicht mehr verwendet werden. Bitte verwenden Sie stattdessen die Direktive 'child-src'.(unbekannt)
Warning: NetUtil.asyncFetch() requires the channel to have one of the security flags set in the loadinfo (see nsILoadInfo). Please create channel using NetUtil.newChannel()
Leerer String an getElementById() übergeben.frameworks-88471af1fec40ff9418efbe2ddd15b6896af8d772f8179004c254dffc25ea490.js:7:24531
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf about:blank blockiert ("base-uri https://github.com").(unbekannt)
Leerer String an getElementById() übergeben.github-49de9034d1fe0af1c01c710fbad9a9a40a3621073e5f78546c32f8bc0bf81191.js:7:27457
Leerer String an getElementById() übergeben.frameworks-88471af1fec40ff9418efbe2ddd15b6896af8d772f8179004c254dffc25ea490.js:9:6863
Tastenereignis ist in manchen Tastaturlayouts nicht verfügbar: Taste="c" Modifikatoren="accel,alt"browser.xul
Tastenereignis ist in manchen Tastaturlayouts nicht verfügbar: Taste="i" Modifikatoren="accel,alt,shift"browser.xul
1474018762841	addons.update-checker	WARN	Update manifest for e10srollout@mozilla.org did not contain an updates property
Async execution error (11): database disk image is malformed
WindowsJumpLists.jsm:442
1474018763014	addons.update-checker	WARN	Update manifest for firefox@getpocket.com did not contain an updates property
1474018763209	addons.update-checker	WARN	Update manifest for {972ce4c6-7e08-4474-a285-3208198ce6fd} did not contain an updates property
Warning: NetUtil.asyncFetch() requires the channel to have one of the security flags set in the loadinfo (see nsILoadInfo). Please create channel using NetUtil.newChannel()
getAttributeNode() sollte nicht mehr verwendet werden. Verwenden Sie stattdessen getAttribute().disco-c28c992487502f051106.js:30:12260
getAttributeNode() sollte nicht mehr verwendet werden. Verwenden Sie stattdessen getAttribute().disco-c28c992487502f051106.js:30:12260
DEPRECATION WARNING: toggleSidebar() is deprecated, please use SidebarUI.toggle() or SidebarUI.show() instead
You may find more details about this deprecation at: https://developer.mozilla.org/en-US/Add-ons/Code_snippets/Sidebar
chrome://browser/content/browser-sidebar.js 324 toggleSidebar
chrome://browser/content/browser.xul 1 oncommand

Deprecated.jsm:79
Async execution error (11): database disk image is malformed
WindowsJumpLists.jsm:442
NS_ERROR_FILE_NOT_DIRECTORY: Component returned failure code: 0x8052000c (NS_ERROR_FILE_NOT_DIRECTORY) [nsILocalFile.directoryEntries]
datasource.jsm:70
Async execution error (11): database disk image is malformed
WindowsJumpLists.jsm:442
`

**Comment by danny0838** [comment]
@mrdc I cannot reproduce it on W7 SP1 x86, FF 48.* by doing what you have described: "close FF, open FF in Private window, press any key - side bar pops-up.". A signed version of the beta version was uploaded. Could you try with that version and report the debug result? Also, to prevent a possible conflict with other addons, please try with all other addons disabled.

The debug result you reported in FF Developer Edition 50.0a2 private mode doesn't seem to be related with ScrapBook X since it still shows up even if ScrapBook X is disabled.

**Comment by danny0838** [comment]
@Herb0yk @mrdc This issue has been reproduced in some limited contexts such as installing a software that requires a system reboot and having not rebooted the system.  We are still not sure about the real cause but have found something that might cause it.  Could you have a test on [this version](https://github.com/danny0838/firefox-scrapbook/releases/tag/1.3.1.1a2) and see if this issue is resolved or not?

**Comment by Herb0yk** [comment]
I've checked with a virgin FF49.0.1 setup and the Problem did not shw up, however I could not locate my Std.Scrabook folder.

I've checked with my  normal profile in a FF51 Developer environment and the problem still persists.

**Comment by danny0838** [comment]
@Herb0yk Could you provide the ScrapBook X version that you "checked with a virgin FF49.0.1"?

As for what you mentioned "I could not locate my Std.Scrapbook folder"... it seems like issue #140. If it's the case, refer to it for solution. If it's not the case, please explain it further so that we can start investigating it.

**Comment by danny0838** [comment]
Close stale issue as no further discussion for over a year.
