### ISSUE TITLE
Broken links in search results page

### ISSUE THREAD

**Issue by mitlenatch** [danny0838/firefox-scrapbook#144]
I am pleased with the more comprehensive search capabilities of ScrapBook X as compared to the original ScrapBook. Unfortunately, the actual links in the search results page are all broken. Clicking on any of them produces a Firefox error page with a message like this: "File not found; Firefox can't find the file at /C:/Users/Foo/ScrapBook/data/20160208084951/index." Note that the URL ends with "index." ... the html suffix is missing. Using Firefox ESR 45.2.0 with ScrapBook X 1.13.1. Please let me know if you need more details.

Edit: If you click "Locate in Sidebar Tree" and then click on the ScrapBook item in the sidebar, that works just fine. It's just the preview link in the search results pane that seems to be broken.

**Comment by danny0838** [comment]
Did you just shifted from ScrapBook or ScrapBook Plus? If yes, you'd have to update the fulltext cache to make the fulltext search function work correctly on ScrapBook X.

**Comment by mitlenatch** [comment]
Boom, you nailed it. My bad for not remembering your Compatibility Notes.
PS: Do I have to worry about the many messages indicating "Removing... urn:scrapbook:item[...]" that I see during the fulltext cache update?
Thanks much for your help, and for Scrapbook X. It looks like it has a lot of improvements over the original.

**Comment by danny0838** [comment]
No, you don't. Due to the format change there would be lots of "remove"s when updating a SB/SBP cache to SBX. It will work as usual in the future.

**Comment by danny0838** [comment]
[Compatibility Notes](https://github.com/danny0838/firefox-scrapbook/wiki/Compatibility).
