### ISSUE TITLE
Rebuilding Cache Started Removing (seemingly) Random Entries

### ISSUE THREAD

**Issue by willos7** [danny0838/firefox-scrapbook#145]
I switched from Scrapbook Vanilla to Scrapbook X for the first time. I didn't get to look at it long enough, it went by too fast, but after it rebuilt the cache so I could search, as it neared completion, it started removing some sporadic entries.  I assumed it was just cleaning things up. 

I temporarily switched back to vanilla to see if searching still worked (after disabling X) and in my first random search attempt about 1/2 of the notes I clicked on were missing when the titles were clicked.  I have 8 years worth of stuff, so I'm not sure what all was and wasn't affected, but now it seems I don't have the option to switch back if I needed to.

Any idea what may have happened?  I'm sure I missed something as I didn't get to read the message fully (on the building cache window). 

*EDIT*
Alright, I just found out it's only happening with those certain scraps when I attempt to view them from the search results window. When I use "locate in sidebar" option, the scraps display properly.

**Comment by danny0838** [comment]
ScrapBook X has changed the format of fulltext cache and thus it's not compatible with legacy ScrapBook or ScrapBook Plus. You have to rebuild the fulltext cache at least once when you shift from or to legacy ScrapBook or ScrapBook Plus to get the fulltext search functionality work right. Also see: [Compatibility](https://github.com/danny0838/firefox-scrapbook/wiki/Compatibility).

By the way, I'm not sure what you really mean by mentioning "ScrapBook Vanilla". The above answer is based on the assumption that you mean the legacy ScrapBook by Gomita.

**Comment by willos7** [comment]
Thanks, I appreciate the feedback.  Unfortunately when it is near the end of the cache building phase, during the "Removing... urn:scrapbook:item...." phase, there is a major delay between processing these entries, and then eventually it hangs. I've tried letting it go overnight, I've tried several other attempts after restarts. Now Gomita's version is doing it too, I get the unresponsive script notice with the option to continue. I hit continue as many times as it allows before freezing the browser indefinitely, and never completing. 

I was using the current versions of the extensions as well as Firefox. I tried an older version of the Pale Moon browser (based on Firefox) and had the exact same result.

I suppose I shouldn't have have let it grow to 14 GB and should've split up into multiple scrapbooks, but since I've never had issues with it I just let it grow wild. It seems that there isn't much I can try, but if you've got any ideas I'd appreciate it.

**Comment by danny0838** [comment]
How many items do you have in your database? (You can use Tools > Calculate to get it)

Although ScrapBook does not have a hard limit for a ScrapBook database, a very large database actually could exceed the capability of the computer and leads to a nonreponsive result. You can try deleting the cache.rdf in the ScrapBook directory and rebuild the fulltext cache again. If it still doesn't work maybe separating your ScrapBook database into multiple smaller databases is the way to go.

**Comment by willos7** [comment]
Hi,
Deleting the cache.rdf solved the problem. Thank you for the suggestions! The calculate size tool also became unresponsive, but Windows Explorer reports 15,540 folders... I'm amazed I haven't run into these issues sooner. Lesson learned, I will break it down into smaller databases.

Thanks again.
