### ISSUE TITLE
error on archiving memory alpha page

### ISSUE THREAD

**Issue by treaki** [danny0838/firefox-scrapbook#151]
hi,

i have tryed to archive the following page:

http://de.memory-alpha.wikia.com/wiki/ATR-4107

and have got this error message (in a windows what i havent seen before and dont have when i try to archive other pages)

ScrapBook ERROR: Failed to write file '[somepath]/ScrapBook/data/20161020152433/quote.css'.

[Exception... "Component returned failure code: 0x80500001 [nsIScriptableUnicodeConverter.charset]"  nsresult: "0x80500001 (<unknown>)"  location: "JS frame :: resource://scrapbook-modules/common.jsm :: sbCommonUtils.writeFile :: line 463"  data: no]

i am using firefox on debian 8 (latest version of the debian repro) and the following version of the plugin
## Allgemeine Informationen

Name: Firefox
Version: 45.4.0
Build-ID: 20160921204512
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
Fenster mit mehreren Prozessen: 0/1 (Standard: false)
Abgesicherter Modus: false
## Erweiterungen

[...]

Name: ScrapBook X
Version: 1.13.1
Aktiviert: true
ID: scrapbookx@addons.mozilla.org

[...]

hope that can be fixed.

thanks for scrapbookx, its a really powerful tool, please keep up the good work

**Comment by treaki** [comment]
no matter that after i have clicked onto the ok buttons of all this windows it lookes like the page has got archived in scrapbook correctly

**Comment by danny0838** [comment]
Does the issue repeatedly happen whenever you try to save that web page?

**Comment by treaki** [comment]
yes, it (still) happens every time i try to archive a page on memory alpha. what can i do to get you enough information, is there a logfile or so i can send you?

**Comment by danny0838** [comment]
The website assigns a charset that is not supported by Firefox for a CSS file, and we have a bug causing Firefox not saving the CSS file completely. It's out of luck that the CSS file is not used in the web page so you don't see a problem.

We'll fix the issue in the next release so that the CSS will be saved, but since the charset is not supported, some text in the CSS may still be corrupted.

**Comment by danny0838** [comment]
Fixed in 41d8d9c55fda405bd2da9cb3eaddce76a2140b44.
