### ISSUE TITLE
save-as broken in scrapbook x

### ISSUE THREAD

**Issue by gred22** [danny0838/firefox-scrapbook#152]
All of a sudden I cannot do a save-as in scrapbook x.  Instead of the save-as drop down, I get a window with a general info and a options button, but then just the "title" of the page, and no way to select a folder or make a new folder, as usual.
![screen shot 2016-10-20 at 9 36 17 am](https://cloud.githubusercontent.com/assets/14096463/19562251/9c20fa48-96a9-11e6-9ebd-dfcf9c066f91.jpg)

**Comment by danny0838** [comment]
Can you expand the dialog by dragging the border downwards?

**Comment by gred22** [comment]
Yes that works - don’t know why the window got smaller.

thanks - Mark

**Comment by gred22** [comment]
I have multiple scrapbook databases from multiple computers and many years.  My latest database was over 30 GB, but firefox on my macbook air bogged down with such a large database and often locked up and had to be restarted.  So I began a new scrapbook database.  I would like to be able to access all my scrapbook databases and do searches on folder titles OR searches on stored web pages.  Is there any way to be able to access many very large scrapbook databases, and do searches on just folder titles, etc?

I know I can have multiple databases selectable from within scrapbook.  But how can I search, folder names for example, across multiple databases at once?

How can I access a large (30+GB) database without firefox and scrapbook delaying many many seconds, or locking, which happens even if a scrapbook save is not in progress/

thanks - Mark

**Comment by danny0838** [comment]
@gred22 It doesn't seem to be related with this topic. Could you raise another issue if you meant to discuss about it?
