### ISSUE TITLE
display problem in archiving window

### ISSUE THREAD

**Issue by treaki** [danny0838/firefox-scrapbook#153]
Hi,

here on my debian gnu/linux 8 with some mate based desktop env ive got a problem when i select (click) on a column in the archiving window it get completely blank. I guess the text color is set to white in the assumption that the background gets dark but somehow dosent get dark. I have heard from other linux users that they had that problem after switching to scrapbook x.

here are some screen shots:
![bildschirmfoto-archivieren - scrapbook](https://cloud.githubusercontent.com/assets/1477872/19562657/6e8b2e9e-96dd-11e6-93bd-b04ef492b92e.png)

![bildschirmfoto-archivieren - scrapbook-1](https://cloud.githubusercontent.com/assets/1477872/19562663/72c9e842-96dd-11e6-918e-3385dc233549.png)

its a quite minor issue cause you can just click elsewhere but it still would be nice it it could be fixed.

thanks

**Comment by danny0838** [comment]
Which Firefox  and ScrapBook X version do you use?

**Comment by treaki** [comment]
@danny0838 see #151

**Comment by danny0838** [comment]
Could you make sure if this issue happens on other platforms?

**Comment by danny0838** [comment]
This issue should probably be fixed in 1.13.4. However I don't have the exact platform you use, please confirm and report whether it helps.

**Comment by treaki** [comment]
hi,

dont understand me wrong,i dont want to be rude insulting but as i see it:

@danny0838 i dont have other platforms than mine fine working debian system where i use scrapbook x right now. i see no point in installing an OS from Redmond (that which are like with submarine, when you open up...) or even California (that thing about rotten fruits (cause someone bite into int and then they are on the showoff like this likely for ever and have to be tossed away and replaced until they are eaten up all the time (no information processing but pure wast production systems...)  ) in finding out that issue that is probably caused by wrong used meta colors to match to any ui design...

if you really want to fix that issue @danny0838 i could provide you with and export (ova file) of an newly created debian vm just for that purpose. But i dont want to risk/spend any time on it if there is just a chance of 10% that this problem gets fixed afterwards.

thanks in advance for your help

PS: sorry, i guess ive done to many annotations again...

**Comment by danny0838** [comment]
No, you don't have to try another platform. Just test and report if ScrapBook X 1.13.4 fixed the issue on your debian gnu/linux 8 or not.

**Comment by treaki** [comment]
whatever you did, now it lookes perfect (guess it done an autoupdate in the background)

thanks a lot

**Comment by danny0838** [comment]
That's fine.
