### ISSUE TITLE
problem with archiving pages that link to pages still archived

### ISSUE THREAD

**Issue by treaki** [danny0838/firefox-scrapbook#157]
Hi,

lets think about following situation: 

You are on a page which you want to archive (e.g. http://tibasicdev.wikidot.com/68k:thecalcs )

on that page is somewhere a link to a page called math and after that a link to a page called arithmetic which directly forwards (using http code 30x) to a section of this page already archived like math#arithmetic. Then the archiving process will hang on this point and wount continue until you press skip. Please fix that...

![bildschirmfoto-archivieren - scrapbook-3](https://cloud.githubusercontent.com/assets/1477872/19830529/5ba4e5a8-9dfa-11e6-9c06-abfd36d90b57.png)

here in this example the two who are still done but highlighted green had exactly that problem

thanks

**Comment by danny0838** [comment]
Thank you for reporting. This issue should be fixed in v1.13.3. Please confirm it.

**Comment by danny0838** [comment]
Close stale issue as no further discussion for over an year.
