### ISSUE TITLE
关于“默认保存设定”

### ISSUE THREAD

**Issue by yfdyh000** [danny0838/firefox-scrapbook#158]
建议不自动保存对其修改，比如某个网页需要深度保存1层（保存页面为...），设置后下次“保存页面”到文件夹时，也会套用此设置。同样，是否保存图片等设定也会因一次操作而静默影响后续行为。
也可以添加一个选项到“保存”对话框或者“选项”对话框来决定行为。

建议选项-组织-默认保存设定加入“深度保存”的选项，进一步明确。

希望“保存页面为...”的文件夹默认使用最后使用（保存）的文件夹，而非根文件夹。如果用户需要根文件夹，可以方便的重新选取。

**Comment by danny0838** [comment]
自 1.14.0rc1 開始在儲存選項中加入「記住目前選項」，只有在勾選時才會把目前選項記住。但因架構因素，目前仍然只有透過「儲存為...」對話框會啟動深入儲存。至於記住最後使用的儲存資料夾，是個不錯的設計方向，但涉及比較複雜的架構調整，要再研議。

歡迎測試及提供回饋。

**Comment by yfdyh000** [comment]
記住目前選項 已看到和使用良好。感谢增强。
