### ISSUE TITLE
Documents files not downloaded and not linked correctly

### ISSUE THREAD

**Issue by kisskrool** [danny0838/firefox-scrapbook#159]
Hi,

I have tried the new version 1.13.3. I have encountered an issue which doesn't occur with 1.12.35 version.

Documents files (zip, rar, doc) are recognized in green while using 'Capture as...' function with a depth of 1. But they are not saved in the corresponding Scrapbook folder and the links of the saved page are the original ones, not the file URLs of the Scrapbook folder.

Please try to fix this issue, as i have now downgraded the version to be able use this functionnality.

Thanks

**Comment by danny0838** [comment]
Could you provide the URL of the web page in problem, and the save settings you actually use?

**Comment by kisskrool** [comment]
Hi,

Let's try this URL for example: http://immortality-280.narod.ru/

With default settings in the 'Capture As...' menu and depth 1, files are found.

![settings](https://cloud.githubusercontent.com/assets/829145/20639641/6143eede-b3c9-11e6-978c-f56912bcd0b4.png)

It has .doc .rar and zip files. 

So i select only those I'm interested in, and they show in green. But not downloaded.

![downloading](https://cloud.githubusercontent.com/assets/829145/20639646/7f170aae-b3c9-11e6-857d-12b910ac560c.png)

**Comment by kisskrool** [comment]
Ok. I have found. The options for file formats need to be uncommented and the first '#' removed. It works differently as the precedent version I've used where it used checkboxes.

**Comment by danny0838** [comment]
Seems that the problem has been solved. Sorry for creating such confusion.

**Comment by kisskrool** [comment]
Yes, that's not easy to grasp at first. Thanks for this awesome extension.
