### ISSUE TITLE
Different file format for on disk storage

### ISSUE THREAD

**Issue by grotesque** [danny0838/firefox-scrapbook#160]
Over a ~decade my Scrapbook database has scaled to ~600,000 files and ~30,000 folders. I now put the database in its own separate partition with low cluster size (like 1k or 2k instead of default 4k) and a larger MFT to mitigate performance issues due to NTFS limitations.

Danny should consider changing the on disk format to something else (like MHT or MAFF). This will basically zip the captured webpage and create a single file entry instead of N.

Also most of the files in the scrapbook database are duplicates(eg. some website has logo.jpg and this file is present in every page that is clipped from that website). In long term we should also try to have some kind of lazy file level de-duplication operation or some lazily replace duplicate files with hardlinks/softlinks/shortcuts solution.

**Comment by danny0838** [comment]
It's a nice idea and we did consider about it. The problem is that non-plain files cannot be viewed directly via the browser, making "Output HTML tree" useless and we have to write a local server for ScrapBook X to read the saved data.

**Comment by nodiscc** [comment]
I have found a way to de-duplicate files in Scrapbook data directories by using [jdupes](https://github.com/jbruchon/jdupes). 

> jdupes can convert duplicate files in hardlinks or relative softlinks.

I have only tested it on Linux (Debian) on an ext4 filesystem with a relatively low number of files, but according to the project documentation, jdupes should also work on Windows, and with large file sets, on any filesystem that supports symlinks/hardlinks.

> The problem is that non-plain files cannot be viewed directly via the browser, making "Output HTML tree" useless

MHT/MAFF files can be opened in Firefox using [this addon](https://addons.mozilla.org/en-US/firefox/addon/mozilla-archive-format/)

**Comment by pbpb** [comment]
In general, please always use the native file system structure (or, say posix), the simplest possible html, and avoid special techniques to save a few bytes.  Try to make everything human-readable, and allow some hope of viewing stuff when scrapbook[-x] is not available, even if 'output-to-html' was never done.

**Comment by danny0838** [comment]
We are not going to do this in ScrapBook X. We may consider implementation of such feature for [Web ScrapBook](https://github.com/danny0838/webscrapbook), though.
