### ISSUE TITLE
Question: Future of ScrapBook X - WebExtensions or ...?

### ISSUE THREAD

**Issue by mseliger** [danny0838/firefox-scrapbook#162]
Firefox has announced that it will support only web extensions with the end of year 2017:
[Add-ons in 2017] (https://blog.mozilla.org/addons/2016/11/23/add-ons-in-2017)
How is the future of ScrapBook X? Is it possible to make a web extension of the add-on? Or do you want to support / switch to another browser like Pale Moon which will not drop xul support?
The license of Scrapbook X is open-source? If the development of Scrapbook X is stopped - than I will perhaps make an fork for Pale Moon.
Greetings and hoping of further support, Maria

**Comment by yfdyh000** [comment]
> The license of Scrapbook X is open-source?

https://github.com/danny0838/firefox-scrapbook/blob/master/LICENSE.txt

**Comment by mseliger** [comment]
Yes
Look here: 
(https://addons.mozilla.org/de/firefox/addon/scrapbook-x/?src=search)
Source code released under Mozilla Public License, version 2.0
(https://en.wikipedia.org/wiki/Mozilla_Public_License)

**Comment by danny0838** [comment]
This issue doesn't go beyond #85 and #93, and the key is still same—It doesn't depend on us. It depends on when WebExtension API will provide sufficient functionality for ScrapBook X.

**Comment by wonderkid** [comment]
Will ScrapBook X be able to use in 2018? If Scrapbook X no longer works, how can I view my old saved scrapbook data?

I have been using Scrapbook for many years and it seems like the owner is no longer updating it and I cannot use the drag to sidebar function now.

I am really happy to see Scrapbook X as an alternative to Scrapbook. 

Thanks for creating Scrapbook X.

**Comment by mseliger** [comment]
You can use your ScrapBook X data after 2018.  Use in ScrapBook X Tools | Output Tree as HTML. This will create a folder tree in your ScrapBook directory and create a file named index.html. If you open this file in the browser you have your ScrapBook tree (be careful: if your ScrapBook is big, then the loading of the file will take some seconds or minutes).
Another solution is to change to Pale Moon (http://www.palemoon.org/). At the moment there's no problem to use the last ScrapBook X version with the Pale Moon Browser which is a firefox fork (based on an older version of firefox, now with an own engine and with own development). Pale Moon will not remove the XUL support. It's not an "old" firefox, it's now independent from the development of the Gecko engine. I use this browser on daily basis in Windows and in Lubuntu. Many firefox extensions will work with Pale Moon (only some newer not).
Greetings, Maria

**Comment by wonderkid** [comment]
If I install Pale Moon can I still use Firefox? I mean sometimes I will use Palemoon with Scrapbook X to scrapbook stuff and sometimes I will use Firefox with Scrapbook X to scrapbook stuff. 

I will set both Palemoon Scrapbook X and Firefox Scrapbook X saved items location to the same directory, and I wonder if I open either Palemoon or Firefox will I see the same saved scrapbook data?
I hope that will not corrupt data or anything.

**Comment by mseliger** [comment]
Yes, wonderkind. I use my data (ScrapBook X, Newsfox, SimpleMail, Reminderfox) with Firefox and with Pale Moon on Ubuntu and on Windows operating system.  Both versions of the ScrapBook X engine are the same - so there is no problem.

**Comment by wonderkid** [comment]
Thanks mseliger.

I was going to install Pale Moon and read more about Pale Moon. I read this article http://ths.gardenweb.com/discussions/3373876/anyone-know-the-pale-moon-browser-and-or-firefox-addon-scrapbook it seems like Pale Moon will automatically migrate some settings or whatever from Firefox to Pale Moon and cause something to disappear and some of the scrapbook contents disappeared.

Do you know if Pale Moon and Firefox share or use any data/files together? Or are they completed different software that do not interfere with each other?

One more question, if lets say I added a webpage to Scrapbook X in Pale Moon, I will be able to see that webpage inside Firefox Scrapbook X correct? (both Scrapbook X (Pale Moon) and Scrapbook X (Firefox) are saving to the same folder location.)

**Comment by mseliger** [comment]
No, Firefox and PaleMoon do not share data files normally. The profile of Firefox is Mozilla\..., the profile of Pale Moon is normally Moonchild\... You should have two profiles - one for Firefox, one for Pale Moon, because the settings in the profiles are different. But you can use the ScrapBook Data in Pale Moon and Firefox (Manage archives). All my ScrapBook archives are on a portable drive and I can use them with Firefox or with Pale Moon. But be careful - don't open the same archive at the same time in Firefox and in Pale Moon: If you store a new element in the ScrapBook it might be delete because you have the ScrapBook opened two times.

**Comment by wonderkid** [comment]
You said: "don't open the same archive at the same time in Firefox and in Pale Moon: If you store a new element in the ScrapBook it might be delete because you have the ScrapBook opened two times."
Do you mean if I have scrapbook opened in Firefox and in Pale Moon, if I store (scrapbook) a new webpage either in Firefox or Pale Moon, that page might not be stored? What is the thing that is deleted?

**Comment by mseliger** [comment]
I don't know if it is really deleted. But I think if you close the ScrapBook with the new element but let the ScrapBook without the new element opened and do some things on the opened ScrapBook, it might be that the element is not stored or not visible (defect). I think it is not stored in the tree but on the content is stored on the hard disk. The tree is not up-to-date then. You may test this with the function "Calculation of size".

**Comment by wonderkid** [comment]
Is there a way to refresh scrapbook tree? Maybe close and reopen Firefox/Pale Moon?

**Comment by mseliger** [comment]
Maybe - i haven't try it, but I think it's better not to have the tree open in two programs (only if you are reading - but not for storing). You may also have one ScrapBook tree in Pale Moon and one in Firefox. With Import / export you can send data between these two trees.

**Comment by wonderkid** [comment]
I have installed Pale Moon but I could not figure out how to install firefox addons to it. Is there any guide? I could not find any when in google.

**Comment by mseliger** [comment]
Just like in Firefox. Tools | Add-Ons. There you can search for Firefox-Addons which can be installed directly in Pale Moon. Or you download the Pale Moon or Firefox Add-Ons first and install them with Tools | Add-Ons | Install Add-On from File.

**Comment by ertyz** [comment]
Someone can write very simple html-server receiver (on node.js for example).
Scrapbook can send all pages to this local server, and this server can store data on the local drive.
This is solved problems with no essential api for datastore in webextensions, right?

**Comment by danny0838** [comment]
We just proved that it's basically possible to save a web page with current available WebExtension API. Here are the demos: [Firefox version (use Firefox Developer Edition since it's not reviewed)](https://addons.mozilla.org/firefox/addon/web-scrapbook/), and [Chrome version](https://chrome.google.com/webstore/detail/web-scrapbook/oegnpmiddfljlloiklpkeelagaeejfai).

However, there are still many many limitations in WebExtension, such as:
1. For Forefox saving a web page or a file from file:/// is not allowed.
2. For Chrome, the user must disable "Ask where to save each file before downloading.", or he will get numerous prompts on each saving.
3. Local file access is very restricted, and therefore editing and saving a saved web page is probably not possible.

**Comment by pbpb** [comment]
In answer to some of the questions above:

*  I use scrapbook (not scrapbook-x) simultaneously from multiple machines and multiple firefox profiles.  There is never a problem with clobbering things either if I add stuff here and look there, or delete here and look there.  In fact I find that this is a much better way of syncing bookmarks than all the cloud-based 3rd party approaches.

* Scrapbook reloads some or all of the tree spontaneously sometimes, I believe, when you close and open subtrees.  However, to be sure that the displayed tree is in sync with data, I use multi-scrapbook and toggle between scrapbooks.  That way, the index is reloaded.

**Comment by danny0838** [comment]
Close this issue as our policy is clear now: We won't add support of e10s and WebExtension for ScrapBook X. For a WebExtension "port", use [Web ScrapBook](https://github.com/danny0838/webscrapbook).

We'll keep basic maintenance for ScrapBook X, but new features and large changes are unlikely. If there were a bug related with them it would be unlikely fixed, either.
