### ISSUE TITLE
Save not shown in list of items be it in different directories, the root of a directory or in folder, 

### ISSUE THREAD

**Issue by Big-Kate** [danny0838/firefox-scrapbook#164]
The software claims to have saved the information. Sometimes a dialog box comes up saying save completed. but whatever happens the information is not apparently saved
I have tried to look both in the main route and in the side bar not there
I have tried changing the name of what is saved - no effect
I have tried to change the directory, so that one directory is stored elsewhere - no effect 
Created a new blank directory - no effect
Tried saving in different scrapbooks - no effect
Tried saving in scrapbook root's - no effect
Tried saving in various folders - no effect
Randomly it will start working again a few times and then stop 

This is driving me nuts
Please help 
Kate

**Comment by danny0838** [comment]
Could you provide the URL of the web page you have problem with?

**Comment by danny0838** [comment]
Close stale issue that is not complete and has no further response.
