### ISSUE TITLE
Migrate ScrapbookX to Chrome

### ISSUE THREAD

**Issue by neokleon** [danny0838/firefox-scrapbook#165]
Hi, Danny
I was wondering if you could migrate this extension to Chrome,
Chrome is more powerful then Firefox and Scrapbook X is the last reason i stick to Firefox.
If you can please clone this extension to work with Google Chrome, then i shall be very happy and obliged.

Regards

**Comment by danny0838** [comment]
No, Chrome is not more powerful than Firefox. It just has a simpler extension framework than Firefox. Many many features Firefox provided is not possible in Chrome's extension API, including the essential functionalities of ScrapBook X: one is the direct access to the frame (or iframe) document in a different domain, and the other is direct access to the filesystem. Without those functionalities it's impossible to make ScrapBook X work on Chrome.

This is a question raised many times. Refer to our [Milestone v2.0.0 related issues](https://github.com/danny0838/firefox-scrapbook/milestone/2) for more detail.

**Comment by danny0838** [comment]
We have a Chrome "port" as [Web ScrapBook](https://github.com/danny0838/webscrapbook).
