### ISSUE TITLE
Ability to show comments in HTML tree

### ISSUE THREAD

**Issue by nodiscc** [danny0838/firefox-scrapbook#172]
Hi,
would it be possible to display Scrapbook comments (`comment` field in each item's `index.dat`) in the HTML tree output?

I use Scrapbook X to save a lot of documentation (since the original Scrapbook, thanks!), and store short summaries, reading notes etc. in comments. Being able to view them in the HTML tree listing would be great (with a toggle?). Example below of a scrapbook folder with 1 item commented

**> A folder**
**> Another folder**
**V Example folder**

 * IEEE 1394 [>](https://en.wikipedia.org/wiki/IEEE_1394)
 * Serial ATA [>](https://en.wikipedia.org/wiki/Serial_ATA)
 * ATX [>](https://en.wikipedia.org/wiki/ATX)
   >Other form factors  WTX (356×425) AT (350×305) Baby-AT (330×216) BTX (325×267) ATX (305×244) SSI CEB (305x267) EATX (Extended) (305×330) LPX (330×229) microBTX (264×267) NLX (254×228) Ultra ATX (367×244) microATX (244×244) DTX (203×244) FlexATX (229×191) Mini-DTX (203×170) EBX (203×146) Mini-ITX (170×170) EPIC (Express) (165×115) Mini ATX (150×150) ESM (149×71) Mini-STX (140×147) Nano-ITX (120×120) COM Express (125×95) ESMexpress (125×95) ETX (114×95) XTX (114×95) Pico-ITX (100×72) PC/104 (-Plus) (96×90) ESMini (95×55) SMARC (82×80) Qseven (70×70) EOMA68 (86x54) mobile-ITX (60×60) CoreExpress (58×65) 
 * Stepping Level
 * PCI Express
 * Conventional PCI
 * UEFI

**>Another folder**
...

@danny0838 would you be ok to add this?
Otherwise can you point me to the right direction on how to implement it?

Thanks again

**Comment by danny0838** [comment]
We might implement it if we come up with a neat solution. Before that, you can implement it via the `tree/custom.js` script.

**Comment by nodiscc** [comment]
I don't use this software anymore and legacy add-ons are no longer supported by Firefox, therefore I'm closing this issue.
