### ISSUE TITLE
特定網頁無法擷取

### ISSUE THREAD

**Issue by bluelovers** [danny0838/firefox-scrapbook#174]
這個網址在擷取網頁時
會直接無反應(沒有任何錯誤通知 也沒有擷取到任何內容)
就像按下後 什麼都沒發生一樣

[http://asurafantasy.sakura.ne.jp/sfc/feda/](http://asurafantasy.sakura.ne.jp/sfc/feda/)

**Comment by danny0838** [comment]
已修正 (484fa7630c49323b823aadf1e284692fbccc4cb6)
