### ISSUE TITLE
Sorting: When "Group by type" is enabled, bookmarks are not grouped

### ISSUE THREAD

**Issue by nodiscc** [danny0838/firefox-scrapbook#176]
After sorting folders by ID/Title/... from the sort dialog, with the "Group by Type" option checked, `bookmark` items are not grouped together (they're sorted as if they were normal captures).

Shouldn't they be grouped separately? The same way as`notes` and `folders` are.

Edit: Considering this maybe `marked` items should also be grouped separately?

**Comment by danny0838** [comment]
Implemented in [1.14.0rc5](https://github.com/danny0838/firefox-scrapbook/releases/tag/1.14.0rc5). Thank you for the feedback.

**Comment by nodiscc** [comment]
I understand. I mostly use the `marked` state to differentiate single article pages from "index/table of contents" pages that link to other resources/documentation/stuff. No pressing need to change this, it was just a remark about consistency.

Thank you very much for fixing this and https://github.com/danny0838/firefox-scrapbook/issues/175 so quickly :clap:
