### ISSUE TITLE
Window Manage Scrapbook ist empty.

### ISSUE THREAD

**Issue by ha-kg** [danny0838/firefox-scrapbook#177]
I use Firefox 50.1.0 with Scrapbook x 1.13.16 and when I want to mange my scapbooks (export, import or delete) there are no srapboooks shwon in the Manage Scrabbook windows
Doe any one has a solution. Deleting the addon and new installation was not helpful.
Thank you

**Comment by danny0838** [comment]
1. We don't have ScrapBook X 1.13.16. Do you mean 1.13.6?

2. What do you mean "the Manage Scrabbook windows"? If you mean the "Manage" window, it's for managing ScrapBook saved data items, not ScrapBooks (databases).

**Comment by ha-kg** [comment]
Sorry you are right its is 1.13.6 and I meana the saved data items I mean the enclosed windows
![scrapbook](https://cloud.githubusercontent.com/assets/25171599/22023042/dd40c13c-dcc4-11e6-8373-7c96d0aa110b.png)

**Comment by danny0838** [comment]
I cannot reproduce this issue currently. Which OS do you use? Does it always happen or only sometimes? Could you identify a specific procedure to reproduce the issue?

**Comment by ha-kg** [comment]
My OS is Windows10. But I Window found a solution when I open the in full Window mode the items will be shown

**Comment by danny0838** [comment]
@ha-kg Does this issue still happen in the latest version (1.14.4)?

**Comment by danny0838** [comment]
Close stale issue that has no further response.
