### ISSUE TITLE
Manage mode: Add 'Copy source URLs' to right-click menu

### ISSUE THREAD

**Issue by nodiscc** [danny0838/firefox-scrapbook#183]
Hello, would it be possible to add a `Copy source URLs` menuentry to the `Tools>` submenu that appears when right-clicking items in manage mode (alongside `Display files/Move/Copy...`)?

This would help greatly when users want to share or otherwise copy links to pages they've scrapbooked.

Examples:

 - Send a collection of useful links to someone by IM, mail: select contents of your `Useful links` scrapbook folder, right-click, `Copy source URLs`, paste in messaging client.
 - Export URLs of your current reading list: Select contents of your `ReadLater` folder, paste to a text editor, save.
 - Etc.

Thanks again

**Comment by danny0838** [comment]
This can be done by installing [Scrapbook X CopyPageInfo](https://addons.mozilla.org/zh-TW/firefox/addon/scrapbook-copypageinfo/).

**Comment by nodiscc** [comment]
Thank you, problem solved :)
