### ISSUE TITLE
Bookmarking by dragging with Alt key is not working

### ISSUE THREAD

**Issue by tanmatra** [danny0838/firefox-scrapbook#184]
Firefox 51.0.1, Scrapbook 1.14.0rc6, Windows 7.

I think it worked until Firefox 51 or 50.

**Comment by MisterAlanBradley** [comment]
Dragging is not working since 51 on my end. With v50 its no problem.

Here is some explanation from the original Scrapbook rating: https://addons.mozilla.org/de/firefox/addon/scrapbook/reviews/840502/

**Comment by tanmatra** [comment]
Can it be fixed at least after v52?

**Comment by danny0838** [comment]
Fixed in ScrapBook X 1.13.9 and 1.14.0rc7. Thank you for report.
