### ISSUE TITLE
drag and drop to scrapbook X sidebar broken

### ISSUE THREAD

**Issue by q-t-p** [danny0838/firefox-scrapbook#187]
Since firefox 51 drag and drop to scrapbook sidebar opens a new window instead of capturing the page to scrapbook.

**Comment by danny0838** [comment]
This issue was already raised (#184) and should be fixed in ScrapBook X 1.13.9 (AMO reviewing) and 1.14.0rc7 (beta).

**Comment by wonderkid** [comment]
When will 1.13.9 be out? Can I download now?

**Comment by wonderkid** [comment]
Is the issue fixed in 1.14.0rc7 (beta) ? Can I install 1.14.0rc7 (beta) into Firefox 51.0.1 ?

**Comment by wonderkid** [comment]
Any answers will be appreciated. Has the owner abandoned the forum/addon?

**Comment by danny0838** [comment]
@wonderkid  As mentioned above, this issue should have been fixed in 1.14.0rc7 and you can simply install it for a confirmation. 1.13.9 is currently reviewed by AMO, and will be available if it passed.

**Comment by wonderkid** [comment]
If I install 1.14.0rc7 now, in future when the 1.13.9 is available will it automatically update to 1.13.9?

**Comment by danny0838** [comment]
I think AMO will choose the larger version number, so 1.14.0rc7 will not be updated to 1.13.9, and will be updated to e.g. 1.14.1.

**Comment by wonderkid** [comment]
When 1.13.9 is available, I can just uninstall 1.14.0rc7 and install 1.13.9 correct?

Is there any cons of using the beta versions forever, Since 1.14.0rc7 will auto be updated e.g. 1.14.1, I guess I will be getting newer bugs fixed versions faster?

**Comment by wonderkid** [comment]
I notice Version 1.14.0rc8 is out today.

The version I installed a few days ago is 1.14.0rc7. I just closed firefox and reopen again and did not get auto update to 1.14.0rc8. How to set auto update?
