### ISSUE TITLE
Scrapbook X hangs/freezes firefox

### ISSUE THREAD

**Issue by Maiking** [danny0838/firefox-scrapbook#188]
Scrapbook X hangs/freezes firefox when I go to the Firefox Menu (alt-f), and choose the Scrapbook X menu. Using Firefox 48 and Scrapbook X  1.13.8

**Comment by danny0838** [comment]
Which is your OS? Does it happen occasionally or always?

**Comment by Maiking** [comment]
Windows 7 SP1
Always
I have a lot of saved pages(2000)

**Comment by danny0838** [comment]
Does it freeze forever or just for a while? I also have a ScrapBook database with > 2000 items. This ought not be the sole factor causing Firefox to freeze.

**Comment by Maiking** [comment]
It freezes for about 1 minute.

**Comment by danny0838** [comment]
It is more likely hardware related if the freeze would recover spontaneously after a while. Did you observe the same issue on different computers?

**Comment by danny0838** [comment]
Close this issue since it seems more likely a hardware issue. If you have further information it's welcome to leave a reply here.
