### ISSUE TITLE
Export creates two directories. One Empty and One With the Contents.

### ISSUE THREAD

**Issue by Tornchi** [danny0838/firefox-scrapbook#189]
In Windows, sometimes when exporting scrapbook items, you would get an empty directory with the expected title as its name, but also a directory named with its scrapbook id having the actual contents.

Test:
In Windows,
Rename a scrapbook item to "test" followed by 60+ spaces and then try to export it.

Fix:
I've tracked the bug to [trade.js line 388](https://github.com/danny0838/firefox-scrapbook/blob/master/chrome/content/scrapbook/trade.js#L388) 

It seems that if the substring(0,60) results in there being any trailing spaces, the problem will occur. 
Windows specifically prohibits trailing spaces in directory and filenames.  It will create them just without the trailing spaces, as well as return true that they exist. But will fail when trying to copy to them.

Add a right trim or trim after the substring to ensure there are no trailing spaces.  I'd do it myself but I don't know JavaScript.

**Comment by danny0838** [comment]
Thank you for investigating and reporting this issue. We'll fix it in the next release.

**Comment by danny0838** [comment]
Fixed in recent 80bf53366005572e8a5c9d71f52993f52d892179.
