### ISSUE TITLE
Scrapbook to scrapbook x and scrapbook x to scrapbook?

### ISSUE THREAD

**Issue by wonderkid** [danny0838/firefox-scrapbook#190]
I am using Scrapbook 1.5.14 addon, Firefox 51.0.1, Windows 10 Home and the drag and drop to scrapbook side bar does not work now.

I intend to install Scrapbook X addon and use it as I saw the drag and drop to sidebar problem is fixed in the next version.

Q1) If I install Scrapbook X and uninstall Scrapbook, will all my previous Scrapbook saved pages data still be able to work fine in in Scrapbook X? 

Q2) I will start using Scrapbook X to save data and in future if I switch from Scrapbook X to Scrapbook, will all my previous Scrapbook X saved pages data still be able to work fine in in Scrapbook? 

Thanks

**Comment by MisterAlanBradley** [comment]
I can answer your Q1 since i switched to Scrapbook X from Scrapbook recently. Till now I didn´'t have any problems with pages scraped by Scrpbook in the X version. It is all working like a charm + you than have some additional functions from the X version.

All the settings from the original version are kept when installing the X version.

Q2 can be answered by me since I didn't switch back and I am not planning anyways.

**Comment by wonderkid** [comment]
Is Scrapbook X going to be updated forever?

I ask Q2 because I have used Scrapbook for many years and it seems like it is no longer (or slow) updated. I wish to use Scrapbook X for a long time. Usually a new addon is good, but after some time the author might lose interest or become busy and ignore it, if that happens I have no choice and have to look for another addon again so I prefer to use addon that the saved scrapbook data is non proprietary and the data can be usable with other addon, so even if one day the addon author disappears I can still view the data.

**Comment by danny0838** [comment]
@wonderkid Basically ScrapBook X data share the same structure with ScrapBook. However, there would be something that could go into problem and need to be noticed. You can see https://github.com/danny0838/firefox-scrapbook/wiki/Compatibility for more detail.

**Comment by wonderkid** [comment]
I have read https://github.com/danny0838/firefox-scrapbook/wiki/Compatibility 

Some questions

Q1 The section "Item property changes" mentioned about import. When do I need to use the import/export button of scrapbook x? In scrapbook x after I have selected the data directory (data saved when i was using scrapbook addon) of the old scrapbook, I could see all scrapbook saved data when I use scrapbook x already.

Q2 What does preferences mean? I don't see any "preferences" button? Is it scrapbook options?

The section "Configs" says "ScrapBook X has moved the preferences to extensions.scrapbook.*, and do not use them in common with the old revisions. To find the previous settings, type aboug:config in the address bar, and you can copy the values of scrapbook.* to the corresponding extensions.scrapbook.* manually."

**Comment by danny0838** [comment]
1. ScrapBook X can basically read all information saved by ScrapBook. However, ScrapBook data does not have some information, such as the last modified time of a data item, and will cause an unexpected result is some cases, such as when you search for "modify:". If you export and then import with the "Import as latest ScrapBook X format" checked, ScrapBook X will automatically generate the field (to be same as the ID currently). It is quite minor though, and you can choose to simply ignore it if you don't really care about it.

2. The preference means the entries in the about:config, which is the background saving mechanism for configs, such as ScrapBook options and "Save As" settings, etc.

**Comment by wonderkid** [comment]
What does "ScrapBook X will automatically generate the field (to be same as the ID currently)" mean?  What is "field" and "ID"? What is "search for "modify:""?

Does export/import affect anything when I am using the search bar in scrapbook x?

How to do an export/import? Is there a guide somewhere? 

I am assuming an export should be done in the old scrapbook and an import is done in the new scrapbook x correct?

Thanks

**Comment by danny0838** [comment]
A "field" means a property of an item, and can be viewed via the properties popup via the context menu of an item in the ScrapBook sidebar or in the Manage window like this: 

![default](https://cloud.githubusercontent.com/assets/531417/23415364/f174d96a-fe19-11e6-8ea1-62858cc87202.png)

I am crazy busy recently and cannot explain in full depth. Refer to our [wiki](https://github.com/danny0838/firefox-scrapbook/wiki/Features) for more details.

**Comment by danny0838** [comment]
Close stale issue since no further discussion for over half year.
