### ISSUE TITLE
How to change location of save data?

### ISSUE THREAD

**Issue by wonderkid** [danny0838/firefox-scrapbook#192]
In firefox scrapbook options>organize, I can change the location of scrapbook https://i.imgur.com/wFHqYQY.png

In palemoon scrapbook x options>organize, I cannot change the location of scrapbook x https://i.imgur.com/hnu1H4y.png

How to change the directory of scrapbook x?

I have been using firefox scrapbook for a very long time and I save the data to a specific directory, if I am unable to change the directory of save data location of scrapbook x, I am unable to use my old scrapbook data. I do not want to save data to default scrapbook location.

Thanks

**Comment by danny0838** [comment]
Use the multi-ScrapBook feature. See https://github.com/danny0838/firefox-scrapbook/issues/140 for detail.

**Comment by wonderkid** [comment]
Hi Danny,

Q1 Would there be any problem if I open both firefox scrapbook x and palemoon scrapbook x and use (add/delete data) both scrapbook at the same time? (both scrapbook data are saved to the same location)

Q2 Would there be any problem if I open both firefox scrapbook and palemoon scrapbook x and use (add/delete data) both scrapbook at the same time? (both scrapbook data are saved to the same location)

Thanks

**Comment by danny0838** [comment]
Yes. It's just like editing a text file in two different applications. Say if you open Firefox A and Firefox B, and then do a change in Firefox A, the change is saved to the database. However, Firefox B does not know that the database has been changed, and if you then do a change in Firefox B, it is saved and overwrites the previous work in Firefox A, causing it permanently lost.

**Comment by wonderkid** [comment]
I was using Scrapbook in Firefox last time and I have just uninstalled Scrapbook and installed Scrapbook X, now only using Scrapbook X in Firefox.

After installing Scrapbook X, I see the default scrapbook location is
C:\Users\Owner\AppData\Roaming\Mozilla\Firefox\Profiles\5t5b946g.default\ScrapBook

I was wondering if that folder is created by Scrapbook or Scrapbook X since it seems like the same name and location as Scrapbook.

Question:
A) After I uninstalled Scrapbook, is the Scrapbook default location auto deleted? 

B) Is the default Scrapbook X location the same location as the default Scrapbook location?

C) Does Scrapbook X create new profile/new folders/files? Is C:\Users\Owner\AppData\Roaming\Mozilla\Firefox\Profiles\5t5b946g.default\ScrapBook created by Scrapbook or Scrapbook X? Is 5t5b946g.default\ScrapBook created by Scrapbook X?

Thanks

**Comment by danny0838** [comment]
The `C:\Users\Owner\AppData\Roaming\Mozilla\Firefox\Profiles\5t5b946g.default` you mentioned is the Profile directory of Firefox, which is automatically generated by Firefox, and if could be different if you config Firefox in another way.

ScrapBook generates a subdirectory `ScrapBook` in the Profile directory, it is not automatically deleted when you unstall ScrapBook. For downward compatibility, ScrapBook X uses the same path as ScrapBook.

**Comment by sevecose** [comment]
> In firefox scrapbook options>organize, I can change the location of scrapbook https://i.imgur.com/wFHqYQY.png
> 
> In palemoon scrapbook x options>organize, I cannot change the location of scrapbook x https://i.imgur.com/hnu1H4y.png
> 
> How to change the directory of scrapbook x?
> 
> I have been using firefox scrapbook for a very long time and I save the data to a specific directory, if I am unable to change the directory of save data location of scrapbook x, I am unable to use my old scrapbook data. I do not want to save data to default scrapbook location.
> 
> Thanks

**Comment by sevecose** [comment]
> In firefox scrapbook options>organize, I can change the location of scrapbook https://i.imgur.com/wFHqYQY.png
> 
> In palemoon scrapbook x options>organize, I cannot change the location of scrapbook x https://i.imgur.com/hnu1H4y.png
> 
> How to change the directory of scrapbook x?
> 
> I have been using firefox scrapbook for a very long time and I save the data to a specific directory, if I am unable to change the directory of save data location of scrapbook x, I am unable to use my old scrapbook data. I do not want to save data to default scrapbook location.
> 
> Thanks

Waterfox + Scrapbook X 1.14.7 nothing also allows. I want to move Scrapbook X data to another drive (100GB from the system disk) but nowhere is it possible to select a directory. Great! Otherwise a great thing, that's why I have waterfox! Thanks!
