### ISSUE TITLE
disabling third party coockies breaks saving some sites.

### ISSUE THREAD

**Issue by rezad1393** [danny0838/firefox-scrapbook#193]
when I use "Allow cookies from originating server only" setting in firefox, I get problems with this website that needs login access for reading stories .
[http://storiesonline.net](url)

 steps to reproduce.
1.create a fresh firefox profile.
2.install scrapbook x addon
3.in firefox preferences "Allow cookies from originating server only". or if not found, use the about:config page of firefox and set this  network.cookie.cookieBehavior from 0 to 1 
4.login into that website (or maybe another website like that which needs login access for accessing some part of the website.
5.save a multipage story via "save as" in scrapbook and use the depth more that 0 to get all the chapters from that story. like this one [http://storiesonline.net/s/54088/](url)

expected result: saving should work correctly like you are visiting pages yourself.

actual result: after first page(homepage of story) other pages give 401 http error (not authorized) .
the first page and the homepage are accessible with no login so they also may be affected.

"Enable all cookies (default)" removes this issue but make firefox way less secure.

**Comment by danny0838** [comment]
It's an issue of Firefox core. We cannot fix this issue unless Firefox made some change to related addon APIs.

**Comment by MisterAlanBradley** [comment]
I have a bit different problem. When saving a page while beeing logged in at the site I get logged out right after the save. Changing the cookie preferences doesnt help. Problem exists with the lates beta version.

**Comment by danny0838** [comment]
Close this issue since it's causes by Firefox core. @MisterAlanBradley 's issue is another issue and we won't discuss it here. It may be related with #251. Please check if download linked files is set, and reply in issue #251 or raise another issue.
