### ISSUE TITLE
Weird square characters in folder name info

### ISSUE THREAD

**Issue by wonderkid** [danny0838/firefox-scrapbook#194]
Hi,

I right click on a scrapbooked page and select 'properties'. In the properties pop up box, I see 00IR characters inside a square in 'folder' name info. see screenshot https://i.imgur.com/qm42XgB.png

Is there anything wrong? How to solve the problem?

Thanks

**Comment by danny0838** [comment]
It's normal. They are used to demark the bondary of the folder name, and we currently cannot find a better char for it (space or tab can be used in the item title and cannot be a good bondary demarking char).

**Comment by Hub-O-Gits** [comment]
Is that an escape char? It would help if there was a space on either side.
How about a backslash, pipe, or one of these:

unicode | example
------------ | -------------
U+00BB | Dir 1 » Dir 2 » Dir 3
U+25AA | Dir 1 ▪ Dir 2 ▪ Dir 3

**Comment by danny0838** [comment]
These chars may present in a normal title and cause a confusion. We need a separator char that won't present in a normal title.

**Comment by danny0838** [comment]
Close this issue since we basically won't make a change about this. If you have further information it's welcomed to leave a reply.
