### ISSUE TITLE
动态演示图片未保存好

### ISSUE THREAD

**Issue by pczbq806** [danny0838/firefox-scrapbook#195]
“保存所选内容”时，以下 URL 中的以下 HTML 内容未保存好，图片位置偏移。

URL: https://thaimilitaryandasianregion.wordpress.com/2016/12/13/vbci-nexter-wheeled-armoured-infantry-fighting-vehicle/

HTML: ‘<div id="gallery-110823-1-slideshow" class="slideshow-window jetpack-slideshow slideshow-black" data-trans="fade" data-autostart="1" data-gallery="[{&quot;src&quot;:&quot;https:\/\/thaimilitaryandasianregion.files.wordpress.com\/2016\/12\/vbci_05_of_80.jpg&quot;,&quot;id&quot;:&quot;111660&quot;,&quot;title&quot;:&quot;vbci_05_of_80&quot;,&quot;alt&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;},{&quot;src&quot;:&quot;https:\/\/thaimilitaryandasianregion.files.wordpress.com\/2016\/12\/vbci_16_of_80.jpg&quot;,&quot;id&quot;:&quot;111657&quot;,&quot;title&quot;:&quot;vbci_16_of_80&quot;,&quot;alt&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;},{&quot;src&quot;:&quot;https:\/\/thaimilitaryandasianregion.files.wordpress.com\/2016\/12\/vbci_20_of_80.jpg&quot;,&quot;id&quot;:&quot;111656&quot;,&quot;title&quot;:&quot;vbci_20_of_80&quot;,&quot;alt&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;},{&quot;src&quot;:&quot;https:\/\/thaimilitaryandasianregion.files.wordpress.com\/2016\/12\/vbci_32ton_dsc00435_800.jpg&quot;,&quot;id&quot;:&quot;111661&quot;,&quot;title&quot;:&quot;vbci_32ton_dsc00435_800&quot;,&quot;alt&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;}]"><div style="position: absolute; top: 0px; left: 0px; z-index: 5; opacity: 1; display: block; width: 546px; height: 360px;" class="slideshow-slide"><img alt="" title="vbci_05_of_80" src="https://thaimilitaryandasianregion.files.wordpress.com/2016/12/vbci_05_of_80.jpg" align="middle"><span class="slideshow-line-height-hack">&nbsp;</span><div class="slideshow-slide-caption"></div></div><div style="position: absolute; top: 0px; left: 0px; display: none; z-index: 4; opacity: 0; width: 546px; height: 360px;" class="slideshow-slide"><img alt="" title="vbci_16_of_80" src="https://thaimilitaryandasianregion.files.wordpress.com/2016/12/vbci_16_of_80.jpg" align="middle"><span class="slideshow-line-height-hack">&nbsp;</span><div class="slideshow-slide-caption"></div></div><div style="position: absolute; top: 0px; left: 0px; display: none; z-index: 4; opacity: 0; width: 546px; height: 360px;" class="slideshow-slide"><img alt="" title="vbci_20_of_80" src="https://thaimilitaryandasianregion.files.wordpress.com/2016/12/vbci_20_of_80.jpg" align="middle"><span class="slideshow-line-height-hack">&nbsp;</span><div class="slideshow-slide-caption"></div></div><div style="position: absolute; top: 0px; left: 0px; display: none; z-index: 4; opacity: 0; width: 546px; height: 360px;" class="slideshow-slide"><img alt="" title="vbci_32ton_dsc00435_800" src="https://thaimilitaryandasianregion.files.wordpress.com/2016/12/vbci_32ton_dsc00435_800.jpg" align="middle"><span class="slideshow-line-height-hack">&nbsp;</span><div class="slideshow-slide-caption"></div></div><div class="slideshow-controls"><a href="#"></a><a href="#"></a><a href="#"></a></div></div>’

**Comment by danny0838** [comment]
儲存整個網頁就沒有異常，這表示這不是 ScrapBook X 的問題，而是因為此網頁用到的某些 CSS 與 HTML 的 DOM 高度相關，因此在刪除部分元素以後就不能像原先一樣正常顯示。遇到這種情況只能退而求其次用「編輯後儲存」手動去除不要的元素並即時檢視是否會導致整個排版異常，然後在沒有異常的情況下儲存網頁。

**Comment by pczbq806** [comment]
明白了，谢谢！
