### ISSUE TITLE
Need a search at the folder level

### ISSUE THREAD

**Issue by CityguyUSA** [danny0838/firefox-scrapbook#196]
Seems like it's self explanatory.  I don't kow how many folders I have but it's more than I want to search for an article that I know resides in a specific folder.  Can you add a search to the context menu of a folder?

**Comment by danny0838** [comment]
Due to some fundamental structure issues, we are not going to implement direct folder search. A workaround is to use a non-folder type folder, for example, create a note page, right click on it and convert it to a folder, so that you can search the note page via its title, content, etc.

**Comment by CityguyUSA** [comment]
Makes absolutely no sense to me.  If my goal is to search all pages saved within a folder how does saving a page as a note and converting that note to a folder solve anything?

**Comment by danny0838** [comment]
Maybe I misunderstood your proposal. If you want to search pages in a specific folder, you can right click on the folder and select "Manage", and then search in the prompted dialog window.

**Comment by CityguyUSA** [comment]
I tried that it seems that it searches through all folders.

**Comment by danny0838** [comment]
This should not happen. Could you provide some screenshots for how you actually operate?

**Comment by CityguyUSA** [comment]
I cant explain but why but it worked differently today.  The other day I had the manage window and a separate window that was showing the each directory as it was being searched.  Last night I had a new tab open with only the folder I selected to search.  Appears to work
