### ISSUE TITLE
儲存後自動載入目前分頁

### ISSUE THREAD

**Issue by Jason19900812** [danny0838/firefox-scrapbook#199]
作者您好，真的很感謝您做出這麼棒的附加元件。想請問有什麼方法可以在擷取網頁之後，自動在目前分頁載入儲存後的HTML檔做後續編輯(劃重點之類的)。當然我可以按那個擷取完成的通知，只是有些網頁擷取需要時間等待，想請教有沒有自動一點的方式。

**Comment by danny0838** [comment]
目前沒有實做這種功能的計畫。如果習慣先晝完重點再儲存，可考慮用「編輯後儲存」。
