### ISSUE TITLE
Search of Scrapbook has broken in Firefox 54

### ISSUE THREAD

**Issue by yfdyh000** [danny0838/firefox-scrapbook#203]
TypeError: Components.classes['@mozilla.org/satchel/form-history;1'] is undefined  scrapbook.js:559:9

https://bugzilla.mozilla.org/show_bug.cgi?id=876002

**Comment by duzers** [comment]
I confirm. There is a problem with search in Firefox 54 beta 1.

**Comment by danny0838** [comment]
解決這問題有兩個方法，一個是把相關 UI 改成像傳統 ScrapBook 1.4.* 一樣，但將會無法記錄曾經搜尋過的關鍵字詞。另一個方法是轉移到新的 API，不過目前似乎看不到相關的文件（Mozilla 最近對開發者越來越不友善，刪除 API 也沒有在 MDN 上提供相關警示及連結至可用的替代 API），我已經發文詢問了，可能要再等等。

**Comment by danny0838** [comment]
Fixed in Scrapbook X 1.14.0rc9.
