### ISSUE TITLE
Preferences not displayed completely (i.e. cut off) on macOS

### ISSUE THREAD

**Issue by gnl** [danny0838/firefox-scrapbook#208]
...and there doesn't seem to be a way to scroll or resize the window. Firefox version is 52.0.2.

For example:

<img width="632" alt="screen shot 2017-04-09 at 02 09 40" src="https://cloud.githubusercontent.com/assets/1690961/24833181/bca26d1e-1cc9-11e7-81d7-c82e13f1f101.png">

Seems to apply to the "Keys" tab as well:

<img width="632" alt="screen shot 2017-04-09 at 02 08 57" src="https://cloud.githubusercontent.com/assets/1690961/24833184/c8a819ba-1cc9-11e7-8fda-06e8fe15de5f.png">

P.S. Thank you for Scrapbook X

**Comment by danny0838** [comment]
This is an old issue (see #122). It seems to be some inconsistent display effect of XUL between different OS. There is no available document for such related XUL issue on MDN, and we can only fix this by trial and error. Unfortunately I am not a Mac user and I don't have an available Mac for testing, so this issue could be pending until some Mac users could actively help such debugging.

**Comment by danny0838** [comment]
Close stale duplicated issue.
