### ISSUE TITLE
How to Save Images from the Gallery for eBay's Listings?

### ISSUE THREAD

**Issue by roseuz** [danny0838/firefox-scrapbook#210]
I absolutely love this program. Finally I can have my eBay listings saved correctly. Whenever I would save any eBay listing with Scrapbook, the description portion would end up being saved in a tiny embedded window to the right of the page. I would then have to open the description portion of the listing from the original page and save that in order to have a saved copy of the description.  It is for this reason why I went in search of a new addon, and finally, thanks to this addon, I don't have to save pages twice.

Now, there is still one thing I can't yet do with this program, and I am hoping it's just a combination of settings that I need to implement, and if not, that there will be a solution offered in a future update.

That one thing that I still can't do is save full size images for all images from the embedded gallery. If you take a look at this listing (which is not mine and I have no affiliation with the seller): http://www.ebay.com/itm/DZ09-Bluetooth-Smart-Watch-Phone-Camera-SIM-Card-For-Android-IOS-Phones-/361664992138?_trkparms=5373%3A0%7C5374%3AFeatured , if you click on any of the thumbnails on the top left of the page for the gallery, then click on the larger image shown above, and then right click on the image and choose View Image (in Firefox), you will see a larger image / the true size of the image. You will notice that the first two are 1600 x 1600 pixels images.

How can I save all these images at their true / full size, preferably in one step, and preferably at the same time I am saving the listing?

**Comment by danny0838** [comment]
The enlargement is done by JavaScript, and we cannot do more. A per-site spider software is required for such cases.
