### ISSUE TITLE
Pages already saved. How to check?

### ISSUE THREAD

**Issue by SergeGardien** [danny0838/firefox-scrapbook#212]
In the page [https://github.com/danny0838/firefox-scrapbook/wiki/Diffs](https://github.com/danny0838/firefox-scrapbook/wiki/Diffs) I read there is an option that says "Show notification on browsing a page having been saved".

Problem is I cannot find it in the option menu of ScrapBook X.

Can you please confirm this option is still alive?

Moreover, is there a possibility to have a marker (similar to the blue star for Firefox Bookmarks) in case a webpage is already saved? For me would be very useful.

**Comment by danny0838** [comment]
Here is the option:
![default](https://cloud.githubusercontent.com/assets/531417/25310991/3a64c5dc-2826-11e7-84d8-8d1bc09578a0.png)

And you'll see such notification when you visit such page (on v1.14.*, or a notification dialog on v1.13.*):
![default](https://cloud.githubusercontent.com/assets/531417/25311007/c44ea25e-2826-11e7-830f-24edf0e86cdb.png)

**Comment by SergeGardien** [comment]
Thanks.
On my Firefox the option window was collapsed so I had to enlarge it to see this option:
![screenshot](https://cloud.githubusercontent.com/assets/21199594/25312068/c72bc766-280f-11e7-8374-9a1e21f55160.png)
...and enlarged:
![screen shot 2017-04-23 at 10 30 28](https://cloud.githubusercontent.com/assets/21199594/25312070/e8498d48-280f-11e7-83bf-fd02f06b70aa.png)

**Comment by danny0838** [comment]
On Windows there is a scrollbar if not fully shown. It seems to be the issue as #122.
