### ISSUE TITLE
能否加入一项“使用最近保存的文件夹”的选项

### ISSUE THREAD

**Issue by pczbq806** [danny0838/firefox-scrapbook#215]
能否在保存页面内容时弹出的“保存选项”里加入“使用最近保存的文件夹”的选项：
![](https://cloud.githubusercontent.com/assets/26035751/25833958/74e88314-34a7-11e7-88d0-9c6894be210d.jpg)
类似于百度网盘这样的：
![](https://cloud.githubusercontent.com/assets/26035751/25833972/8b57385c-34a7-11e7-84d9-112e0aa6ac9c.jpg)

**Comment by danny0838** [comment]
現在已經有這個功能，在選擇文件夾時「根文件夾」以上會顯示幾個最近選擇過的文件夾。如圖：

![default](https://cloud.githubusercontent.com/assets/531417/26136627/c0fc508e-3aef-11e7-8947-48f4de9b84fd.png)

**Comment by pczbq806** [comment]
明白了。
