### ISSUE TITLE
saving multiple file

### ISSUE THREAD

**Issue by afifosh** [danny0838/firefox-scrapbook#216]
the issue once i put depth to 1 it will extract all others link after that he go to capture each link
everything till now is working fine , the issue with the save pages ,, the content of the page after you open it normally on any tab it will go throw many stage to open the desired page 

how we can sort it out ?

**Comment by danny0838** [comment]
What do you mean by saying "it will go throw many stage to open the desired page"? Could you provide a more detailed explanation?

Which page do you have this issue?
