### ISSUE TITLE
每次都抓漏頁面 可否手動修補?

### ISSUE THREAD

**Issue by birdoffire** [danny0838/firefox-scrapbook#218]
重抓幾次之後,終於在不同的資料夾收集齊全部頁面,請問如何把他們合而為一呢?主要是修改連結

**Comment by danny0838** [comment]
目前不支援此功能，請使用深入儲存的方式儲存互相連結的多個頁面

**Comment by birdoffire** [comment]
已經使用深入儲存,可能是BUG吧,原版SCRAPBBOK的抓失率接近60%,換了X之後大約10%
我已用HTML編輯器手動更改成本地連結了
