### ISSUE TITLE
In FF v53.0+ META Refresh for saved image files fails to work

### ISSUE THREAD

**Issue by jdunn0** [danny0838/firefox-scrapbook#219]
When a non-HTML file is saved using ScrapBook X, an index.html file is created with the contents:
`<html><head><meta charset="UTF-8"><meta http-equiv="refresh" content="0;URL=filename.ext"></head><body></body></html>`
I recently found that when this no longer appears to work in FF v53.0+ for image files as when the index.html file is loaded, instead of redirecting to the image file, it just shows a blank page.
I have two computer with FF v53.0 or higher with ScrapBook X that have this problem.

**Comment by danny0838** [comment]
I also met this issue for times. Sometimes opening the item in a new tab will work. It seems to be an issue of Firefox core, and currently we cannot fix it.

**Comment by jdunn0** [comment]
I'm not sure how possible it is to implement but it seems the best way to deal with this would be to add a filename field to the index.dat file so that when a file entry is selected in ScrapBook X, it knows the file name so the image can be loaded without the use of a index.html file.
This would have the benefit of a small speed boost by loading the file directly and allow features like the "Open in Default Program" option to get the file name easier.

**Comment by danny0838** [comment]
@jdunn0 We already have the function. Right click on an item and select "Open in Default Program". This is not the default behavior because it's assumed that the user would prefer to view a file in the browser whenever possible.

**Comment by jdunn0** [comment]
I guess my comment wasn't clear.
I was saying that if each entry had a file name field in addition to the name, comment, date, etc. that ScrapBook X would have the file name available when an entry is selected so that it can tell directly tell Firefox to open image.jpg for example instead of loading index.html that then redirects to image.jpg
I figured this metadata would help with the "Open in Default Program" function too as I assume that function needs to look in the index.html file to get the actual file name to open.

It's kind of a clucky hack that an index.html file is generated and used to redirect to the actual file with a file is saved.
I'm guessing the reason this is still done is to maintain compatibility as all versions before a change would only expect an index.html and not know about the file name metadata.

**Comment by danny0838** [comment]
We are not going to change this since there's too many potential compatibility issues.
