### ISSUE TITLE
Unable to use New Note Page

### ISSUE THREAD

**Issue by roseuz** [danny0838/firefox-scrapbook#220]
I am unable to use the New Note page. I believe I was able to use this once sometime in the past.

When I click on "New Note Page", a new note page is created with the words "New Note Page" as the title of the page and is also shown on the right / on the page itself.

How do I go about adding notes to this page?

**Comment by danny0838** [comment]
You should be able to edit a note page. If not, check whether the HTML edit mode is activated in the editor toolbar.
![screen-2017-06-06_19-13-59](https://cloud.githubusercontent.com/assets/531417/26826669/77f62f38-4aec-11e7-99f3-a4ddf2fb3c33.jpg)

**Comment by danny0838** [comment]
Close stale issue since no further discussion over half year. If you have further information it's welcomed to leave a reply.
