### ISSUE TITLE
[WORKAROUND] How to transfer bookmarks from Scrapbook to Firefox?

### ISSUE THREAD

**Issue by sergeevabc** [danny0838/firefox-scrapbook#221]
As we click “Export”, chosen folder is populated with entities, but they seem to use Scrapbook format.
However Firefox is able to import ```bookmarks.html``` only, so what’s the best way to get one?

**Comment by danny0838** [comment]
Firefox bookmark only support storing page information such as URL, name, keywords, tag, etc, while pages saved by ScrapBook are full copy, and therefore ScrapBook data cannot be imported into Firefox bookmark.

**Comment by sergeevabc** [comment]
Scrapbook has two ways to save pages: either as full copy or as bookmark.
I never saved full copies, just bookmarked them into categories via Scrapbook context menu.
Now I see that this is no different from FF’s native bookmarks, which I’d like to convert them into.

**Comment by danny0838** [comment]
Ok. I understand. But we are still not going to develop such conversion, since it's a very specific and restricted use case.

Since all bookmarks are records in the scrapbook.rdf file. One way you can do this is to write a script to parse it and convert to the format that native Firefox bookmark use.

**Comment by sergeevabc** [comment]
Since Scrapbook is kinda replacement for browser’s bookmarks, I believe it should be equally easy to board the ship (_import)_ and leave it (_export_) if travel plans are changed. This approach is practiced by [Delicious][1] and [Diigo][2] to name a few. Well done! Here I, being a mere user, feel locked in the hold.

[1]: https://youtu.be/9wwufHbPNbQ?t=56s
[2]: https://youtu.be/lNuMfsRXuec?t=25s

**Comment by sergeevabc** [comment]
Scrapbook’s “Output tree as HTML” already creates HTML with all its bookmarks, yet they are not properly formatted to be imported into Firefox right away.

**Comment by sergeevabc** [comment]
Workaround: “Output tree as HTML” already creates HTML with Scrapbook bookmarks, yet they are not properly formatted to be imported into Firefox right away. Now [Multi Link Plus][3] addon comes into play: we open generated HTML, expand folders/categories one by one, then right click and drag a box around links, then choose to add them to bookmarks, voila. Conversion is not fully automatic, but intuitive. 

[3]: https://addons.mozilla.org/en-US/firefox/addon/multi-links-plus

**Comment by pviotti** [comment]
In case anybody needs this, here is what I did.

for each complete web page I created a pdf using `wkhtmltopdf` 
```bash
for dir in $(ls):                                                                                         
do                                   
   wkhtmltopdf $dir/index.html $dir/index.pdf;
done
```

for the links: 
 - installed Pale Moon browser to be able to use Scrapbook 
 - export all using `Import / Export' from Scrapbook menu
 - converted to the Mozilla bookmark HTML format with this script
```bash
#!/bin/bash

SAVEIFS=$IFS
IFS=$(echo -en "\n\b")
for f in */
do
  url=$(grep source "$f"/index.dat | cut -f2 | grep -e "^http")
  if [ -n "$url" ]
  then
    title=$(grep title "$f"/index.dat | cut -f2)
    folder=$(grep folder "$f"/index.dat | cut -f2- | sed 's/\t/,/g')
  
    echo -e "<DT><A HREF=\"$url\" ADD_DATE=\"1511123805\" LAST_MODIFIED=\"1511123805\" LAST_CHARSET=\"UTF-8\" TAGS=\"$folder\">$title</A>\\n<DD>" >> bookmarks.html
  fi
done
IFS=$SAVEIFS
```
In alternative, one can directly parse the rdf file in the Scrapbook folder without installing Pale Moon.
