### ISSUE TITLE
Doesn't work properly with JS, while the original addon works fine.

### ISSUE THREAD

**Issue by JulyMorning** [danny0838/firefox-scrapbook#222]
Wanted to download the book (needs registration):

— https://www.safaribooksonline.com/library/view/make-getting-started/9781457186769/

Scrapbook X was downloading the pages with the message «needs js to display properly» and so on, but the original one, the «Scrapbook» did the job right.

**Comment by marcos1500** [comment]
hey dude , so if u use Scrapbook normal version, try to use this config, worked correctly with me.
![boxarea0000](https://user-images.githubusercontent.com/24254685/27046227-faae352e-4f79-11e7-9a0a-0ce04517f69e.png)

**Comment by marcos1500** [comment]
sorry but my screenshot was portuguese br

**Comment by marcos1500** [comment]
see below 
![croparea0000](https://user-images.githubusercontent.com/24254685/27046462-e63cc3ca-4f7a-11e7-9671-c59106b46849.png)

**Comment by JulyMorning** [comment]
That's the thing: I've get it done with normal version, but this report was intended for «Scrapbook X». Don't know why, but all its settings fail. Thanks for your response however.

**Comment by danny0838** [comment]
I did a quick check and failed to see a clear problem. Could you provide a few screenshots illustrating the issue?

**Comment by JulyMorning** [comment]
I can tell you about the settings I was trying to use. I've tried to check all the checkboxes (with and without JavaScript), the filter I've used was «/library/» or «/view/» or the name of the book. I don't know, I've tried almost everything, but the pages of the book were saying that they need js to display properly – like I've turned it off. I also use «NoScript», but I've made it allow everything. It just didn't work. Then I bethinked about the other version that worked for me with this site previously. I've installed it and everything became fine, with the same settings (with the depth of 1, js on etc + filters, etc). I don't want to reinstall it just to make a sreenshot, but if you need something besides, please tell me.

**Comment by danny0838** [comment]
I don't have an account to test the site. Please provide a few screenshots illustrating the difference between the page saved by ScroopBook X and the one saved by legacy ScrapBook. You can mask or mosaic unrelated areas if there is a concern.
