### ISSUE TITLE
unresponsive script / corrupting GUI of other addons

### ISSUE THREAD

**Issue by rkoe** [danny0838/firefox-scrapbook#223]
ScrapBook X causes "Unresponsive script"-warnings and when stopping the script, corrupts the GUIs of the uMatrix-addon.

Details:
- When I try to capture "http://api.libreoffice.org/docs/idl/ref/annotated.html" with Scrapbook X, Firefox freezes for some seconds, and afterwards the warning "Unresponsive script" about "Script: chrome://scrapbook/content/saver.js" appears. (The line-number of the warning varies, e.g. 936, 937, 1274, ...)
- Clicking "Continue" does not help -- after some time, the same warning appears again.
- Clicking "Debug script" results in an empty debug-pane.
- Clicking "Stop script" stops it, but afterwards the uMatrix-addon-window is corrupted, and I have to restart Firefox to solve this.
- Attachments:
  - Screenshot of the website and the warning.
  - Screenshot of the corrupted uMatrix GUI (right side is cutted away).

Used versions:
- ScrapBook version: ScrapBook X 1.13.11
- Browser: Firefox ESR 52.2.0 (64-bit)
- OS: Linux (Debian Jessie)

![scrapbook-api libreoffice 1](https://user-images.githubusercontent.com/2507744/27220612-14a30662-5286-11e7-87b9-290887841c35.png)
![scrapbook-api libreoffice 2](https://user-images.githubusercontent.com/2507744/27220618-1727f154-5286-11e7-844d-5fea6617cdaf.png)

**Comment by danny0838** [comment]
Although the web page doesn't seem big, it has a lot of hidden elements and it's actual size is near 3MB. There is nothing wrong for ScrapBook X, it just need much time to save the page, and Firefox core simply jumps the alert if the script takes a long time. Just keep pressing "Continue" (or check "Don't ask me again"), and the page will eventually be saved correctly.

**Comment by rkoe** [comment]
Oh, ok. It did work -- after 33 minutes of 100% CPU load (!).

So, there is definitely something wrong, when parsing+saving such a webpage needs over half an hour of full CPU-load (while you can't do anything else with Firefox). But I don't know if there is something wrong with Scrapbook itself or if there's something wrong with Firefox and its (terrible) addon-performance...

(By the way: Thanks **very much** for ScrapBook and for your quick responses. ScrapBook is the most important addon and the most important "Firefox-feature" for me =)).)

**Comment by danny0838** [comment]
On my computer it only took < 1 minutes. I think the performance highly depends on the client. Technically it may be possible to make the browser more responsive during the saving process, but it probably would increase the total saving time.

**Comment by rkoe** [comment]
Hmm, that's weird. What's your client?
(I used Firefox ESR 52.2.0 on Linux on a quite fast PC (i3-4160T).)

**Comment by danny0838** [comment]
I use Windows 7 SP1. We are closing this issue since it doesn't seem to be something we can fix. If you have further information you're welcome to leave a comment here, and we'll consider if a further investigation is required.
