### ISSUE TITLE
Duplicate folders when importing from Scrapbook Plus

### ISSUE THREAD

**Issue by Hub-O-Gits** [danny0838/firefox-scrapbook#225]
**Conditions:**
(1) When exporting from Scrapbook Plus, then importing to Scrapbook X, and (2) when there's a subfolder with more than one page, and (3) at least one of those pages has the same name as its folder:
Scrapbook X creates an additional folder as shown below:

![image](https://user-images.githubusercontent.com/29762558/27662775-f08e13fe-5c24-11e7-8e96-bbbff481ee72.png) ![image](https://user-images.githubusercontent.com/29762558/27662785-ff37ba0e-5c24-11e7-8be5-337828a90275.png)

**Environment:**
![image](https://user-images.githubusercontent.com/29762558/27663136-8a13babe-5c26-11e7-9037-5220602a7dc1.png)

**Comment by danny0838** [comment]
Fixed in the new release. Thank you for the report.
