### ISSUE TITLE
BUG: "Save Page" and "Save Page As" don't work with cbsnews.com 

### ISSUE THREAD

**Issue by xtraeme-xt** [danny0838/firefox-scrapbook#229]
The problem is exactly as described in the title. The bug is fairly simple to repro. 

1. Go to any page on [http://www.cbsnews.com/](http://www.cbsnews.com/)
2. Open the context menu and try "Save Page" or "Save Page As" 

**Results:**
The article doesn't save.

**Expected:**
The document should save locally.

**Notes:**
1. I have experimented with Pale Moon and Firefox. The problem has been around FF for at least four or five updates (probably back to 44).
2. "Save As Bookmark" works fine. However, I suspect the problem extends beyond cbsnews.com because right clicking on the bookmark and doing "Save Page" or "Save Page As" fails as well. I'll open up the XPI later and add more notes when I have time.
3. I have disabled all javascript in page to make sure that wasn't a problem (Tools → Web Developer → click the gear → select "disable javascript").

**Comment by danny0838** [comment]
This seems to be a bug of Firefox core. I [already filed it](https://bugzilla.mozilla.org/show_bug.cgi?id=1385552) for a further survey.

**Comment by danny0838** [comment]
Temporarily added some codes to fix this issue in [1.14.0rc11](https://github.com/danny0838/firefox-scrapbook/releases/tag/1.14.0rc11).
