### ISSUE TITLE
saving animations on animagraffs.com

### ISSUE THREAD

**Issue by tomjones4** [danny0838/firefox-scrapbook#230]
When I use ScrapBook X to save https://animagraffs.com/electric-car/, it does not save the animation, yet when I view the saved page while connected to the internet the animation is loaded. I've tried the

`###any file except for web pages`
`(?!$|html?|xht(ml)?|php|py|pl|aspx?|cgi|jsp)(.*)`

and has not worked. Is there is a way to save the animation?

**Comment by danny0838** [comment]
The anime in that web site is drawn in a canvas element via javascript. You can try checking "Scripts" in save options and it might work for some cases. However, since javascript is highly context dependent, they are not guaranteed to fully work correctly and have no side effect.

**Comment by tomjones4** [comment]
> You can try checking "Scripts" in save options and it might work for some cases.

Unfortunately, this does not work.

**Comment by danny0838** [comment]
As mentioned above, we are unable to rewrite the javascript if the original version just cannot work offline.
