### ISSUE TITLE
Capture instead of loadurI replaceit by addTAB

### ISSUE THREAD

**Issue by afifosh** [danny0838/firefox-scrapbook#232]
I have an issue with the following line ...  this.ELEMENT.loadURI(aURL, null, null);

so i get the url using : var url = this.ELEMENT.contentWindow.location.href; from capture.js
than i add the following code to open the url in new tab , because the loaduri didn't load the full page so my purpose is to open the link into new tab and save it than close the tab

var currentWindow = Components.classes["@mozilla.org/appshell/window-mediator;1"].getService(Components.interfaces.nsIWindowMediator).getMostRecentWindow("navigator:browser");
var url = this.ELEMENT.contentWindow.location.href;
var browser = currentWindow.gBrowser.getBrowserForTab(currentWindow.gBrowser.selectedTab = currentWindow.gBrowser.addTab(url));
browser.addEventListener("load", function onLoad() {
  browser.removeEventListener("load", onLoad, true);

  alert(browser.contentWindow);
}, true);

the issue the browser.contentWindow return [object CPOW [object Window]] and  sbCaptureTask._captureWindow(this.ELEMENT.contentWindow, false);

 "this.ELEMENT.contentWindow" return    Window  [object Window] 

can you help me on this please !!!!

**Comment by danny0838** [comment]
What are your OS, browser, and ScrapBook X versions? And on which page do you have this issue?

**Comment by danny0838** [comment]
Close stale issue without further feedback.
