### ISSUE TITLE
Javascript rewriting issue

### ISSUE THREAD

**Issue by rjhorn-agfa** [danny0838/firefox-scrapbook#233]
The javascript rewriting is leading to execution of "URL=https://find.minlib.net:443/iii/encore/resources/NoJavascriptPage.html" as part of initial page drawing.  This does not happen on the original page.

I've captured and attached an html copy of the scrapbook saved page, and the html page source from Firefox.  If I modify the http-equiv-"refresh" to something else, the Scrapbook page displays properly.  

This may be related to #212

[https:_find.minlib.net_iii_encore_record_C__Rb3567504__Sbillions__Orightresult__U__X7?lang=eng&suite=cobalt.html.gz](https://github.com/danny0838/firefox-scrapbook/files/1202482/https._find.minlib.net_iii_encore_record_C__Rb3567504__Sbillions__Orightresult__U__X7.lang.eng.suite.cobalt.html.gz)
[index.html.gz](https://github.com/danny0838/firefox-scrapbook/files/1202484/index.html.gz)

**Comment by danny0838** [comment]
We don't rewrite javascripts. Javascripts are just downloaded as original. Javascript is highly context dependent, and it's impossible to "rewrite" javascript to get it work in the off-line environment without a per-site basis. Some javascripts would work right offline just as the original page, but if the javascript just cannot work off-line as the original page, we cannot help more. You'd have to find (or write) a tool specific for that site.

**Comment by rjhorn-agfa** [comment]
I looked a little more carefully.  This is the main html file, not the Javascript contents that is different.  So I may have summarized it wrongly.  For some reason the HTML that I see when showing page source is different than the HTML that is captured by Scrapbook.

**Comment by danny0838** [comment]
ScrapBook X must do some essential HTML rewriting to make the page shown correctly in the offline environment. It might sometimes break javascript, but if we don't do the rewrite, even the HTML will work incorrectly besides javascript.

**Comment by rjhorn-agfa** [comment]
This issue is probably related to that rewriting then.  The files attached to the original issue show the difference.  

The most serious problem is that the script removal results in the references NoJavascriptPage being executed automatically.  Removing the  <noscript>... for it leaves the page poorly formatted but usable.

My impression is that the removal logic is removing too much, perhaps because the host software that generates the page is generating some confusing dynamic javascript.

**Comment by danny0838** [comment]
Unfortunately we cannot provide a further handling for dynamic JavaScript related pages if there is an issue no matter saving JavaScript or not. A per-site spider software is required for such cases.
