### ISSUE TITLE
fetch image from cache

### ISSUE THREAD

**Issue by bluelovers** [danny0838/firefox-scrapbook#234]
希望能增加嘗試從 cahce 中下載圖片的選項
因為某些網站會在擷取時觸發了防外鏈機制
導致圖片無法正常擷取

例如 blog.xuite.net

http://blog.xuite.net/s080076666/blog/300376252-ASUS+R9+270+++%E5%96%AE%E9%9B%99%E5%8D%A1+CF%E4%BA%A4%E7%81%AB+%E6%95%88%E7%9B%8A

**Comment by danny0838** [comment]
已於 [1.14.0rc11](https://github.com/danny0838/firefox-scrapbook/releases/tag/1.14.0rc11) 修復，不過重點不是快取而是 header referer。
