### ISSUE TITLE
Unable to save web page when image is checked in Firefox 56+

### ISSUE THREAD

**Issue by bluelovers** [danny0838/firefox-scrapbook#235]
這幾天開始出現
擷取後 > 跳出擷取完成

然後實際上沒有寫入清單內 
---
資料夾雖然成功建立 並且有寫入資料(除了 index.htm, index.dat 以外的檔案都有建立成功)
但是卻沒有寫入 index.htm, index.dat

**Comment by danny0838** [comment]
請問你使用的 OS, Firefox, ScrapBook X 版本？是否停用其他附加元件了？

發生在特定網頁嗎？或是任何網頁都有可能？

下次若再發生煩請也試試 Ctrl+Shift+J 打開控制台再擷取，並回報裡面顯示的錯誤訊息，如果有的話。

**Comment by bluelovers** [comment]
似乎是 這個插件導致的 https://github.com/mozilla/valence

firefox dev 56.0b3 x64
windows 10

**Comment by bluelovers** [comment]
更正 原因似乎與那個插件無關

在擷取時 勾選 圖片 就會產生 這個 BUG
沒有勾選圖片時 則可以正常擷取

log 內 除了一堆的 unsafe/forbidden CPOW usage 以外

只有這個看起來比較不一樣而已

```
Error: cross-process JS call failed  saver.js:609:39
	inspectNode chrome://scrapbook/content/saver.js:609:39
	saveDocumentInternal/< chrome://scrapbook/content/saver.js:486:13
	forEach self-hosted:269:13
	saveDocumentInternal chrome://scrapbook/content/saver.js:485:9
	captureWindow chrome://scrapbook/content/saver.js:218:23
	captureWindow chrome://scrapbook/content/saver.js:5:16
	_captureInternal chrome://scrapbook/content/tree.js:456:9
	onDrop chrome://scrapbook/content/tree.js:217:21
	onDrop chrome://scrapbook/content/tree.js:514:16
```

**Comment by bluelovers** [comment]
另外請問一下 有考慮打算把 不擷取圖片時 保留圖片網址的功能 改回來嗎?

**Comment by danny0838** [comment]
目前沒有。

不同議題以後請開新 issue 或在相關 issue 下留言哦，謝謝。

**Comment by danny0838** [comment]
最近在 Firefox 56.0 正式版、開全新 Profile 且使用預設設定值、只安裝 ScrapBook X 1.14.0 之下運作正常。

有可能是 Profile 的問題，或者之前 beta 版本有問題。你可以再試試看。

**Comment by JonasCz** [comment]
Not sure what is said in this issue, but, I just updated to ff 56, and now ScrapBookX is not working anymore.. I can save pages, it creates a folder + some files for them in the save directory (but seemingly missing the HTML files), but the saved page does not show in the list.

**Comment by danny0838** [comment]
@JonasCz What you said is exactly this issue. And what I said in [the comment above you](https://github.com/danny0838/firefox-scrapbook/issues/235#issuecomment-333272650) is that ScrapBook X seems to work normal in a standard Firefox 56.* with a new profile and only ScrapBook X 1.14.0 installed. It may be an issue of the profile (if which has come from < Firefox 56 or Firefox 56 beta).

Please try using a new profile and do not install addons other than ScrapBook X, and see if this issue still persists or not.

**Comment by JonasCz** [comment]
Ok, so I disabled all my other addons (trying to find possible conflict), scrapbook x works, then enabled other addons one by one, and.. ScrapBookX works !

Problem solved, for me at least.

 (If it's useful info, other addons I'm using are: Downthemall, Hide caption titlebar plus, HTTPS Everywhere, uBlock origin, and something called "Safe browsing version 4 (temporary addon)" which seems to have been installed automatically.)

**Comment by JonasCz** [comment]
Hmm.. So ScrapbookX doesn't actually work, though it works _sometimes_ when saving local files (e.g. when opening a file already saved by scrapbook, and then saving it again. This only worked with (already locally saved) GitHub pages though, others didn't work, and neither did actual online pages.

I'll try a new profile though, but would like to avoid having to redo everything (addons, settings, bookmarks, ..) in a new profile

**Comment by JonasCz** [comment]
It seems that unistalling scrapbookx, deleting it's data folder in the firefox profile folder, and then reinstalling seems to really have fixed it for me.

 Unfortunately on reimporting old data (using import / export), the problem comes back...

**Comment by bluelovers** [comment]
firefox 56.0.2 普通版

如果擷取圖片就會失敗

http://www.ihowandwhy.com/z/%E4%B8%8D%E5%90%AB%E8%8B%B1%E6%96%87%E5%AD%97%E6%AF%8D%E7%9A%84%E7%BC%96%E7%A8%8B%E8%AF%AD%E8%A8%80%E6%9C%89%E5%93%AA%E4%BA%9B%EF%BC%9F

**Comment by danny0838** [comment]
@bluelovers 我用 56.0.2 那個頁面擷取正常，應該不是 SBX 本身的問題。還是先檢查看看套件衝突及 Profile 重設吧。

**Comment by tanpau** [comment]
Same issue here on waterfox 56.0.1 (64bit) on linux (mint), workarounds (new profile, diabling/uninstalling other plugins,.. didnt work). Funny thing: on windows machine in work, FF56 stopped working this way, so I changed to waterfox 56 => scrapbook worked again. At home on linux-machine: FF 54 still working as always, installed waterfox 56 -> no chance to get it to work.
Visual indicator on both machines if scrapbook stops working: folders changed from yellow ones to a gray rectanguar style ...

**Comment by jdunn0** [comment]
I just started looking at this bug and due to the error that mentions "cross-process JS call", I thought this might be a compatibility issue with e10s (Multi Process Support) in Firefox 56 and Waterfox 56.

In Waterfox 56 you can easily disable e10s via the "Enable Multi-Process Waterfox" checkmark in Options.
I'm not sure how to do that on Firefox 56.

I decided to test this idea and found that with e10s enabled I encountered the same issue but with e10s disabled I had no problems saving a web page with ScrapBook X.

**Comment by tanpau** [comment]
thanks a lot, disabling multiprocess-support did the trick and scrapbook is working again without problem :)
Now with waterfox and working scrapbook the future looks bright again, scrapbook is really a gem!

**Comment by danny0838** [comment]
@jdunn0 Thank you for the information. ScrapBook X is not compatible with e10s and it is explictly declared in the install.rdf. Firefox should be able to automatically detect whether there's an addon that's incompatible with e10s and disable e10s. On my PC with Fx 56 e10s is disabled and this issue doesn't exist. For forks that has this issue on Firefox 56, please check whether e10s is enabled. If it is, it's probably a bug for Firefox.

**Comment by jccalhoun** [comment]
can confirm that disabling e10s on waterfox 56 makes scrapbook work again. Thanks to the people that were able to track down the issue!

**Comment by bluelovers** [comment]
but only index.html is fail
other css image is saved
so i think should be has way make it

**Comment by jdunn0** [comment]
@bluelovers You should check to see if e10s (Multi Process Support) is enabled.
You can do this by going to "about:support" and checking to see what it says under "Application Basics" in the "Multiprocess Windows" field.
I've only used the English version of Firefox/Waterfox so it's possible that the text to look for is different if you are using a non-English version.

If it's enabled then I can post how to disable e10s in Firefox 56 (the way to disable it can vary depending on what about:support shows) and ScrapBook X will work for you.

**Comment by tshu711** [comment]
>  I can post how to disable e10s in Firefox 56 (the way to disable it can vary depending on what about:support shows) and ScrapBook X will work for you.

That would be marvelous, jdunn0. My **about:support** display shows 
`Multiprocess Windows  2/2 (Enabled by default)`
and 
`Multi-process staged rollout	3.05`
