### ISSUE TITLE
[req] webext port

### ISSUE THREAD

**Issue by ianamk** [danny0838/firefox-scrapbook#237]
I tried searching for this request and I couldn't find it, as mozilla will kill old style addons with Firefox 57 I'd like to make a request (or a question) will (can) this great addon be ported to webext

**Comment by yfdyh000** [comment]
#85, #209.
https://github.com/danny0838/webscrapbook

**Comment by danny0838** [comment]
As @yfdyh000 has provided, the WebExtension port of ScrapBook X is available as [Web ScrapBook
](https://github.com/danny0838/webscrapbook). But currently it still has much limited functionalities compared to ScrapBook X.
