### ISSUE TITLE
Images are not saving/showing. Script issue.

### ISSUE THREAD

**Issue by JulyMorning** [danny0838/firefox-scrapbook#239]
Trying to save online course from edx dot org. Saving scripts is turned on. Scrapbook-X. Just for example:

https://courses.edx.org/courses/course-v1:Microsoft+DEV218x+1T2017/course/

_→ Resource Content: Building a Responsive Layout → «Using Style Guides to Set Up Your Base CSS» block._

«style-guides.png» is saved in the main folder, where all the htmls are stored.

Original link:

— https://d37djvu3ytnwxt.cloudfront.net/assets/courseware/v1/27087bc53eb5d700c8777aa1ed09a0c1/asset-v1:Microsoft+DEV218x+1T2017+type@asset+block/style-guides.png

Saved link to the image (scripts turned on via NoScript):

— file:///assets/courseware/v1/27087bc53eb5d700c8777aa1ed09a0c1/asset-v1:Microsoft+DEV218x+1T2017+type@asset+block/style-guides.png

Scripts are saved by scrapbook, but blocked by NoScript, the link:

— *here_is_my_private_path*/data/20170929213738/style-guides.png

The image is loaded, but the site is not functional. Of course, turning scripts off via scrapbook on the saving step will save not working content. Overall, trying to download the images fails – in the example above I've used the main page that already has some image, just to check what's wrong, so there's only «style-guides.png» file saved in the folder, speaking of the course-related imgs.

**Comment by danny0838** [comment]
I don't have access to the site. Could you provide a bit more screenshots illustrating what's going wrong about the saved page in contrast of the original site page?

I don't get you when you said "**The image is loaded**, but the site is not functional." and then "Overall, **trying to download the images fails**". Could you explain a bit more?

**Comment by danny0838** [comment]
Close stale issue without further response.
