### ISSUE TITLE
Pale Moon support?

### ISSUE THREAD

**Issue by Lootyhoof** [danny0838/firefox-scrapbook#240]
Hi there,

With the removal of XUL add-on support in Firefox 57, and removal of all XUL add-ons from AMO once ESR52 support ends, would you consider supporting [Pale Moon](https://www.palemoon.org/)?

Scrapbook X currently works in Pale Moon, but needs to add its GUID to install.rdf for full support:

````
        <em:targetApplication>
            <Description>
                <!-- Pale Moon -->
                <em:id>{8de7fcbb-c55c-4fbe-bfc5-fc555c87dbc4}</em:id>
                <em:minVersion>25.0</em:minVersion>
                <em:maxVersion>27.*</em:maxVersion>
            </Description>
        </em:targetApplication>
````
With this added, it would be eligible to be added to the [Pale Moon Add-ons Site](https://addons.palemoon.org), if you're interested. If you are, I can help get you [setup](https://developer.palemoon.org/Add-ons:Site/Submit). This site will keep XUL add-ons alive indefinitely, and also provides auto-update for Pale Moon users if there's an update.

Thanks!

**Comment by danny0838** [comment]
It would be nice.

Is there a documentation telling what is not supported in version < 25?

I'd be glad to, and actually I did try to, submit to Pale Moon before. But related documentation is little. The "How to submit" instruction page you provided is difficult to find. It told me that I should PM to the add-ons team, but I could hardly find which exact staff I should contact with. It asks the developer to provide many details, but there is not a template available. It does tell us how to submit an updated version...

**Comment by mseliger** [comment]
You can install Scrapbook X without changing the GUID in Pale Moon. I use it with Pale Moon the last two years and I haven't no significant problems with the extension and Pale Moon. But it would be nice, when it become a "native" Pale Moon extension.

**Comment by Lootyhoof** [comment]
Pale Moon used the same GUID as Firefox before v25, so 25 is the earliest developers can target. With regards to its capabilities, v25 and v26 are more-or-less Firefox 24, with our own patches for improved security and web compatibility. With Pale Moon 27, this is more-or-less Firefox 38 with our own patches, but using the front-end from Firefox 24-28.

I am a member of the add-ons team, and would be happy to help you get setup. Do you have an email address I can ping with some details? Sorry about the confusing wording of that page too, by the way.

Thanks!

**Comment by danny0838** [comment]
Thanks for @Lootyhoof 's help. ScrapBook X is now [available as Pale Moon Add-ons](https://addons.palemoon.org/extensions/download-management/).

**Comment by Lootyhoof** [comment]
Just to note that as a result of [Mozilla planning to remove XUL add-ons from AMO](https://blog.mozilla.org/addons/2017/10/03/legacy-add-on-support-on-firefox-esr/#comment-224377), we will be [removing AMO support](https://forum.palemoon.org/viewtopic.php?f=44&t=17829) from May 8, 2018 (2018-05-08). At this time any add-ons externally hosted on AMO will have their external link removed from our site, and will not receive auto-updates.

In order to workaround this it is advised to either host this directly on our add-ons site, or host it elsewhere (not AMO) so long as you have a correct `updateURL` in `install.rdf` and we could update the external link.

Please let me know ASAP how you would like to proceed.

Thanks!

**Comment by danny0838** [comment]
Hosting them in Pale Moon's site is fine.

**Comment by Lootyhoof** [comment]
Thanks, I'll get that arranged soon. Would you also like the ScrapBook X add-ons you also host on AMO to be hosted there (they must have the Pale Moon application block added to `install.rdf` though)? Would you like FTP access to be able to update these in future if necessary (I will send the details via email if so)?

**Comment by danny0838** [comment]
Yes and yes. I'll take care of this once Mozilla really removed all legacy addons from AMO.

**Comment by Lootyhoof** [comment]
Just to confirm that this is now live: https://addons.palemoon.org/addon/scrapbook-x/

I have sent you details in email.

Thanks!

**Comment by smnthermes** [comment]
The most recent version (1.14.7) isn't available at the Pale Moon Add-ons Site.

**Comment by Lootyhoof** [comment]
This would require @danny0838 to upload it: https://addons.palemoon.org/panel/

This panel allows for releasing both updates and new submissions. The login details would be the same as I'd previously sent, though I'd be happy to re-send if required. This supports both Pale Moon and Basilisk, too.

**Comment by danny0838** [comment]
@Lootyhoof I cannot access FTP using previous login information. I also tried the web panel, which asked for email verification after I logged in, but I never received an email afterwards (spam mails were checked and not found).

@smnthermes You can download the installation file from the [releases/tags](https://github.com/danny0838/firefox-scrapbook/releases/tag/1.14.7) in this repo.

**Comment by Lootyhoof** [comment]
@danny0838 The FTP no longer exists. I've also activated your account on the panel, please try to login again. Thanks!
