### ISSUE TITLE
[bug] Supplementary highlighter/formatter erase text formatting.

### ISSUE THREAD

**Issue by pascallothar** [danny0838/firefox-scrapbook#241]
Since a while, Scrapbook X changed its behaviour. 

My setting for "_HTML formatting template 2_" is: `<span style="border-bottom: medium solid rgb(204, 0, 0);" class="linemarker-marked-line" data-sb-obj="linemarker">{THIS}</span>`.

50% of the time 
_(I guess that it depends on how the selection was made. For example, if the cursor was going from left to right or from right to left before beginning the selection. And, consequently, what was put in the copying buffer.)_,
when I use Ctrl+Alt+2 to apply this formatting to a selection already formatted _(for example, italic, bold, hyperlink or a already scrapbook-highlighted selection)_, it will erase the previous formatting. If I take a larger or narrower selection _(for example, larger of only one white space)_, it will behave properly. It happens only when the selection corresponds exactly to the entire previous formatting. But it happens randomly.

So I guess you made some change in the code that induce this phenomenon. :-)

**Comment by danny0838** [comment]
We don't change any code about this in recent versions. But the precise selection area will be adjusted by the browser to better fit HTML spec, so it may change if you use a different browser or a different version.

We probably cannot do anything about this, and thus we'll close this issue. If you find something really severe, please provide a more detail information (the source web page, and what would happen if you select what area), and we may consider a further investigation.

**Comment by pascallothar** [comment]
> We probably cannot do anything about this

Following what you say, I think also that there is nothing to do for how Firefox behave to determine the "precise selection area". 

But, I think that it would be possible to **_prevent_** ScrapBook X **_to erase the previous tags_** (included the hyperlink tags, bold tags, italic tags, etc) and **_only_** let ScrapBook X **_add new tags and attributes_**. Wouldn't it?

**Comment by danny0838** [comment]
@pascallothar There are several technical details affecting this. It's actually not as easy as it may look like.

**Comment by pascallothar** [comment]
OK
