### ISSUE TITLE
[enhancement] Searching could list also folders, not only items

### ISSUE THREAD

**Issue by pascallothar** [danny0838/firefox-scrapbook#243]
When making a search by **Title**, there are never folders in the list. It could be sometimes useful if the searching would list also folders.

**Comment by mseliger** [comment]
I have resolved the problem by putting a simple note in every folder with the folder name and with tags, which define my folder structure, like #Favorites #Software #ScrapBook for the tree Favorites -> Software -> ScrapBook.

**Comment by danny0838** [comment]
Folders are never indexed and showed in the search results by convention. To  use a "searchable folder", create a note page and convert it to a folder (aka. non-folder-type-folder).

**Comment by pascallothar** [comment]
By the way, the content of the "**Comment**" (via "**Properties**") of a folder is not listed in the search results neither.

Is that normal?

**Comment by danny0838** [comment]
I don't get you. Folders are not listed in search results, and then how can we expect that the comment of folder be showed in the search results?

**Comment by pascallothar** [comment]
You said:
> Folders are never indexed and showed in the search results by convention.

I don't know why you made this convention. I guess it was to not "pollute" the search results with irrelevant results? But the content of the "**Comments**" of Folders could be relevant, especially when you make a search by "**Comments**". But don't mind, it has only to be known to not use the "**Comment**" field of Folders in the hope to make tags for Folders.

**Comment by danny0838** [comment]
This convention is not made by me. It's the behavior since ScrapBook and ScrapBook Plus.
