### ISSUE TITLE
upgrading from scrapbook v 1.5.14 questions

### ISSUE THREAD

**Issue by pbpb** [danny0838/firefox-scrapbook#246]
It's not clear to me from the documentation what exactly occurs when I install scrapbook-x when scrapbook is already installed.

It sounds like scrapbook-x simply uses the existing data and locations of scrapbook, maybe adding some extra stuff.  However, what is not clear is:

1.  Whether anything gets clobbered.
2.  Whether some of the conversions mentioned in the documentation are performed automatically.
3.  Whether it's possible to force scrapbook-x to install such that it uses a copy of the scrapbook data, rather than having to do that manually after installation.  This matters because I don't want anything clobbered during install or first startup of scrapbook-x.  (Obviously I could just back everything up first, but I don't want to have to do that twice since it's many gigs of data.)
4.  There is a bug in scrapbook where after roughly FF version 50, it does not drag and drop properly into the sidebar.  Has this been fixed?  Someone made a comment on the scrapbook page as to how to fix it -- need to use a different js call.

Thanks.

**Comment by pbpb** [comment]
I see from another report that #4 above has been fixed, so never mind on that one.

**Comment by danny0838** [comment]
We have this in the [manual](https://github.com/danny0838/firefox-scrapbook/wiki/Compatibility).

**Comment by pbpb** [comment]
Thanks for replying, but I did read the manual, and as I said it was not completely clear on the points I mention.

**Comment by danny0838** [comment]
Unfortunately we really cannot provide an answer for a rough question. If you are worrying about some specific case or you still have some question after reading the manual, reply with more detail. Or we cannot provide any more assistant besides the manual.
