### ISSUE TITLE
Firefox 57 incompatible

### ISSUE THREAD

**Issue by primaeval** [danny0838/firefox-scrapbook#247]
I expect this is a known issue. Please could you tell me what the status of fixing it is.

**Comment by danny0838** [comment]
This is an issue mentioned over and over again (#237, etc.). We are not going to port ScrapBook X, go for [Web ScrapBook](https://github.com/danny0838/webscrapbook) instead.

**Comment by primaeval** [comment]
Thanks. I couldn't see anything about it.
