### ISSUE TITLE
Cannot delete entry in Calculation Window

### ISSUE THREAD

**Issue by mirceglavni** [danny0838/firefox-scrapbook#25]
Don't know if this is intentional or not, but the delete button on right click on an entry in the Calculate Size window is greyed out, i.e. you cannot delete from there.
Tested with 0a39.

**Comment by danny0838** [comment]
Which version of ScrapBook were you use? This is not a new feature, and older ScrapBook X do not allow deleting non-INVALID items, either.

**Comment by mirceglavni** [comment]
You're right, just checked it with my home-install (0a36), also not allowed to delete. Didn't notice it until 0a39, as this revision had some changes to the calculate size window which I checked out. Maybe it's a little bit counterintuitive to have a delete option which is greyed out most of the time, but no problem, it's easy enough to select the item you want to delete, locate it on the sidebar and delete it.

**Comment by danny0838** [comment]
We made a change and non-invalid items are deletable in the latest revision (1.12.0a40). Thank you for the feedback:)
