### ISSUE TITLE
[bug?] Unsollicited logout of Wikipedia when saving.

### ISSUE THREAD

**Issue by pascallothar** [danny0838/firefox-scrapbook#251]
In my preferences of Wikipedia, I have chosen to stay logged in during 365 days. 

But when I save a page of Wikipedia with Scrapbook X, I am always logged out afterwards.

Why?

**Comment by danny0838** [comment]
Do you use download linked files that checks for HTTP header?

**Comment by pascallothar** [comment]
Yes I use "`download linked files`" set on "`Match HTTP header and URL file extension`" with "`images`" and "`video`" **_unchecked_**. Shouldn't I?

**Comment by danny0838** [comment]
Technically it's impossible to get the HTTP header without visiting a link. So when `Match HTTP header and URL file extension` is selected, effectively all links in the page will be "visited" by ScrapBook X in order to retrieve the HTTP header information.

Ideally a logout should not be implemented with simple links since it is vulnerable to a XSRF. Unfortunately some sites still do it in this way. If you don't really need to download linked files in that page you can simply disable the match or use match URL extension. If you really need to download some linked files that need a HTTP header match, you can either:

1. Selected the area you want to capture without the logout link, and use "Capture selected area".

2. Filter out the logout link via a hidden preference `scrapbook.save.default.linkUrlFilters`, which can be found in the `about:config`.

**Comment by pascallothar** [comment]
Thank you.

I understand much better now `Match HTTP header and URL file extension` .

1°) Could it be the reason why the site _http://mathworld.wolfram.com_ is banning my IP (fortunately I can reset it by rebooting my modem), saying I made too many connections, when I save for example the page http://mathworld.wolfram.com/TangentBundle.html ?

2°) Wasn't `Match HTTP header and URL file extension` implemented to fix the issue #96 ? So I guess, there is no other choice than using it, if I want to save for example https://en.wikipedia.org/wiki/Differential_structure ? Isn't it?

3°) For the moment, `scrapbook.save.default.linkUrlFilters` in `about:config` is set with the default `[]` . What should I write in this field **_to filter out the logout link_**? Taking the saving of ﻿https://en.wikipedia.org/wiki/Differential_structure as example?

**Comment by danny0838** [comment]
1. Maybe. A web site may block a user if he attempts to request for a lot of web pages in a very short interval. In this aspect, download link files that checks the HTTP header and inDepth save are at risk.

2. No. Download linked files feature is for links (those using HTML markup `<a href="...">`). SVG images are images (those using HTML markup `<img src="...">`), they are captured as long as "Images" is checked, and their HTTP headers are obtained during the capture process.

3. The value is a JSON string that parsed to an array of strings, and each string can be a literal string or a RegExp (if it's formatted like `/regexp/flag`) and matches any part of the URL.
Wikipedia uses different logout links for different languages. If you use the french version, the logout link should be something like `https://fr.wikipedia.org/w/index.php?title=Sp%C3%A9cial:D%C3%A9connexion&returnto=...`, and you can use a value like `["/index.php?title=Sp%C3%A9cial:D%C3%A9connexion&"]` to filter out the logout link.

**Comment by pascallothar** [comment]
### To avoid to others some struggling, I will share my experience :
1. Pay attention to _**double quotes**_ `"`. Using _simple quotes_ `'` doesn't work. Actually, the _JSON spec_ requires double quotes.
2. Pay attention to _**escape**_ the _**escape character**_ `\` with a second `\`.
3. If you have multiple values in your array, don't forget to separate them with _**commas**_.

### Simple examples:

- If you wish to match `index.php?title=foo`, the **RegExp** is `/index\.php\?title=foo/` (`.` and `?` have to be escaped because they are **_special characters_** for the **RegExp** context). And the **`scrapbook.save.default.linkUrlFilters` value** is `["/index\\.php\\?title=foo/"]` (`\` has to be escaped because it is a _**special character**_ for the (?) JSON or (?) JavaScript or (?) (I don't know exactly!) **context**).
- To match also `INdeX.php?title=FoO`, use the **RegExp** `i` **flag** that will make it _case `i`nsensitive_. So your **RegExp** will be `/index\.php\?title=foo/i` and the **`scrapbook.save.default.linkUrlFilters` value** will be `["/index\\.php\\?title=foo/i"]`.
- If you need to match _**strings with slashes `/`**_, don't escape them. So, to match `en.wikipedia.org/w/index.php?title=foo`, your **RegExp** will be simply `/en.wikipedia.org/w/index\.php\?title=foo/i` and the **`scrapbook.save.default.linkUrlFilters` value** will be `["/en.wikipedia.org/w/index\\.php\\?title=foo/i"]`.

### Here a full example:
The **`scrapbook.save.default.linkUrlFilters` value**
`["/en\\.wikipedia\\.org/w/index\\.php\\?title=Special:UserLog(?:(?:in)|(?:out))&/", "/fr\\.wikipedia\\.org/w/index\\.php\\?title=Sp%C3%A9cial:(?:D%C3%A9)connexion&/i", "wolfram.com", "wolframalpha.com"]`

which is an **_array_** containing two **_RegExp_** and two **_literal strings_**,
will fit for links of the following types
- https://en.wikipedia.org/w/index.php?title=Special:UserLogout&returnto=Differentiable+manifold
- https://en.wikipedia.org/w/index.php?title=Special:UserLogin&returnto=Differentiable+manifold
- https://fr.wikipedia.org/w/index.php?title=Sp%C3%A9cial:Connexion&returnto=Vari%C3%A9t%C3%A9+diff%C3%A9rentielle
- https://fr.wikipedia.org/w/index.php?title=Sp%C3%A9cial:D%C3%A9connexion&returnto=Vari%C3%A9t%C3%A9+diff%C3%A9rentielle

and for all links inside the sites
- http://mathworld.wolfram.com
- http://www.wolframalpha.com

### Documentation
About **_Regular Expressions_** in _JavaScript_ : 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions

About **_`Array`_** in _JavaScript_ : 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array

Here, an excerpt of the _ScrapBook X Version History_ :
Version 1.13.0
Changes since v1.12.38
>  * New user preference "save.default.linkUrlFilters".
> 
>    This is a JSON string containing a simple string, a RegExp string
>    (e.g. "/\\\\.php/i"), or an array with a combination of them.
>    
>    A URL in an anchor (\<a> or \<area>) matching it (or one of it if it's
>    an array) will be totally ignored so that it's never condidered a
>    candidate of download linked files or deep save.
> 
>    It can be used to exclude an offending URL that should never be visited,
>    for example, a link that logouts the user.
> 
>    If the provided string is invalid, it will be ignored and the error
>    will be output to the browser console for trouble shooting.
>
