### ISSUE TITLE
under Waterfox not saving index.html file

### ISSUE THREAD

**Issue by jccalhoun** [danny0838/firefox-scrapbook#254]
using the latest version of Waterfox, scrapbookx doesn't seem to save the index.html file. when I go to save a page, it says it is completed and I click on the popup but then get a file not found. If I look on my drive, there is a folder with the correct address with the images and css and and js files, just no html. 
It used to work on an older version of waterfox but I'm not sure if you want to go to the trouble of keeping it compatible with waterfox or not.

**Comment by danny0838** [comment]
What are the versions of Waterfox that works and not works? What is the URL of the page you have problem saving?

I'm not very sure but there is also a similar issue on Firefox 56 (see #235). You can try clearing profile and disabling other addons and see if this solves the issue.

**Comment by grahamperrin** [comment]
@jccalhoun considering the linked issues: please tell whether this issue #254 is reproducible with multiprocess disabled in preferences of Waterfox 56.x.

**Comment by danny0838** [comment]
This issue is duplicated, see #235.
