### ISSUE TITLE
Found #370 "INVALID" entries: please help to recover.

### ISSUE THREAD

**Issue by t1onix** [danny0838/firefox-scrapbook#258]
Executing casually the "Calculation of size" command I discovered 370 entries marked as "INVALID", corresponding to as many pages of researches, that I thought I had saved (based on the notification of confirmation of "successfully saved" !!!). 

In reality all these folders are not  present/accessible from within Scrapbook-x .

 Is there a way to retrieve them and put them back in the original saving location (since the folders and related files are present in the "data" folder?)

 Please, I can not lose all this data due to a bug, and doing the same job again is impossible.

**Comment by danny0838** [comment]
If all files are saved correctly and there's only a problem of the ScrapBook tree, you can copy those folders to another directory, delete the item in ScrapBook X, and then import them from the directory. (Make a full backup of your ScrapBook folder before the operation in case there's something going wrong)

**Comment by danny0838** [comment]
Close stale bug that has no response. Comment if you still have an idea about this.
