### ISSUE TITLE
Scrapbook X captures less than Scrapbook on a certain page

### ISSUE THREAD

**Issue by MadsM** [danny0838/firefox-scrapbook#26]
I am using Scrapbook and Scrapbook X to capture a certain page.

I am trying to download a website with an overall design like:
http://www.MainPage.com/Subsite1
http://www.MainPage.com/Subsite2
etc.

Each subsite has pdfs, but they are linked in different ways.
ScrapBook easily handles them, when the link is “Subsite/filename.pdf”
But most of them are in a more complex format, like “Subsite/.pdf?title=&asset_type=FILETYPE/pdf…(a lot of file details follow)”, which I can’t make ScrapBook open.

Scapbook X captures all the pdfs, but it can't capture the links from MainPage to Subsite.
When I ask it to save the MainPage, it will start the capture dialogue, but freeze in the "Loading...20" stage
Scrapbook captures all links, but nok the pdfs.

Do you have any advice?

**Comment by danny0838** [comment]
When I visit the URLs given above, I cannot find any links to another webpage or pdf file. Could you make sure that they are correct?

**Comment by MadsM** [comment]
Thank you for a quick reply!
The URLs are just generic examples, I'm sorry. The website requires login, so I'm not sure how to best share more information?
If I'm logged in, the links are from HTTPS to HTTPS - which Scrapbook captures fine, but Scrapbook can't.
If I log out, the links will redirect from HTTPS to HTTP - and then both versions capture them easily.
Does that help, or can we troubleshoot in a different way?

**Comment by danny0838** [comment]
If there is no private information showed on the logged in page, try select all > right click > source, copy the whole source, and provide us the HTML source as well as the whole page URL in the address bar.
If there is something private showed on the logged in page, try mosaicking the private parts with asterisks or so (e.g. Danny -> D***y) in the source before providing.

**Comment by MadsM** [comment]
That would be okay - is there an e-mail address, where I can send it?

**Comment by danny0838** [comment]
You can send it here: danny[dot]0838[at]gmail[dot]com

**Comment by danny0838** [comment]
@MadsM Thank you for the feedbacks. This issue is identified and is fixed in version 1.12.0a42.
