### ISSUE TITLE
Full Text Searches open in tab regardless of setting in options

### ISSUE THREAD

**Issue by Rising-Soul** [danny0838/firefox-scrapbook#260]
In the Options, I've unticked 'Full text search' under 'Open in tab for the following operations', under Tabs. It still opens my searches in a new tab though, whether from the sidebar or from Manage.

I'm using Pale Moon 64bit 27.7.1, and Scrapbook X 1.14.5

Searches for Titles and other things work fine in the sidebar and Manage. Only full text doesn't work there.

**Comment by danny0838** [comment]
By design full text search result is always opened in a tab—the current tab if 'Open in tab' is unchecked and a new tab if it's checked.

**Comment by Rising-Soul** [comment]
Oh! That wasn't very clear in the options. ;)

It'd be really nice if there was a way to display full text results in the sidebar like all the other search options.

And/or maybe a way to have the search results open in a new tab by default instead of the display pane below the results. I know I can right click to open them in a tab... but that seems to be the only way I can find.

**Comment by danny0838** [comment]
Fulltext is implemented in a different module with the index search. We won't implement a change about this due to requirement of a large code work.
