### ISSUE TITLE
保存页面时如何避免延迟加载（lazy load)的影响

### ISSUE THREAD

**Issue by woyaojizhu8** [danny0838/firefox-scrapbook#261]
现在很多网页会延迟加载图片，即使已经滚动到了页面底端，保存网页时还是无法保存全部图片。貌似只会保留当前可视区域的图片，不在当前可视区域的，即使加载过也会被清除。在这种情况下如何保存完整网页呢？

**Comment by danny0838** [comment]
由於每個網站的加載方式及條件不同，這只能針對個別網站用人工或腳本處理。

所謂人工即是按照網站的動態加載方式操作網頁，確認所有內容已加載後再擷取；腳本方面可寫個適用於該網站的書籤小工具或用站台腳本相關的瀏覽器套件（如 Tampor Monkey 之類）。

**Comment by woyaojizhu8** [comment]
谢谢解答！我现在全局用了一个脚本nolazyload  ( https://greasyfork.org/zh-CN/scripts/791-nolazyload ), 暂时能满足需求。
