### ISSUE TITLE
Page downloaded with another style

### ISSUE THREAD

**Issue by superjuve** [danny0838/firefox-scrapbook#262]
Hi,

I have downloaded this website: https://www.pef.czu.cz/cs/

Originally it looks like that:
![image](https://user-images.githubusercontent.com/19925380/36390767-6a000f92-15a4-11e8-8f63-c539feb32f03.png)

This is what I have from Scrapbook:
![image](https://user-images.githubusercontent.com/19925380/36390796-7ce7f016-15a4-11e8-947d-3901cbfca559.png)

Any ideas why the page is spread from the left side until the right one?

Thanks for any ideas how to solve that!

**Comment by danny0838** [comment]
I don't see an issue here. You have different zooming for both pages?

**Comment by danny0838** [comment]
Close due to lack of information and has no further feedback.
