### ISSUE TITLE
到firefox 56为止，都是全功能兼容的吗？

### ISSUE THREAD

**Issue by woyaojizhu8** [danny0838/firefox-scrapbook#264]
我原先都停留在firefox 42，升级到56后感觉流畅度提升了很多，但是怕scrapbook x 功能随着firefox升到56会受到影响，如果有较大影响我就得回42了。请问据目前所知，scrapbook x 在Firefox 56上会不会因为firefox砍掉了一些扩展API而功能受到限制呢？

**Comment by danny0838** [comment]
目前有回報過的問題是 Firefox 56 可能偵測錯誤開啟了 e10s，因 ScrapBook X 與 e10s 不相容，這會造成無法正常擷取網頁。萬一發生可調整設定值讓 e10s 不啟用。詳見 #235。

除此之外尚未收到版本相關問題的回報。
