### ISSUE TITLE
Cannot save linked file

### ISSUE THREAD

**Issue by zbelial** [danny0838/firefox-scrapbook#265]
This  is a great firefox extension, thanks. But I have a wired problem that no matter whether I comment the line about pdf and txt  in Extensive Save, it can't save linked files.  
Following is the webpage that I wanted to save:  http://nil.csail.mit.edu/6.824/2015/schedule.html
And all txt and pdf files cannot be downloaded, such as http://nil.csail.mit.edu/6.824/2015/notes/l01.txt

**Comment by danny0838** [comment]
By default the download linked files feature is disabled, and you need to switch the drop-down list to match URL or HTTP header:

![default](https://user-images.githubusercontent.com/531417/38943517-2fc84400-4364-11e8-8581-7020cc1a54fa.png)
