### ISSUE TITLE
Normal filenames when saving

### ISSUE THREAD

**Issue by ernestoalfredo13** [danny0838/firefox-scrapbook#266]
Every time i save a page the filename should have the page name included in it instead of a timestamp only, cause later on when i'm trying to open a saved file i don't know to which page correspond. When i have multiple saved page it's impossible to tell the difference between them.

At least should ask me a name of the file before saving it.

**Comment by ernestoalfredo13** [comment]
You're right, thanks for your response, in my defense i think that the tooltip of the option it's not quite self-explained, it only suggests me to change the directory of the file instead of also the file name, never cross my mind that besides change the save directory it will also change the file name to the conventional one.

**Comment by danny0838** [comment]
Thank you for the feedback. We'd consider improving the UI.
