### ISSUE TITLE
Adding PDF text as tooltip

### ISSUE THREAD

**Issue by OknowYedgeIA** [danny0838/firefox-scrapbook#267]
It woudl be nice when saving PDF, as several have names not related to their contents, to get some pdf text as tooltip. This can be done like this scope.sh ranger association:

pdf)
   try pdftotext -l 10 -nopgbrk -q "$path" - && \
            { dump | trim | fmt -s -w $width; exit 0; } || exit 1;;

The same can be done, at least as a config option, when anotating something from a webpage like Wikipedia Peek add-on does to show a tooltip preview.

**Comment by danny0838** [comment]
Does pdftotext have a cross-platform implementation?

Calling an external application is complicated and requires some configuration and is unfriendly for users  for a browser extension. We may consider this but rather unlikely.

**Comment by danny0838** [comment]
Since legacy addons are not supported by Firefox, we'll  are move to Web ScrapBook and won't implement more functionality.
