### ISSUE TITLE
Feature request. Standalone app

### ISSUE THREAD

**Issue by Ygarr** [danny0838/firefox-scrapbook#269]
Please make standalone applicaton for such page storing

**Comment by shiftyshady** [comment]
you can run scrapbook x on waterfox. i can't imagine a better standalone app than waterfox
you can use dde messages to grab current browser tab and then run a command to open it on waterfox.
using keyconfig, it should be possible to call a scrapbook function to automatically start saving a page or bring up the save page as window
better than all that is to drop firefox for a better browser, waterfox, which does not come with all the spying features and it's not supported by an ad company (mozilla is 100% funded by advertising companies)

**Comment by Ygarr** [comment]
Thank you for advice. It is possible solution. I am using separate browsers like  the above-mentioned. but seems I need one more yet  
Cause each of Cyberfox, Waterfox, Palemoon, even Seamonkey, and Basilisk, and origin Firefox already has it`s sphere of application on my PC...

**Comment by Ygarr** [comment]
I Think it is convenient  to have one point of concentration of saved pages,  cause browser can be have excessive functionality. 
Also good  to migrate from-to other storages and PC`s,  to control, edit, work with  imported from other browsers.

**Comment by danny0838** [comment]
A standalone app cannot know what's in a dynamic generated page in the browser, and to build a GUI interface for viewing the web page could be as complicated as rewriting a web browser, which is not we have the ability and are going to do.

Standalone app + a browser extension as the helper is a possible approach. But it's still complicated and needs much investigation.

**Comment by GuitarTab** [comment]
> you can run scrapbook x on waterfox.

??
Does ScrapBook X work for you in Waterfox? It does not for me, see issues #254 and #281.

**Comment by shiftyshady** [comment]
@GuitarTab:
yes it does. as danny said, just make sure you have disabled multiprocessing

**Comment by danny0838** [comment]
[WebScrapBook](https://github.com/danny0838/webscrapbook) is the project of scrapbooking addon with a helper app.
