### ISSUE TITLE
Captured page is not normally accessible

### ISSUE THREAD

**Issue by mirceglavni** [danny0838/firefox-scrapbook#27]
Just encountered a problem with the following page
http://www.investopedia.com/university/financialstatements/financialstatements2.asp

Whatever the way of capture (whole page capturing, or only a multi-page selection), Scrapbook X reports the completition of the capture, but on the captured page there is no vertical scroll bar, and you cannot use the mouse wheel to scroll. You can scroll only with the up and down arrow keyes on the keyboard.
The normal, "live" page doesn't behave like this.
Just tested it with other sub-pages of investopedia - same problem.
Any ideas?

Tested with 0a41 and 0a42, PaleMoon Portable, Windows XP SP3.

EDIT: I thinkg the culprit in this case is the "Reorganise Styles" option in the capture dialouge box : If I deselect it, the page is captured "normally" ie you can scroll normally on the capture page.

**Comment by danny0838** [comment]
It is because the original algorithm to simplify CSS rules won't work for styles on the <html> element. It's a rather bad issue that could potentially cause captures inaccurate. Fixed in 1.12.0a44. Thank you for the report.
