### ISSUE TITLE
archive

### ISSUE THREAD

**Issue by shiftyshady** [danny0838/firefox-scrapbook#270]
It would be very useful to have a context menu feature to archive pages/folders/bookmarks (you know, specially for those saved pages that have some historical value but you don't want cluttering the tree).

By archiving I mean moving the page to a mirror of scrapbook folder structure, which could be placed itself in a special folder.

Long live Scrapbook X / Waterfox!

**Comment by danny0838** [comment]
Use the import / export feature and manage the exported files with the file manager. We are unlikely to develop new features for ScrapBook X as it's no longer supported by Firefox.
