### ISSUE TITLE
Scrapbook 1.5.14 destroys a free disk space.

### ISSUE THREAD

**Issue by JeanPaulLucien** [danny0838/firefox-scrapbook#272]
This addon is cool, but there is a big problem. Addon destroys a free disk space. It can't use a disk space sensibly. I have saved about 100 pages and it spent 1 GB of ROM.

I can describe an algorithm to use a disk space better, but I can't help it in code, I'm bad in JS and never developed addon.

**Comment by danny0838** [comment]
I don't get you. Could you be more clear about what "Addon destroys a free disk space. It can't use a disk space sensibly." exactly means?

**Comment by JeanPaulLucien** [comment]
@danny0838, I mean the addon downloads **everything** and summary will get duplicates.

**Comment by danny0838** [comment]
Please provide a specific test case.

**Comment by JeanPaulLucien** [comment]
@danny0838 what do you mean?

**Comment by danny0838** [comment]
Could you provide a specific test case? For example, when you capture which web page with which capture options, and which are the files that you think is useless, etc.

**Comment by JeanPaulLucien** [comment]
@danny0838 
https://github.com/JeanPaulLucien/scrapbook-dump/upload/master/saved%20pages/2017
That folder is 12 MB in total.

**Comment by danny0838** [comment]
This issue doesn't seem valid. No information is provided about what is the unwanted thing being saved. Even if provided, we are not likely to implement a feature change as ScrapBook X is now in maintenance-only state.
