### ISSUE TITLE
share scrapbookX profile between 2 firefox instances

### ISSUE THREAD

**Issue by shiftyshady** [danny0838/firefox-scrapbook#273]
I need to do that because on one instance multiprocessing is enabled, so I need another instance to save pages.
this seemed to work quite fine, but now I am finding that some pages are on disk, but not on the scrapbook index (the sidebar)
is there any way to make the viewing scrapbook to only read and never write or lock the index?

**Comment by shiftyshady** [comment]
Figured out that the reason the multiprocessing firefox wrote scrapbook index was due to reordering scrapbook pages and folders on the multiprocessing firefox.
is there a quick fix to make scrapbook unable to modify the index entirely? if not, is there a list of functions I could disable on the source code? Thanks

**Comment by danny0838** [comment]
Multiprocessing Firefox is not supported, as the documentation says.
