### ISSUE TITLE
一些使用上不夠人性化的部分

### ISSUE THREAD

**Issue by bluelovers** [danny0838/firefox-scrapbook#28]
「擷取網頁細節」功能的選項沒有自動記憶，每次點選後都必須在設定一次
希望能增加過濾 iframe 的選項

---

沒有資料夾移動功能，目前只能利用手動拖移來移動資料夾，資料夾多的時候非常不方便

---

當選擇一個資料夾並且新增資料夾時，資料夾是產生在同級，但是正常來說應該要新增在子級才對

---

排序功能 希望能增加能指定只對資料夾 或者 只對檔案做排序的功能
另外希望能增加將資料夾排序在檔案之前的選項

**Comment by danny0838** [comment]
感謝您的建議，以下逐點回覆：

* 「擷取網頁細節」選項自動記憶：將在未來版本加入

* 增加過濾 iframe 的選項：看起來是頗有意義的選項，但涉及比較大的變動，是否實做、何時實做還要再考慮

* 資料夾移動：將在未來版本加入

* 資料夾新增在子級：一般軟體新增項目時，皆是新增在選取項目的同級，例如 Adobe Acrobat 為 pdf 檔案新增書籤；有些軟體會額外提供「在子級新建項目」的選項，比如 Xmind，但預設仍是新增於同級。考量這個慣例，目前不傾向對此做修改。

* 排序功能：理想上最好能做到選取數個項目針對它們排序，不過這涉及相當大的變動，有技術困難，恐怕不是短期可以達成。只增加針對資料夾排序的功能比較簡單，但恐怕不夠應付各種需求變化，目前不傾向實做。您可考慮建立一個新資料夾，將檔案全部移入，排序後再移回原資料夾，步驟稍多了點，但應在可接受的範圍。

我不太理解「將資料夾排序在檔案之前」，目前的排序功能便是將資料夾、檔案、筆記等不同型態的資料項分組排序，未來版本會增加「依型態排序」的選項，可決定是混排或分組排，不知這是否符合您的需求？

**Comment by bluelovers** [comment]
意思是 排序時 單獨只對 資料夾做排序 而不更動 其他項目的排序位置
或者單純只將 資料夾 移動到 其他項目之前
---
本來想試著clone 做點修改補丁 不過目前還看不懂結構XD
----
另外最近發現搜尋時不知道為何容易出現 無回應

**Comment by danny0838** [comment]
瞭解了，關於「排序時 單獨只對 資料夾做排序 而不更動 其他項目的排序位置」，就如前所述，如果不能做到理想上的「選取數個項目針對它們排序」，目前傾向不做。至於「單純只將 資料夾 移動到 其他項目之前」似乎不太屬於排序的範疇，個人認為選取那些資料夾再拖曳到前面即可。

和排序有關的程式碼主要在 content/scrapbook/sort.xul 及 content/scrapbook/sort.js，目前版本用的是 ScrapBook Plus 改寫過的程式碼，比較複雜，[https://github.com/danny0838/firefox-scrapbook/tree/test-sort](草案)打算改回基於 ScrapBook 1.5.11 的程式碼做調整，經實測效能有極小幅的下降，但整體而言比較精簡易讀，如有興趣可參考看看。

搜尋演算法在最近幾個版本有不少改動，以支援較複雜的條件，效能則可能會稍有下降，或許因此較易跳出「程式碼無回應」警示。能否提供您的資料筆數及大小？咱們再進一步評估及研擬改善方案。

**Comment by bluelovers** [comment]
資料筆數 3212 / 2983 個項目
scrapbook.rdf 1.77mb
cache.rdf 47.4mb

**Comment by danny0838** [comment]
您的資料量比我的多一點，但應在可容忍範圍。您能否分辨無回應是在處理特定資料項時發生，或是隨機性地發生？另外，您使用的搜尋關鍵詞是簡單關鍵詞或是複雜條件？改變這點會有影響嗎？

**Comment by bluelovers** [comment]
目前測試三個資料庫
都是使用簡單的英文字 或者 中文

猜測應該是在快取建立要完成時的最後步驟才無回應

也許可能要考慮再建立快取檔案時 將快取檔案做分卷切割

目前排除記憶體問題 因為未使用的記憶體還有 好幾G

1 & 2 都在執行搜尋建立快取的進度條滿了之後 就無回應
再次搜尋只會再度重新建立快取 然後再度無回應

3 在進度條滿的時候 會稍微停一下 但是正常完成快取
再次搜尋時無須再次建立快取 搜尋都是瞬間搜尋完成

1
---
資料筆數 3212 / 2983 個項目
scrapbook.rdf 1.77mb
cache.rdf 47.4mb

無回應

2
---
資料筆數 1602 / 1488 個項目
scrapbook.rdf 937kb
cache.rdf 21.5mb

3
---
資料筆數 644 / 622 個項目
scrapbook.rdf 383kb
cache.rdf 5.75mb

**Comment by danny0838** [comment]
所謂無回應是指跳出「執行過久，是否繼續執行」的視窗？還是整個 Firefox 當掉？

如果直接從搜尋下拉 > 工具 > 更新快取，也會這樣嗎？此時建立快取的視窗是否有關閉？

嗯，如果方便，可打開 Ctrl+Shift+J 偵錯視窗，先清除所有內容再跑搜尋/快取，看看是否有錯誤訊息？

**Comment by bluelovers** [comment]
整個 Firefox 當掉無回應
沒有出現詢問「執行過久，是否繼續執行」

另外剛剛發現 1 & 2 的 cache.rdf 實際上根本沒有建立(我看到的檔案是以前建立的)

工具 > 更新快取 也是一樣結果

**Comment by bluelovers** [comment]
..........剛剛 發現把舊的 cache.rdf 刪除就正常了= =
可能需要考慮加上在建立快取之前 先刪除舊的檔案的設計了XD

**Comment by danny0838** [comment]
刪除舊 cache.rdf 以後重建那次正常，之後再重建也正常嗎？或是仍須刪除才正常？

之前的 cache.rdf 是用舊版 ScrapBook 建立的嗎？

**Comment by bluelovers** [comment]
好像正常

恩 舊版建立的 日期一個是 今年一月 一個是去年

**Comment by bluelovers** [comment]
一個沒有刪除 可以正常重建快取

另一個則會失敗 必須要再刪除一次 才能正常重建快取

感覺起來還是刪除比較保險

**Comment by danny0838** [comment]
我目前無法重現這問題，可能要再觀察一下，如果有發生，試試叫出瀏覽器控制台觀察有沒有錯誤訊息。

最近有個類似的問題，在寫入 xxx.rdf 時可能會多出 xxx-1.rdf 的檔案，長久下來可能會有一堆 xxx-#.rdf。但在不同電腦實測，有些電腦常發生，有的電腦則幾乎永不發生，這指向是 Firefox 本身設定或其他附加元件交互作用所致，而非 ScrapBook 本身的問題。但也請順便觀察是否有此現象。

先刪檔再寫入的最大風險是萬一因故寫入失敗，檔案會永久遺失；當然這不是無法解決，但處理上會變得比較複雜。Firefox 有專門的內建指令管理 rdf 寫入，如無特別嚴重的運作異常，還是會先維持現狀。

**Comment by bluelovers** [comment]
控制台在無回應之前 沒有錯誤訊息

刪除不保險的話 可以考慮先將原有的更名 這樣就算寫入失敗 原有的也能夠復原

**Comment by danny0838** [comment]
嗯，如果問題確實存在且很嚴重，這似乎是唯一方法。

方便在不同的 Firefox 安裝上測試嗎？比如弄個 Portable Firefox 版本，不裝其他addons，然後試試是否有同樣的問題？

**Comment by bluelovers** [comment]
目前暫時沒有發生無回應狀況(包含免安裝版) 所以應該只需要簡單的先加上更名來避免意外狀況即可

**Comment by danny0838** [comment]
重建索引時無回應的問題已於 1.12.0a50 修正
