### ISSUE TITLE
有个网站中的网页抓取不了。

### ISSUE THREAD

**Issue by pczbq806** [danny0838/firefox-scrapbook#285]
你好！
    我在使用 ScrapBook X 1.14.5 抓取 https://crxdoc-zh.appspot.com/extensions/ 的下级网页（过滤条件为 Include crxdoc-zh.appspot.com）时，每个网页的状态均显示为 405 Method Not Allowed，不知道能否解决此问题。

**Comment by danny0838** [comment]
ScrapBook X 的深層擷取需要用到 HTTP 的 HEAD 方法，而該網站不支援該方法（有一點違反一般的 HTTP 協定）。

要解決這問題需要大幅更改程式碼，由於本專案已經停止開發，除非有熱心人士願意協助，否則大概不會動了。

[WebScrapBook](https://github.com/danny0838/webscrapbook) 未來若加入深層擷取功能，會設法避免此問題。（雖然目前也是八字還沒有一撇XD）

**Comment by pczbq806** [comment]
谢谢！一直用 ScrapBook X 收集网页，强大而便利！
