### ISSUE TITLE
How to import old windows Scrapbook data into Mac WebScrapbook

### ISSUE THREAD

**Issue by Gandalf99** [danny0838/firefox-scrapbook#286]
I have very old data from a Windows version of Scrapbook. I'd like to review it to see if there's anything I need to keep before I jettison the whole lot. Supposedly WebScrapbook on a Mac (FX v75) is supposed to be able to import this data, but it's not at all clear to me what I need to do to make it happen. While I am pretty computer literate, my technical skills died with DOS, batch files, etc, so please be gentle.

**Comment by danny0838** [comment]
We already have a [documentation](https://github.com/danny0838/webscrapbook/wiki/Import)
about that. If you have a problem fowwling it please be specific about that and we can possibly provide more assistant.

**Comment by danny0838** [comment]
Close due to no feedback. If you still have a problem following the doc, please raise an issue in the [WebScrapBook repo](https://github.com/danny0838/webscrapbook) with more details.
