### ISSUE TITLE
Spider

### ISSUE THREAD

**Issue by Davidgithub1** [danny0838/firefox-scrapbook#288]
What's a good spider tool? Every tool I've used was not able to download websites that ScrapbookX was able to.

**Comment by danny0838** [comment]
How would you define "a good spider tool"?

For a general case, HTTrack seems to be a quite good one.

**Comment by Davidgithub1** [comment]
I've used HTTrack but it doesn't download many websites that ScrapbookX is able to.

**Comment by danny0838** [comment]
Which websites? Please be more specific.

**Comment by Davidgithub1** [comment]
1. HTTrack is not easy to use. ScapbookX is easy to use and takes 1 seconds to start downloading a webiste.
2. HTTrack has trouble preserving the CSS and look of many websites I've tried to download. ScapbookX has always been able to preserve the look / style of every website. 

That's why I use ScapbookX !

**Comment by danny0838** [comment]
SBX does not support preserving original file structure, which is what some user care about most. On the other hand, HTTrack does not support advanced DOM rewriting, such as not saving scripts,  videos, etc. It really depends on your use case, and just choose the tool that works best for you.

**Comment by Davidgithub1** [comment]
ScapbookX works best for me. But I'm afraid websites will stop supporting old firefox.
Can you create a version that uses Headless Chrome to save an entire website (follow links)?

**Comment by danny0838** [comment]
Handling headless Chrome is too much work, we are unlikely going to do that.

**Comment by danny0838** [comment]
ScrapBook X already has this feature. As for this feature in WebScrapBook, we'll track in [its source repo](https://github.com/danny0838/webscrapbook/issues/164).
