### ISSUE TITLE
Dynamically changing images

### ISSUE THREAD

**Issue by Zorgodon** [danny0838/firefox-scrapbook#290]
Some pages load images dynamically. Example: [howtogeek](https://www.howtogeek.com/howto/41560/how-to-get-ssh-command-line-access-to-windows-7-using-cygwin)
They start out by loading a 1px\*1px transparent gif, and then replace it with a png using javascript as the page is scrolled. _Mozarchiver_ has the same issue, while the Wayback machine copies the gif replacement script and loads the actual images as I scroll:   [howtogeek-wayback](http://web.archive.org/web/20200531052907/https://www.howtogeek.com/howto/41560/how-to-get-ssh-command-line-access-to-windows-7-using-cygwin)
I have tried everything in the default save options, but it seems that when scrapbook sees the 1*1 gif, it happily saves it and ignores the pngs that are supposed to be loaded later.
How can I save pages that have this annoying and noncompliant behaviour?

**Comment by Michaelsy** [comment]
I checked your page and I'm able to save all relevant images in my ScrapBook. First you have to scroll all the way down until all images are loaded. And only then save the page in ScrapBook.

**Comment by danny0838** [comment]
You can configure **capture helper** to capture deferred-loading images. For example, write this for the site you provided:

```json
[
  {
   "description": "save deferred images in How-To Geek",
   "pattern": "/^https://www\\.howtogeek\\.com(?:/|$)/",
   "commands": [
     ["attr", {"css": "img[data-pagespeed-lazy-src]"}, "src", ["get_attr", null, "data-pagespeed-lazy-src"]]
   ]
  }
]
```

Of course you'd have to modify the code to get it work for another site, since it may implement a different dynamic image loading technique, and thus it's impossible for a single simple setting to work for all sites.

**Comment by danny0838** [comment]
Sorry for my careless. Capture hepler is a feature of WebScrapBook, and ScrapBook X doesn't support it. You can, however, write a site-specific script to do the automatic image loading using a user script via TamperMonkey or so.
