### ISSUE TITLE
Not all pictures are saved

### ISSUE THREAD

**Issue by Everest8** [danny0838/firefox-scrapbook#292]
I am using the old, pre-revolution version of ScrapBook with the old, pre-revolution version of Firefox. Oftentimes, when a page to be saved contains multiple photos, only a few, first ones are saved. Is there any parameter in ScrapBook, like timeout, that can be adjusted to ensure that all photos are saved? Thank you.

**Comment by danny0838** [comment]
What is the web page you are trying to capture? If it is the web site that implements a lazy loading mechanism, such as loading only images visible in the screen, there is no configuration and the only way is to scroll the screen manually or programmatically (such as installing a user script that does the scrolling).

You can [configure the capture helper option](https://github.com/danny0838/webscrapbook/wiki/FAQ#some-web-pages-load-images-only-after-the-screen-is-scrolled-down-is-there-a-way-to-capture-the-complete-page-without-scrolling-the-screen) for some simple cases if you are using [WebScrapBook](https://github.com/danny0838/webscrapbook) instead.

**Comment by Everest8** [comment]
Thank you for your quick reply. I am sending you an example of such a
partially captured page. No, it captures not only photos visible on the
screen, but still not all of them. Moreover, if you do it several times in
sequence, the number of captured photos often varies from one attempt to
another. That makes me think that there is some kind of timeout issue.

**Comment by Everest8** [comment]
You may be right, actually. If I scroll through the whole page before
capturing, it appears that all photos are captured. I will test it more.

Thank you.

**Comment by Everest8** [comment]
Danny,

I have a question, which is not directly related to your great addon, but
still is close...

When I use my old Firefox 52.9.0 (in order to be able to use the older
ScrapBook, in which I now have 11,000+ captured pages), some sites display
only the first of several pictures in the page. This is related not only to
the ScrapBook capture, it happens even at the first opening of the page,
regardless of ScrapBook. Scrolling does not help. Chrome and Edge show all
the pictures of the same page.

Here is a sample page from one of such sites as an example:

https://www.architecturaldigest.com/gallery/home-libraries-slideshow?utm_source=nl&utm_brand=ad&utm_mailing=ARD_Daily_AM_010221&utm_campaign=aud-dev&utm_medium=email&bxid=5e6ea7bd6c28c710c4051859&cndid=60287870&hasha=267b9a9f03d5b6b94caf306fd41ef5b7&hashb=186e3ae26a317b23e7e4148ceeba02f69048bd56&hashc=099d06398100192bb651b9996e431cc6a683dc31a0a0d0874203824dc8e2767b&esrc=subscribe-page&utm_term=ARD_Daily

Firefox displays only one picture, 1/35. Below is a screenshot. Ironically,
all the ad pictures (not seen on the screenshot) are always shown in full.

Do you have an idea what may be the cause of such behavior?

Thank you.

Vitaly

[image: image.png]

**Comment by danny0838** [comment]
@Everest8 It seems that there are some scripts in the website not working for Firefox 52.9. You may consult the website manager to know whether it's a bug, or they simply aren't intended to support older browsers.
