### ISSUE TITLE
希望「擷取網頁細節」的選擇資料夾能摺疊

### ISSUE THREAD

**Issue by bluelovers** [danny0838/firefox-scrapbook#31]
資料夾多的時候 不方便選取想要的資料夾

希望能類似其他部分的選擇資料夾一樣

**Comment by danny0838** [comment]
點擊右邊的「選取資料夾」按鈕就有摺疊式清單可使用，因此這部分不會修改。保留那個繁雜的下拉選單，是因為該選單會記錄最近選過的資料夾，且如不放上整個資料樹，選取不在裡面的資料夾會顯示成空白。

倒是「新增資料夾」按鈕似是多餘的（「選取資料夾」就有開新資料夾的功能），會考慮拿掉，讓界面精簡一點。

**Comment by bluelovers** [comment]
「新增資料夾」可以考慮留著，畢竟他是可以直接新增在目前選擇的位置那邊

**Comment by danny0838** [comment]
嗯...看起來「選取資料夾」對話視窗是比較適合把資料夾建立在子層，我把草案做了些調整，看看有沒有比較符合需求？

**Comment by danny0838** [comment]
已於 1.12.0a48 處理
