### ISSUE TITLE
擷取時 希望能夠區分背景圖片以及一般圖片

### ISSUE THREAD

**Issue by bluelovers** [danny0838/firefox-scrapbook#36]
希望能有增加這種選項

**Comment by danny0838** [comment]
看起來是比較次要的需求，也會增加複雜性，還要再評估

**Comment by bluelovers** [comment]
主要是這樣可以減少擷取不需要的檔案
而不至於需要去資料夾內手動刪除

尤其在擷取網頁時 雖然已經先編輯過之後 才擷取 
但是卻會從CSS內 去抓取目前頁面上沒有用到的樣式圖片

經常擷取的情況下 這類多餘的檔案 會造成總體容量的肥大

**Comment by danny0838** [comment]
ScrapBook X 如有把「CSS 處理」設為「改寫連結，移除未知及未使用者」，應該不會儲存未用到的元素的樣式定義，也不會儲存相關的樣式圖片。

如果還是有區分背景圖片和一般圖片的需求，[WebScrapBook](https://github.com/danny0838/webscrapbook) 有支援此功能，的確是非常複雜orz 由於涉及大的架構更動，ScrapBook X 不會在這方面做改動。
