### ISSUE TITLE
Updating search index is very slow and freezes the browser

### ISSUE THREAD

**Issue by dliw** [danny0838/firefox-scrapbook#37]
I had to force close the browser after it got unresponsive for more than 10 minutes
ScrapBook 1.5.11 took about 20s to update the index.

Additionally it seems, that ScrapBook X does not update the index automatically if new pages were added and then a new search is started.

**Comment by danny0838** [comment]
The search index is not automatically rebuilt when a new search is started unless the cache.rdf is very small (<32K). This feature is same in ScrapBook X, ScrapBook, and ScrapBook Plus.

As for the unresponsive problem. Could you try removing the ``cache.rdf`` manually, rebuild again, and see if it works?

**Comment by dliw** [comment]
Ok, I removed cache.rdf (~ 35MB) and rerun indexing. It seems to be a bit better than last time, but the browser still is rather slow when indexing. 
Indexing finished in about 2 Minutes - IMO a bit longer than ScrapBook used to need.

**Comment by danny0838** [comment]
ScrapBook skips several process when rebuilding a cache if it already exists, and thus it's predictable that a complete rebuild be slower than a partial rebuild.

In one of my personal ScrapBook with 1837 items, 72760 files, 1837 folders, 1.16GB in total size, it takes 0:57 for a complete rebuild and 0:21 for the following partial rebuild in ScrapBook X 1.12.0a49. And it takes 1:01 for a complete rebuild and 0:18 for the following partial rebuild in ScrapBook 1.5.11.

**Comment by dliw** [comment]
> thus it's predictable that a complete rebuild be slower than a partial rebuild.
Yes, of course.

The actual problem was the crash/freeze, which doesn't happen when `cache.rdf` is removed manually.

Updating runs as quick as usual, my collection is a little bit bigger than yours, so that timing is roughly equal.

Could it be, that the progress bar gets updated only after a complete folder / item is processed?
I have a few folders that contain recursively captured web pages. If these get indexed for the first time, the browser "freezes" / is unresponsive.
When indexing single page items or when updating there's no such impact.

But actually this is acceptable, as this happens only when indexing for the first time.
