### ISSUE TITLE
Search results are missing .html

### ISSUE THREAD

**Issue by dliw** [danny0838/firefox-scrapbook#38]
Search result preview doesn't show up, as all links are missing the extension `.html`.
The same happens when double clicking a search result (url in new tab is missing a `.html`).

**Comment by danny0838** [comment]
Could you provide a detail about your process to reproduce it? You mean a fulltext search or a filtering search? Are you searching in the main sidebar or the "Manage" window?

**Comment by dliw** [comment]
I do a fulltext search. So a new tab opens and lists all matching pages. That works well.
Now when you click on a result, the selected page should be shown in the lower part of that tab. But actually I only see an error, which states that the page (file://path-to-file) could bot be found. And that's because the path is missing a .html.

But maybe this is related to issue #37?

**Comment by dliw** [comment]
Seems to be a problem, if cache.rdf is not updated after switching to ScrapBook X.

**Comment by danny0838** [comment]
We've added a note for the [compatibility issue](https://github.com/danny0838/firefox-scrapbook/wiki/Compatibility) about the cache. Thank you for reporting this issue. 

We'll further investigate if it's possible to prevent a nonresponsiveness of Firefox when rebuilding a cache that is create in an old version ScrapBook.

**Comment by danny0838** [comment]
Fixed non responsive problem in 1.12.0a50.
