### ISSUE TITLE
Notification type

### ISSUE THREAD

**Issue by dliw** [danny0838/firefox-scrapbook#39]
Somehow notifications of ScrapBook X differ from "usual" firefox notifications, they are shown in the system tray.
Could there be a preference on how the notification is shown?

I really like the feature to be notified if a page was captured before, but currently it pollutes my notification system tray.

**Comment by danny0838** [comment]
What is a "usual" firefox notifications? And what is a "notification system tray" and what's wrong about it?

**Comment by dliw** [comment]
Sorry for being unclear. I'll try to explain - possibly it's not scrapbook's fault...

With "usually" I mean, that - from what I experienced up to now with other addons I have installed - if a notification is shown, it is "inside" firefox. So a small box with information pops up in the lower right corner of Firefox.

As I run Linux with KDE there is a "global" notification tray (*). Now Scrapbook X shows it's notifications in there and not inside Firefox - that's my problem.
However just yesterday another addon started to use the "global" notification tray, so it might be, that Firefox 36 changed how notifications are handled...

So if you're not doing something fancy with libnotify - which I suppose (sorry for not looking into the code) - you can actually close this issue.

In that case, it would be nice to get a hint, if a page is going to be captured twice (maybe asking for confirm).
Instead of notifications, a additional icon in the address bar, which shows up, if a page was captured and shows further information in a popup, if hovered, would be a less distracting alternative.

(*) Looks like: http://www.crystalxp.net/news/img/4732.png or http://www.crystalxp.net/news/img/4730.png

**Comment by danny0838** [comment]
Yes, ScrapBook X notification is using the native Firefox notification mechanism. Do you think it would be better if the notification were as ScrapBook Plus did?

This notification is not only for reminding that a capture is being duplicated, but also for reminding that the current-viewing page has a copy in ScrapBook and the user would probably want to take a look since there could be comments and highlights, and therefore a cost in attention distract seems required. However this indeed could be unwanted for some people. We'll consider adding an option that reminds the user only if a duplicating capture is going to happen, or to show in a less attracting way.

**Comment by dliw** [comment]
>Do you think it would be better if the notification were as ScrapBook Plus did?
Actually no. If you want to show a notification that's the right way to go...

Basically I think these are two distinct features:
- warning when capturing pages twice (in my case *really* helpful, I even wrote a shell script that detected duplicate captures)
- information if, when and how often a page has been captured

For the latter case IMO a notification is too "strong". Read: For me it isn't that important, that I wanted to see it in my "global" notification tray.
Apart from the ideas already mentioned, you could alos show a bar (similar to what appears when a plugin gets blocked), this would be visible but not too distracting. More like a offer to switch to the captured page.

>We'll consider adding an option
As far as I'm concerned you can close this issue...

**Comment by danny0838** [comment]
OK. Thank you for the feedback. :)
