### ISSUE TITLE
Restart l10n

### ISSUE THREAD

**Issue by yfdyh000** [danny0838/firefox-scrapbook#41]
还放在 BabelZilla，或者放在 Transifex 等平台。方便及时更新。

**Comment by danny0838** [comment]
對這幾個平台不熟悉耶，可能要研究XD

**Comment by shyangs** [comment]
建議放在 Transifex.

 BabelZilla 好像連 bug 回報系統都沒有人在管。像 [Encoding '<' and '>' in downloaded DTD files](http://www.babelzilla.org/forum/index.php?showtopic=7632) 這討論串，2014年10月說 Bugtracker 故障，到現在都沒人回應。

**Comment by shyangs** [comment]
也有套件作者是用 github 的 pull requests 來接受翻譯的。不過這樣的門檻比較高，翻譯者要會一點 git.

**Comment by bluelovers** [comment]
github 也支援 從網頁上編輯 也不會太難XD

**Comment by yfdyh000** [comment]
本addon的语言文件偏多，本地不太好编辑。而且没有检查措施，容易出现漏掉转义、丢个等号之类的疏忽，导致界面出错。而且没有更新通知到译者。

**Comment by bluelovers** [comment]
XD 話說... firefox 的語言包機制 感覺好笨... 只要語言包內缺少了某個條目 就會整個出錯 
不會自動從英文語言包內 抓條目來補= =

**Comment by bluelovers** [comment]
可以考慮使用 Sisulizer 我都用這個來翻譯軟體
https://github.com/bluelovers/firefox-scrapbook/tree/feature/i18n/sisulizer/1

**Comment by yfdyh000** [comment]
@bluelovers 呃，没必要用本地软件吧，明显增加门槛。
BabelZilla、Transifex、crowdin.com 等平台都可以。

**Comment by danny0838** [comment]
實在沒有餘力去研究另一套翻譯平台，加上 1.13.0 版已將要翻譯的檔案數精簡為 2 個，要翻譯直接修改語系檔並提交 issue 或 pull request 即可。目前不考慮使用其他平台。
