### ISSUE TITLE
Scrapbook X and Scrapbook

### ISSUE THREAD

**Issue by samspo** [danny0838/firefox-scrapbook#46]
Hello Danny,

Thank you for your work.
Today, firefox automatically updated the version of scrapbook X to scrapbook Version 1.5.12 from @gomita 
Is there any problem of compatibility with firefox-scrapbook X?
Just to know, is there any coordination between you two or does these two versions evolve in parrallel?

Thanks,

**Comment by danny0838** [comment]
Really?! That's bizarre. ScrapBook X should not be updated to ScrapBook in any ways.

You can shift from ScrapBook X to ScrapBook or vise versa. However there is possible compatibility issues. Check [this page](https://github.com/danny0838/firefox-scrapbook/wiki/Compatibility) for more details.

**Comment by samspo** [comment]
Pretty sure it automatically updated Scrapbook X to Scrapbook.
Thanks for your answer.

**Comment by danny0838** [comment]
Is ScrapBook installed on your Firefox where ScrapBook X is installed? And is ScrapBook disabled?

**Comment by danny0838** [comment]
closed since no response over half year

**Comment by samspo** [comment]
Sorry for the absence of answer. This behavior didn't reproduce since. You can close the issue.
