### ISSUE TITLE
Cannot compose email of mail.yahoo.co.jp if Scrapbook x installed

### ISSUE THREAD

**Issue by mozillabug** [danny0838/firefox-scrapbook#47]
This problem happens on Windows7 Firefox31ESR and Firefox36+.

Steps To Reproduce:
1. Install Scrapbook X with newly created profile
2. Login mail.yahoo.co.jp
3. Compose mail and attempt to edit message body

Actual Results:
No caret is shown. And I cannot input/edit text.

Disabled Scrapbook x solves the problem,
Original Scrapbook does not have the problem.

**Comment by mozillabug** [comment]
https://github.com/danny0838/firefox-scrapbook/commit/b0897abf6073bcfb76218cc2483139c63699cc23 triggred the bug

**Comment by alice0775** [comment]
It seems to fix if I add | typeof isTemp !="undefined" && | to editor.js line 529.

- if (isDisable && !isTemp) sbHtmlEditor.init(null, 0);
+ if (typeof isTemp !="undefined" && isDisable && !isTemp) sbHtmlEditor.init(null, 0);

**Comment by danny0838** [comment]
@mozillabug I don't have an account for mail.yahoo.co.jp. Please test if patch 426410fc3f93ece2b41b59ec21c6828b0291cddb works.

**Comment by danny0838** [comment]
@mozillabug I don't have an account for mail.yahoo.co.jp. Please report whether patch 93a0c375b20ed15c7250f25153067fa56b8aed75 fixes it.

**Comment by alice0775** [comment]
I can confirm the patch 93a0c37 fixes the problem. Thanks.
