### ISSUE TITLE
cannot perform simple AND-ed search

### ISSUE THREAD

**Issue by grotesque** [danny0838/firefox-scrapbook#49]
Firstly, your add-on is awesome. Thanks for all the effort.

Now, suppose I want to : 
find all the pages, notes etc.
whose any data (title, content, comments etc.) contain the exact words: Processor Interrupts Sec

Currently there is no way to do this easily (i.e. without regular expressions).
Following query doesn't work: Processor Interrupts "Sec"

**Comment by danny0838** [comment]
Do you try `"Processor Interrupts Sec"` and it still doesn't work?

**Comment by grotesque** [comment]
I am not trying to find the phrase "Processor Interrupts Sec".
I am trying to find all pages that contain words, "Processor" AND "Interrupts" AND "Sec"

What happens now is that we match Sec with words like "Security", "Secondary" etc. to give irrelevant results (lots in my case).

What can be done is something like "match whole word" or something.

Anyway, I think I'll switch from scrapbook plus to this soon. Also, let me know if you need help with testing or something.

**Comment by grotesque** [comment]
Just found out that following works:

query: Processor Interrupts "Sec "

PS: note the space after Sec to force scrapbook x to treat it as a word
