### ISSUE TITLE
[enhancement] voluntarily choose to ignore few file extensions

### ISSUE THREAD

**Issue by grotesque** [danny0838/firefox-scrapbook#50]
1)
WWW is bloated.

2)
Try clipping pages like with scrapbook X 
https://addons.mozilla.org/en-US/firefox/search/?q=ScrapBook&appver=&platform=

Clipped webpage size: 1771.52 KB

3)
go to clipped webpage local folder

4)
delete file extensions:
*.eot 
*.ttf
*.woff
*.svg

All font files are now deleted

5)
Clipped webpage new size: 217 KB
Webpage functions properly.

6)
88% reduction in size

7)
It would be nice if scrapbook X has to setting to automatically ignore certain file extensions.

**Comment by danny0838** [comment]
You can use "Capture As" and deselect images, media, fonts, frames.

**Comment by grotesque** [comment]
Oh...nice.

But I 99% of time use Auto-Save or keyboard shortcut for "Capture Page" or Drag n Drop (without Capture As POP up). All of these by default capture everything except scripts.

Can we make above mentioned ways, respect the last Setting of the "Capture As" ?

If not maybe I'll build my own changes and use them locally. Can you suggest what file and functions to look into to make these changes?

**Comment by kehandley** [comment]
I, too, would like a way to change the default settings for doing a capture, as most of the time that I capture I do "Capture all tabs...".

**Comment by danny0838** [comment]
You are right. These would be a nice and probably something that should have been implemented.

However the current framework of ScrapBook does not support several configs for some specific situations. For example, a multiple tab capture with depth capture is not supported. And thus assigning the capture detail settings for all subsequent captures would be a large rework of code (and thus error-prone).

So, unfortunately, this would be put into a "someday" plan and could be pending until a thorough reworking of ScrapBook framework is done.

**Comment by danny0838** [comment]
Close the issue since the feature that a normal capture remembers last capture detail options has been implemented since ScrapBook X 1.13.0b.
