### ISSUE TITLE
"Capture multiple URLS -> URL detector -> All links in selection" is not working

### ISSUE THREAD

**Issue by grotesque** [danny0838/firefox-scrapbook#53]
Nothing gets added.

The same works with scrapbook plus.

**Comment by grotesque** [comment]
You seem to have faced a similar issue earlier

https://github.com/danny0838/firefox-scrapbook/commit/800611b18eb8e8b71a3bd1f883340016560e049f

**Comment by danny0838** [comment]
Bug confirmed. This will be fixed in the next version. Thank you for reporting.

**Comment by danny0838** [comment]
Fixed in a1440cd77f3d9f349d85d66bd1e20144921ac326.
