### ISSUE TITLE
[issue] can not correctly download picture in this site

### ISSUE THREAD

**Issue by allen7575** [danny0838/firefox-scrapbook#55]
I can not correctly download .png files in this site: 
http://mirlab.org/jang/books/dcpr/feLda.asp?title=11-3%20LDA%20%28%BDu%A9%CA%C3%D1%A7O%A4%C0%AAR%29

I have selected download link options but useless, check the capture folder but still don't have those png files.

**Comment by danny0838** [comment]
There's currently a bug causing this and it will be fixed in the next release. Thank you for reporting.

**Comment by danny0838** [comment]
Fixed in bcc507984662ee9c3a709be8f596a86373587282.

**Comment by allen7575** [comment]
it works very well, thanks!
