### ISSUE TITLE
[issue]無法正確擷取數學式

### ISSUE THREAD

**Issue by allen7575** [danny0838/firefox-scrapbook#56]
用中文講比較快，跟上次同一頁
http://mirlab.org/jang/books/dcpr/feLda.asp?title=11-3%20LDA%20%28%BDu%A9%CA%C3%D1%A7O%A4%C0%AAR%29
你後來修正版之後，就能正確擷取數學式沒錯
但是我若從首頁開始擷取
http://mirlab.org/jang/books/dcpr/
擷取出來的那一頁，卻無法正確顯示數學式
照理說應該是同一頁，怎麼從不同地方擷取會不一樣？

**Comment by danny0838** [comment]
您指的是使用多層擷取功能擷取目錄頁，而後多層擷取得到的子頁面的數學式不正常？

擷取目前頁面時，是把目前瀏覽器呈現的 DOM 擷取下來，如果頁面有 javascript，會把 javascript 執行後的結果下來。多層擷取、多重擷取、擷取連結指向頁面等方式是用隱藏瀏覽器觀看，不會執行任何 javascript（且 javascript 執行條件複雜，目前沒有通用的方法能讓程式在瀏覽器把 javascript 跑完後才開始擷取，因為程式根本無法知道何時 javascript 跑完）。

您給的頁面其數學式是把原始碼寫在 HTML，然後用 javascript 動態渲染，非目前頁面由於只有擷取到原始 HTML，因而顯示效果不同。

就個人所知，砍站軟體或 bot 普遍有無法抓到 javascript 執行後結果的限制，這部分我們目前無能為力，只能說要擷取 javascript 執行後的顯示結果，若非對特定網站撰寫專門程式，就只能用瀏覽器一一開啟，待 javascript 執行完再擷取了。

**Comment by allen7575** [comment]
這麼說的話，那是否有可能在多層擷取的時候，
在新視窗開啟該頁面，等頁面跑完再擷取，之後再關閉頁面？
選項裡面加個"擷取javascript執行結果"之類的.....

**Comment by danny0838** [comment]
恐怕是不成，就如之前描述的：「javascript 執行條件複雜，目前沒有通用的方法能讓程式在瀏覽器把 javascript 跑完後才開始擷取，因為程式根本無法知道何時 javascript 跑完了」。

**Comment by allen7575** [comment]
那麼我選擇把javascript 存下來，讓他動態產生呢？
我有試過，在單頁的情況是OK的，查看原始碼，原始的數學式都在，是透過javascript動態產生的。
但是用多層擷取後，卻出現了錯誤訊息，原始碼被改了，這又是為什麼？

**Comment by danny0838** [comment]
javascript 能否正常執行需要依賴許多條件，那些條件在原網頁和擷取的網頁可能不同，因而前者能順利執行的 javascript 程式碼在後者未必能正常執行。

這便是為什麼程式會警告使用者「注意：儲存 javascript 可能會引發許多問題」。

基本上現在網頁的 javascript 越寫越複雜，擷取下來 javascript 不能用是常態，能用基本上是人品好。

**Comment by allen7575** [comment]
但我的問題是多層擷取出來的html原始碼跟單層擷取的原始碼也不一樣耶......這是正常的嗎？

**Comment by danny0838** [comment]
不太確定你的意思，假設是目錄頁 A 連向頁面 B、C、D，如果你指的是「瀏覽頁面 B 時單層擷取頁面 B」 的原始碼和「瀏覽頁面 A 時多層擷取頁面 A」得到的頁面 B 的原始碼不同，這是正常的，因為前者是頁面 B 已被 javascript 修改過的原始碼，後者是頁面 B 未被 javascript 修改過的原始碼。

**Comment by danny0838** [comment]
Closed suspended issue (no further discussion over half year). If there's more information, add comment here and open it again.
