### ISSUE TITLE
Dom Eraser not working within iframes

### ISSUE THREAD

**Issue by kehandley** [danny0838/firefox-scrapbook#58]
Hello.  I'm glad you are actively developing this program, as I just found it when I was having some frustration with the original Scrapbook.

The Dom Eraser doesn't seem to work within iframes.  The Highlighter, Annotation, and Eraser seem to work fine.  The Dom Eraser worked to some extent within iframes in the old Scrapbook.

And example URL where to demonstrate this problem is:

http://www.ebay.com/itm/Prohibition-Satire-Poems-THE-SWEET-DRY-AND-DRY-Cartoons-FRANK-KING-amp-J-P-McEVOY-/311327891722?orig_cvip=true

Thanks.

-Keith

**Comment by danny0838** [comment]
Support for DOMEraser in iframes is currently removed since there has been several issues on working with iframes, such as the label cannot be placed properly, the undo would be broken, and several commands cannot work correctly, etc. We'll improve it in the future if a solution comes out.

**Comment by danny0838** [comment]
Fixed in dd40c65f3e5c59904cd8258655d83a65a438ddd1 and in release 1.12.15
