### ISSUE TITLE
Font when using HTML Editor

### ISSUE THREAD

**Issue by mirceglavni** [danny0838/firefox-scrapbook#59]
Not exactly an issue given the main purpose of this addon, but I wonder if there are plans to further upgrade the HTML Editor of captured pages?
Maybe I am misusing Scrapbook X, but I find myself more and more trying to shift my work-related research exclusively to SB, for example: I capture an empty page, turn on HTML Editor, and whenever I find some interesting (rather short) infor, I copy it from the web-page or pdf document to this page. It works reasonably well, you have the basic formating options, lists, checkboxes, indendts, you can even make a table in word and copy it into the page. 
However, I didn't find a way to change the font of the text? Am I missing something, if not, are there plans to implement some additional font-selection in the editor?

And again, congratulations for your excellent work so far.

**Comment by danny0838** [comment]
No, we probably are not adding a font selection functionality. However, you can define font stylings in Tools > Options > HTML formatting template (1~0) and call them from the HTML Editor. This should work for most cases.

Additionally, if you simply want to write "notes" in a page, you can simply create and edit a note page so that a hack of capturing an empty page is not required.

**Comment by mirceglavni** [comment]
Thanks a lot for the info. However, not sure how to define the HTML formatting templates: If I go to Tools  / Options / Edit, under HTML formatting template 1...0 there are text boxes with the heading "eg. <code>{THIS}</code>.
This text is greyed out, ie you cannot enter something into the box. How do you edit this? What should I enter if I want for example font Calibre, size 11?

Thanks for your help!

**Comment by danny0838** [comment]
Doesn't the example show `eg. <code>{THIS}</code>`?

For your case you can try `<span style="font-family: Calibre; font-size: 11px;">{THIS}</span>`. Say if you define it in template 1, you can select a text and use Ctrl+Alt+1 to format it after that.

**Comment by mirceglavni** [comment]
Yes, the example show what is in your message; don't know why my post only shows  e.g. {THIS}.
I have entered the code you provided, it works.
Thank you very much for your time and help!
Regards

**Comment by danny0838** [comment]
It shouldn't happen that the example placeholder doesn't show the tags. Could you provide your OS, Firefox versiono, and ScrapBook X version?

**Comment by mirceglavni** [comment]
Dear Danny - think that there is a misunderstanding here. Here is a screenshot of my options page:
![clipboard01](https://cloud.githubusercontent.com/assets/9267744/8076277/b6ed95ee-0f4a-11e5-9dea-45602229a73f.jpg)
The placeholder is OK and coresponds to the one you stated in your post; however, when I wrote my post, it was sort of truncated, i.e. the tags were not shown in the post.
In case I am the one with the misunderstanding here are my specs:  I use WinXP SP3, PaleMoon 24 portable, last scrapbook x (1.12.3).

**Comment by danny0838** [comment]
OK. I get it. Thank you for the clarification.
