### ISSUE TITLE
Everything is captured except images on this site

### ISSUE THREAD

**Issue by leavion** [danny0838/firefox-scrapbook#60]
There is one site of the Haaretz newspaper that when I capture a page all is captured except the images in the article body.

An example of such a page (this page is outside the paywall):

http://www.haaretz.co.il/gallery/recipes/breakfast/1.2667686

So far this is the only site that I ran into this issue.

Page as seen in browser:
![original](https://cloud.githubusercontent.com/assets/13081708/8394448/d5804702-1cfd-11e5-9928-1960d8d46186.png)

Page as captured:
![as scrapbooked](https://cloud.githubusercontent.com/assets/13081708/8394449/df7d8d5a-1cfd-11e5-9987-2a14632f82e1.png)

**Comment by danny0838** [comment]
This is because the site uses the HTML5 `srcset` attribute for the `<img>` tag, which is not currently supported by ScrapBook X. We'll do further investigation for supporting it.

**Comment by danny0838** [comment]
Fixed in 1e334dea509109548b414ed10e193bdd3cd19f29.
