### ISSUE TITLE
"Capture Page" and "Capture Page As"

### ISSUE THREAD

**Issue by grotesque** [danny0838/firefox-scrapbook#62]
Currently, "Capture Page As" remembers the last-used "Capture Page As" settings 

eg. 
1. go-to a webpage
2. do "Capture Page As" (from right click menu or shortcut)
3. select "Capture as HTML" and capture to any folder (eg. root)
4. go-to different page
5. do "Capture Page As" (from right click menu or shortcut)
6. "Capture as HTML" is remembered and automatically selected the second time you perform "Capture Page As".

FEATURE REQUEST *1
Use same feature for "Capture Page" such that it remembers the last-used "Capture Page As" settings.

FEATURE REQUEST *2
Make "Capture Page As" setting remember the "last capture folder" just like it currently can remember stuff like "Capture as HTML" etc. This feature if implemented for "Capture Page As" will automatically apply to "Capture Page" if Feature *1 is implemented.

**Comment by grotesque** [comment]
Hi Danny,
Don't you think this enhancement should be easy to implement? I think so because the "remembering last used setting" feature is already implemented for "Capture Page As" and we just need to copy/port it to "Capture Page".

Also, can I donate money to this project? How?

**Comment by danny0838** [comment]
We'll check about it sometime. It seems not technically hard, but having a potential to break user conventions.

**Comment by grotesque** [comment]
Well, I kind-of automated this with auto-hotkey. I've attached the trivial script below if anybody wants. To use it:
* set your "Capture Page As" shortcut to [ctrl+shift+z]
* prepend the folder you want to repeatedly save webpages to with ` (https://en.wikipedia.org/wiki/Grave_accent)
* do a dummy manual capture page (any random page) so as to set whatever default settings you like (eg. capture as HTML, disable downloading fonts etc.)
* delete the manual dummy capture
* henceforth press `caps lock + Grave accent` to directly capture page to the folder to which you've prepended grave accent (or `)
* you can also `caps lock+left-click-on-saved-page` to see captured properties (eg. to mark it important)
* you can also `caps lock+right-click-on-saved-page` to see captured page file system contents
* to change script's page capture destination folder, remove grave accent from the older folder and prepend it to new target folder

```javascript
Capslock & `::
SendInput ^+z
sleep, 300
SendInput {Tab}
sleep, 100
SendInput ``
sleep, 100
SendInput {Enter}
Goto, GEnd

Capslock & LButton::
Click right
SendInput {Up}
SendInput {Enter}
Goto, GEnd

Capslock & RButton::
Click right
SendInput {Down}
SendInput {Down}
SendInput {Down}
SendInput {Down}
SendInput {Down}
SendInput {Down}
SendInput {Right}
SendInput {Enter}
SendInput {CapsLock}

GEnd:
return
```

**Comment by danny0838** [comment]
[ScrapBook 1.13.0b](https://addons.mozilla.org/zh-TW/firefox/addon/scrapbook-x/versions/?page=1#version-1.13.0b) should have fixed this issue. You are free to have a test on it.

**Comment by danny0838** [comment]
Close this issue since it's implemented. It's welcome to refile the issue if related problems still happen in the latest 1.13.* version.
