### ISSUE TITLE
doc files saved but docx not - extension length matters?

### ISSUE THREAD

**Issue by mumblemu** [danny0838/firefox-scrapbook#63]
Firefox 39 w scrapbook-x v1.12 and webpage with doc and docx files. 
The doc files download but the docx files lead to "You have chosen to open..." firefox dialog.
Is this because of the extension length (4 in docx vs 3 in doc)?
Any way to get around this error?
Does the same with ppt and pptx files!

**Comment by danny0838** [comment]
Could you provide the source URL of the web page and what exactly you did for "downloading" doc/docx?

**Comment by mumblemu** [comment]
The site was

http://www.dpcdsb.org/JOANA/Learning/Resources/Math+4U.htm

I tried with and without 'docx' in the custom box. Didn't work either way.
It kept calling up firefoxs dialogue box for saving the file.

**Comment by mumblemu** [comment]
I  limited the downloads with a filter

http://www.dpcdsb.org/NR/rdonlyres

And the doc files worked but not the docx.

**Comment by danny0838** [comment]
Please check whether docx files are really downloaded or not. After the capture process, right-click on the scrapbook item > Tools > Show Files, and see if there are .docx files in the file manager.

**Comment by mumblemu** [comment]
They are not downloaded. Look at the attached. There is a dialogbox for
every docx. But, it doesn't go to the scrapbook.

**Comment by danny0838** [comment]
I cannot see attachments. Maybe you have to upload to some shared cloud drives.

**Comment by mumblemu** [comment]
Can you try again... The attached is a doc with a screenshot of the thing
Firefox does for every docx file. Doc files work in scrapbook but not docx.
Same for ppt and pptx.

**Comment by danny0838** [comment]
GitHub doesn't care about mail attachments, and thus other people are not able to see them if you simply attach files or images in the email.

If you tend to attach an image please do it via the standard web interface uploading, and if you tend to attach a file please upload it to a cloud drive or a web host and share the link.

Here's the screen I've just see  in your reply:

![1](https://cloud.githubusercontent.com/assets/531417/8964886/b8bf9818-365a-11e5-9910-d99e6240a278.jpg)

**Comment by mumblemu** [comment]
ok. I tried again... right side got cut off but you get the idea I suppose.
Notice how it tells the user to "you have chosen to open..." a docx file rather than silently downloading (like a regular doc file) and placing it in the scrapbook folder.

![untitled1](https://cloud.githubusercontent.com/assets/13531449/8965540/399780f6-35fa-11e5-92ec-7c731805a77c.jpg)

**Comment by danny0838** [comment]
@mumblemu: please try the configuration below and report whether it works.

![001](https://cloud.githubusercontent.com/assets/531417/8984797/80090c5a-3706-11e5-8c0a-a0ff187e7c22.jpg)

**Comment by mumblemu** [comment]
Yes that works.
It won't if the depth is set to 1.
Wonder why not?

**Comment by danny0838** [comment]
@mumblemu A rough test showed that it works in the same way even if the depth is set to 1. Could you provide a bit more detail about what was the exactly thing that went wrong?

**Comment by danny0838** [comment]
closed since no response over half year

**Comment by HajoEhlers** [comment]
Firefox: 45.3.0
Scrapbook: Download from Okt. 2016 
Task: Downloading a MS Sharepoint Wiki whicg has files with the doc & docx extension

Problem:
scrapbook does download pdf,doc & docx files if configured BUT it hangs as soon as it does encounter a docx file like https://wiki.xxx/site/local/list.docx.
scrapbook simply does not continue/process further with the download thus you will see on the download ( Save ) Windows : 
 Loading ....1 https://wiki.xxx/site/local/list.docx

Analysis:
Content Type ------------- Action
"pdf " files ------------ preview  - No problem
"doc" files ------------- It is not clear how FF handles these files but they get download by scapbook without any problem.
"Microsoft Word Document" - Save to file

As soon as scrapbook tried to download a "docx" File, the file get "downloaded" by FF to the default download location. 
So it looks like that FF Starts an action which cause scrapbook to wait/hang.
I was not able to find a way to disable the handling of the "Microsft Word Document" format files by FF

Note:
The same behaviour is seen when accessing .xlsx & pptx files mut for simplicity not mentioned.

**Comment by danny0838** [comment]
@HajoEhlers Could you provide a web page having the issue?

**Comment by HajoEhlers** [comment]
Hi Danny
sorry no. The problem shows up on an internal wiki. But I will check if it happens on normal - not an ms shareponit - page as well. If so I could provide a public page for testing. 
With kind regards
Hajo

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: Danny Lin <notifications@github.com> </div><div>Datum:2016.10.27  16:00  (GMT+01:00) </div><div>An: danny0838/firefox-scrapbook <firefox-scrapbook@noreply.github.com> </div><div>Cc: HajoEhlers <hans-joachim.ehlers@ashe.de>, Mention <mention@noreply.github.com> </div><div>Betreff: Re: [danny0838/firefox-scrapbook] doc files saved but docx not -
  extension length matters? (#63) </div><div>
</div>@HajoEhlers Could you provide a web page having the issue?

**Comment by danny0838** [comment]
Which wiki engine does the internal wiki use?

**Comment by HajoEhlers** [comment]
Its a MS Sharepoint Server 2010

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: Danny Lin <notifications@github.com> </div><div>Datum:2016.10.30  22:53  (GMT+01:00) </div><div>An: danny0838/firefox-scrapbook <firefox-scrapbook@noreply.github.com> </div><div>Cc: HajoEhlers <hans-joachim.ehlers@ashe.de>, Mention <mention@noreply.github.com> </div><div>Betreff: Re: [danny0838/firefox-scrapbook] doc files saved but docx not -
  extension length matters? (#63) </div><div>
</div>Which wiki engine does the internal wiki use?

**Comment by HajoEhlers** [comment]
Beg my pardon. I was not not aware that you are supporting "scrapbook-x" where i was using "scrapbook"
So sorry for the hassle. I will try to use scrapbook-x now.
