### ISSUE TITLE
Scrapbook X sidebar is not picked up by All-In-One Sidebar extension

### ISSUE THREAD

**Issue by ferdnyc** [danny0838/firefox-scrapbook#64]
Unlike both Scrapbook and Scrapbook Plus, the Scrapbook X sidebar is not included in the All-In-One Sidebar ("AIOS") extension's sidebar selector / toolbar button. I suspect this is an issue with how Scrapbook X registers itself to the browser, not with the AIOS extension, because its [feature list](http://firefox.exxile.net/aios/features.php) reads, in part:
> **Sidebar Panel Button (AiOS Button)** - easy access all installed sidebar panels. All sidebar extensions are supported, which creates a menu item in Firefox's sidebar menu

And, indeed, when I look at Firefox's `View > Sidebar` menu, there is no entry for the Scrapbook X sidebar. The only way to open the Scrapbook X sidebar is by using the `Scrapbook X > Show in sidebar` menu option, or associated keyboard shortcut.

Would it be possible to have Scrapbook X add its sidebar menu item to the View > Sidebar menu, as the previous Scrapbook extensions did, so that it would be accessible to extensions which use that menu to identify available toolbars?

**Comment by danny0838** [comment]
Could you try and confirm whether [this version](https://github.com/danny0838/firefox-scrapbook/tree/test-fix-view-sitebar) works? (download zip and then rename to .xpi to install and test)

**Comment by ferdnyc** [comment]
It does indeed! With that version installed, I have "Scrapbook X" listed in the `View > Sidebar` menu, and as a result can access it from the AIOS toolbar button/dropdown, and when switching among sidebars via the sidebar selector.

There's a weird double separator preceding the Scrapbook X entry, for some reason, but that's really minor and doesn't appear to be anything that the Scrapbook X code would be causing. (It's possible the same thing was happening with gomita's Scrapbook extension, as well — I honestly can't recall now.)

(I ended up having to download the .zip, extract it, and then re-zip the extension files, because the "Download Zip" option places all of the files inside a folder named `firefox-scrapbook-test-fix-view-sidebar` inside the archive, which confused Firefox.)

**Comment by danny0838** [comment]
Good! Thank you for the feedback.
