### ISSUE TITLE
Slow page scrapbooking in multi-process Firefox

### ISSUE THREAD

**Issue by jgm2** [danny0838/firefox-scrapbook#65]
Using 42 Developer or 43 Nightly 64-bit with multi-process enabled, there is a very noticeable delay of several additional seconds when saving the page.  My observation is that this extra delay seems to be roughly proportional to the size of the page content.

**Comment by danny0838** [comment]
Since a page capture means downloading all its contents, it is expectable that a capture for larger page contents takes longer time to complete.

**Comment by jgm2** [comment]
Here's what I can definitely say:  Testing with Firefox Nightly or with Aurora/Developer, there is an option to turn on/off multiprocess on the first options page.  If I have multiprocess turned on, all Scrapbook X page saves are much slower than when multiprocess is turned off - a large page can take up to 10 or 15 seconds to save, while the same page save with multiprocess off happens saves in a second or two.  I have a modern, fast PC with plenty of memory, running Windows 7.  You may or may not be aware of the issues with multiprocess Firefox (due in FF Beta perhaps this month and in release versions perhaps by end of year) and its consequences for extension developers; there is a summary here:  https://developer.mozilla.org/en-US/Add-ons/Working_with_multiprocess_Firefox

Thanks.

**Comment by danny0838** [comment]
Thank you for the extra information. Since ScrapBook X is made of XUL, it seems that we cannot fix the problem without a total code rework.

Currently we are still trying to make ScrapBook X work correctly, and to pass Firefox AMO review (which is damn slow), the rework would probably be pending for a period of time.

**Comment by hermann-san** [comment]
Is there any news about multiprocess support with Scrapbook X?
At the moment it shows up as not compatible with multiprocess and I would have to either disable Scrapbook X to enable multiprocess or don't use multiprocess at all. But I guess you know this already.

**Comment by danny0838** [comment]
Close this issue as our policy is clear now: We won't add support of e10s for ScrapBook X. Use [Web ScrapBook](https://github.com/danny0838/webscrapbook) or disable e10s for ScrapBook X.
