### ISSUE TITLE
scrapbook x saves of html outlines cannot be collapsed or expanded

### ISSUE THREAD

**Issue by gred22** [danny0838/firefox-scrapbook#68]
I have saved many ecco pro outlines as html files, which retain the colored text and the ability to expand and collapse the various outline items.  But after saving the html outline page in scrapbook, when the page is selected from scrapbook, the items cannot be expanded or collapsed, rather all that can be displayed are the levels as displayed at capture - it is frozen as is.

I can provide html file(s) for testing.

**Comment by danny0838** [comment]
The expand/collapse function is probably made of javascript, which is not captured by default.

You could try "Capture As" with "javascript" checked. However, due to several technical restriction, the javascript is not guaranteed to work properly after captured.

If it doesn't work you could further try "Capture Again", which captures the original page HTML instead of the javascript-processed HTML and would solve some HTML-related problems (when the javascript really requires the original HTML to work). If it still doesn't work, then it's the technical problem we cannot solve currently.

**Comment by gred22** [comment]
YES, if I do a save-as with script checked, the collapse and expand works fine.  THANK YOU!

If would be great to have some kind of expand all and collapse all buttons for my large outlines.  I have banged my head for years on how to get my ecco pro outlines into some form to use without ecco pro, that can be used on both windows and mac if possible, and this is the closest I have come, especially with the great search capability of scrapbook x.

Mark

**Comment by gred22** [comment]
Any more ideas on how I can export and import very large scrapbook databases?

thanks for all your support

Mark

> Begin forwarded message:
> 
> From: Mark Gredler <mgredler@charter.net>
> Subject: Re: [firefox-scrapbook] import/export javascript unresponsive (#67)
> Date: September 8, 2015 at 4:20:21 PM EDT
> To: danny0838/firefox-scrapbook <reply@reply.github.com>
> Cc: mgredler@charter.net
> 
> Here is more data - 
> 
> on original export, that profile still had the straight scrapbook, and exported all, but ended with an unresponsive script which I dismissed.
> Then on import into a fresh profile, using scrapbook x, I got the unresponsive script and could not get the import to complete, but only hit continue a couple times.
> 
> This time, I uninstalled scrapbook and installed scrapbook x in the profile to export before exporting.
> The export showed 6138 items, and exported all 6138 before the unresponsive script, which I hit continue 5 or 6 times and it finished, but no additional items.
> The number of items showed by windows explorer of the export folder is 6680.
> 
> I changed to the profile to have the combined databases, deleted all that was in scrapbook x (got an unresponsive script at end too)
> Then I did an import of the database exported above.
> It showed 6152 items detected, and would not import any of them.
> 
> To clarify, the export, windows explorer, and import numbers are all different
> The export seems to export all data before the unresponsive script, and appears to complete after hitting continue 6 times
> The data exported by scrapbook can almost all be imported by scrapbook x before unresponsive script
> The data exported by scrapbook x cannot be imported at all by scrapbook x
> 
> Hope this helps!
> 
> Mark
> 
> 
>

**Comment by danny0838** [comment]
The further question is another issue. Please open another issue if it still persists in the latest SBX version.

**Comment by gred22** [comment]
I installed scrapbook x - no problem.

I installed scrapbook x converter, and all my scrapbook data disappeared.  PLEASE HELP - I cannot afford to loose all my data.

Mark

**Comment by gred22** [comment]
I can’t find how to point to a different data store location in scrapbook x.  Tools / Options / Manage no longer has that.

Please tell me where it is at.

Mark

**Comment by jdunn0** [comment]
> I can’t find how to point to a different data store location in scrapbook x.  Tools / Options / Manage no longer has that.

The answer to that is in the comments of [issue 140](https://github.com/danny0838/firefox-scrapbook/issues/140)
