### ISSUE TITLE
Javascript option problem.

### ISSUE THREAD

**Issue by zohaibji** [danny0838/firefox-scrapbook#70]
Hi there

This addon is love of my life. There's only one problem and I want you to kindly fix it. I'm willing to support and pay for this project as it's my most fav addon... :-)

1) When we use "Save Page" or "Capture multiple url's" options, they work perfect but they always work without "javascript" which means all tabs get saved but without javascript.

2) In the Save as option we can select javascript option, but is it possible to make it always enabled so we don't have to do it again and again.

Kindly let me know how can I fix this problem so I can opt whether I want javascript option to be enabled or disabled.

Looking forward to hearing from you.

Kind regards,
Zo

**Comment by danny0838** [comment]
This issue seems like #21, and we currently have difficulties on implementing it.

**Comment by danny0838** [comment]
A normal capture now remembers last capture detail options since ScrapBook X 1.13.0b.
