### ISSUE TITLE
Converting from ScrapBook Plus 1.9.24.40b4?

### ISSUE THREAD

**Issue by froomkin** [danny0838/firefox-scrapbook#74]
Diffs page currently discusses conversion from ScrapBook Plus up to version 1.9.24.40b3.  It is not, however, stated what happens to users of version ScrapBook Plus 1.9.24.40b4.  Please could you indicate if it is safe to upgrade from this version, and what if anything is different in b4-->X from b3-->x.

Thank you.

**Comment by danny0838** [comment]
The latest version ScrapBook Plus 1.9.24.40 only added a little change for Firefox 36+ compatibility, and there's no change to the previous review of compatibility. The compatibility report is updated. Thank you for the report.

**Comment by danny0838** [comment]
Close issue due to no further response for half year.
