### ISSUE TITLE
Add a Delay between the requests

### ISSUE THREAD

**Issue by Kurtafterjim** [danny0838/firefox-scrapbook#75]
Hi,
is it possible add a delay? Because after a lot of pages some site return an error.

Thanks!

**Comment by danny0838** [comment]
Try `Timeout` and please report more detail if it doesn't work.

![2016-01-06 23_13_47-scrapbook - capture detail](https://cloud.githubusercontent.com/assets/531417/12145834/66ac2cb8-b4cb-11e5-97ad-b3e7f79e201a.png)

**Comment by danny0838** [comment]
This issue seems fixed. If there's further information, add a comment here and open it again.
