### ISSUE TITLE
Saving JavaScript - global option

### ISSUE THREAD

**Issue by DostalTomas** [danny0838/firefox-scrapbook#78]
Hello, 
  would it be possible add global option for saving javascript? I use drag'n'drop to saving pages and JS doesn't save. Using Save As... option, ever I want to download page is quite uncomfortable. 

Best Regards,
   Tomas

**Comment by danny0838** [comment]
It's not in our plans currently. However, you can hold the Shift key when you drag something to capture, and then you can set the capture detail options manually.

**Comment by DostalTomas** [comment]
OK, thanks for information.

**Comment by danny0838** [comment]
A normal capture now remembers last capture detail options since ScrapBook X 1.13.0b.
