### ISSUE TITLE
關於scrapbook x訪問特定網頁假死問題

### ISSUE THREAD

**Issue by sjjyz126** [danny0838/firefox-scrapbook#79]
首先感謝您提供如此優秀的軟件，但是有個地方美中不足，就是程序經常發生卡住在某一網頁裡，就算在配置界面裡設置超時時間，程序還是一直停滯在那個網頁上，重試很多遍，程序才自動跳過那個網頁，繼續捕捉下一網頁，比如捕捉www.pingan.com,程序卡在一個子頁http://wifi.pingan.com和http://ex.pingan.com/ ，我這邊嘗試過很多遍，通過不同的電腦和網絡測試，還是出現相同的問題，請問是什麼原因？如何解決？非常感謝！

**Comment by danny0838** [comment]
我們用 ScrapBook X 1.12.17，擷取連結層數設為 1 時，並未發現此問題，或許是和網路環境有關。如要進一步調查，可能得請您提供您使用的 ScrapBook X 版本及您操作多層擷取時使用的參數了。

**Comment by sjjyz126** [comment]
您好，不好意思，我上次忘記說，我在擷取前我選擇了動態腳本，如果我沒有選擇動態腳本都是正常的，如果選擇了就一直卡住在這兩個網址上不動。能不能在處理動態腳本上有個超時的處理機制，配置界面上的超時設置好像沒有起到作用，謝謝！

在 2016-01-14 01:49:43，"Danny Lin" <notifications@github.com> 写道：


我們用 ScrapBook X 1.12.17，擷取連結層數設為 1 時，並未發現此問題，或許是和網路環境有關。如要進一步調查，可能得請您提供您使用的 ScrapBook X 版本及您操作多層擷取時使用的參數了。

**Comment by danny0838** [comment]
最近發現有個地方出錯導致此問題，下一版會嘗試修正。

**Comment by danny0838** [comment]
Fixed in 1fa0eca0cffa24ed39c27ceea9ccf0a847359b8c.
