### ISSUE TITLE
Printing issue with freenote

### ISSUE THREAD

**Issue by githmw** [danny0838/firefox-scrapbook#84]
I am able to print whatever I saved with ScrapbookX by using the Print command in my browser. The Print Preview displays the freenotes created with the Annotation Tool, but these notes do not print for me. 

Are they supposed to print?

Thanks,

Harry

**Comment by danny0838** [comment]
We need some more information to investigate the issue. Could you provide a demo page as well as the pictures for what was displayed in print preview and what is actually printed?

**Comment by githmw** [comment]
Danny:

Three screenshots are attached.
#1. This is what ScrapbookX captured. The red arrow points to the
freenote I added.
#2. This is what Preview displayed. (I have set this to 'print
background' so more details show. I tried it both ways. Neither have
an effect on what is actually printed.)
#3. This is what my printer (an Epson WF-7010 color inkjet) printed.

I tried going through this Preview and Print procedure several times.
The results were always the same.

Let me know if you need more information.


Harry

**Comment by danny0838** [comment]
Attachments via email doesn't seem to work in GitHub. You'd have to attach them via the web interface.

**Comment by githmw** [comment]
Danny:

Attached are the three files noted in my post yesterday. I hope this works. Also note in #2, that the freenote is moved to the left of where it was originally placed in #1.

![scrapbookx_nofreenoteprint_1](https://cloud.githubusercontent.com/assets/17102180/12955274/45fa44d8-cff0-11e5-914b-f4353fb51726.jpg)
![scrapbookx_nofreenoteprint_2](https://cloud.githubusercontent.com/assets/17102180/12955285/50096b84-cff0-11e5-8fdb-beca040e926c.jpg)
![scrapbookx_nofreenoteprint_3](https://cloud.githubusercontent.com/assets/17102180/12955291/583b6bae-cff0-11e5-833e-b33ba469cbe8.jpg)

**Comment by mseliger** [comment]
Hello Harry, 
I have no problem to print freenotes. My configuration: Lubuntu 15.10, Firefox 44.0.2., Scrapbook X 1.12.17. 
Which operating system, Firefox and Scrapbook X version are you using?
Greetings, Maria

**Comment by githmw** [comment]
mseliger:

Interesting. I have ScrapbookX 1.12.17--same as you. My primary browser is Pale Moon. The problem exists on Versions 25.x and 26.x. I have Firefox 42, but never tried it there, since I hardly ever use it. I just tried it, and it prints fine on Firefox. so the problem must be between ScrapbooX and Pale Moon.

Harry

**Comment by mseliger** [comment]
Hello Harry,

i've installed PaleMoon 26.1.0 (x64) and Scrapbook X 1.12.17 - but I don't have any problems with printing freenotes. Maybe your profile is corrupt?
Greetings, Maria

**Comment by danny0838** [comment]
@githmw Could you try printing it to a PDF file and see if it works or not?

**Comment by githmw** [comment]
Danny:

Printing to PDF did not help. I then disabled all my add-ons except for ScrapbookX. The problem still exists. I also tried creating a freenote in a different document. Same problem.

Maria seems to not have a problem printing with Pale Moon, although she is running (x64) and I am running (x32). I also tested on my laptop, which has the same version of Pale Moon that Maria has (26.1.0), AND where I have Scrapbook (not ScrapbookX) and the same problem exists. So I don't think I have a corrupt Pale Moon profile.

 At this point I am not sure what else to try. Suggestions?


Harry

**Comment by mseliger** [comment]
Hello Harry,

i will try to install Palemoon on Windows tomorrow (Windows 7, 64-bit) to see if it is a windows issue. Have you tried the newest version of Scrapbook (1.12.20) (from yesterday)?
Greetings, Maria

**Comment by githmw** [comment]
Marie:

Thanks for making all this effort on my behalf. Greatly appreciated.

I suggest you install the x86 version of Pale Moon, not the one for 64 bit. If you read their forum on the 64 bit version, you will see that it is not as stable as the 32 bit version, and also some websites that run on the x86 version do not on the 64 bit.

No, I still have 1.12.17. I just looked at the revision log, and I didn't see anything in .18, .19 or .20 that I thought was major.  If you think differently once you install .20, let me know.

Harry

**Comment by mseliger** [comment]
Hello Harry,

freenotes are not printed in Palemoon Windows 32-bit version. But I don't think this is a scrapbook error, because the preview is right shown.
As a workaround:
Install printedit ([https://addons.mozilla.org/en-US/firefox/addon/print-edit/?src=search](https://addons.mozilla.org/en-US/firefox/addon/print-edit/?src=search))
Open the preferences of PrintEdit in the Addon-Manager.
Check / Uncheck these settings (shown in the attachment).
![Uploading PrintEditOptions.PNG…]()
Restart your browser.
Use PrintEdit to print the page and print it to PDF with the build-in-function of PrintEdit.
![printeditoptions](https://cloud.githubusercontent.com/assets/8599087/13181179/0d16cf4a-d72c-11e5-81ed-f3d7178c12e5.PNG)
In my case the freenote is printed when you print it to PDF with PrintEdit.
Greetings, Maria

**Comment by githmw** [comment]
Maria:

Installed Print Edit, and followed your instructions. Works great, and solves the problem! Another one of those add-ons that I knew nothing about, and I see it has some other neat printing features that I can use.

If I understand your threads, you had no problem printing normally to Firefox (and neither did I). Also, Pale Moon 64 bit running on Linus had no problem, but Pale Moon 32 bit running on Windows 7 did. Is that what you found? I want to alert the folks at Pale Moon about this problem, and if it only exists on their 32 bit (x86) version, but not on their Linus 64 bit version, that should help them solve the problem.

Thanks again for all your help on this.

Harry

**Comment by mseliger** [comment]
Hello Harry,

yes, it seems the problem is only on Windows (7) with Palemoon (32-bit). 

Greetings, Maria

**Comment by danny0838** [comment]
Could you do a further try: uninstall ScrapBook X, create an HTML file with below content, print it, and see if it works right?

    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title data-sb-obj="title">test</title>
      <meta name="viewport" content="width=device-width">
    </head>
    <body>
    test
    <div style="cursor: help; overflow: visible; margin: 0px; border-width: 12px 1px 1px; border-style: solid; border-color: rgb(204, 204, 204); -moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; border-image: none; background: rgb(250, 255, 250) none repeat scroll 0% 0%; opacity: 0.95; padding: 0px; z-index: 500000; text-align: start; font-size: small; line-height: 1.2em; word-wrap: break-word; width: 250px; height: 100px; position: absolute; left: 69px; top: 24px;" data-sb-obj="freenote">test freenote</div>
    </body>
    </html>

**Comment by mseliger** [comment]
Hello,

i've created a document, disabled Scrapbook X and PrintEdit and printed the document with Palemoon x86 with Windows 7 on a HP Printer. The freenote is shown in preview and in print from the example above.

Greetings, Maria

**Comment by githmw** [comment]
Since Maria has already followed your instructions and disabled everything, I tried it without disabling anything. I previewed and printed the freenote .html file with Palemoon (x86) and Windows 7 Pro (64 bit) without any problem. For PrintEdit, I did NOT check 'Print as PDF'.

Harry

**Comment by danny0838** [comment]
Well, since you've concluded that the printing issue happens on **Windows (7)** with **Palemoon (32-bit)** and **without PrintEdit**, could you try pring the above html content under this condition?

**Comment by githmw** [comment]
Danny:

Are you sending this request to me (githmw) or to Maria (mseliger)? I ran your code with PrintEdit installed but did NOT select 'Print as PDF', and it worked fine. Maria ran it by disabling PrintEdit, and she said that also worked.

Harry

**Comment by danny0838** [comment]
When it worked ok, if you install ScrapBook X and do it again, would it fail?

**Comment by mseliger** [comment]
Hello,

I've updated the Palemoon version to version 26.1.1, Windows 7, 32-bit Version. And I updated the Scrapbook X version to 1.12.23. 
I can print the html file above. And it is correct printed. But if I printed a saved Scrapbook X page with a freenote then the freenote is shown in the print preview, but not printed by the printer. If I activate the Print Edit Addon and make a PDF of the print preview, then the freenote is shown.
Any suggestions?

@Harry: Do you have a virtual printer? For example Fineprint, Bullzip PDF Printer or Microsoft Office XPS printer? What, if you print your document on a virtual printer?

Greetings, Maria

**Comment by githmw** [comment]
Maria:

>>@Harry: Do you have a virtual printer? For example Fineprint, Bullzip PDF Printer or Microsoft Office >>XPS printer? What, if you print your document on a virtual printer?

I have Fineprint, Snagit 10, and PDF995 (which prints to a .pdf file). If I start with a saved ScrapbookX file with a freenote, the freenote is NOT printed on any of these 3 virtual printers.


Harry

**Comment by danny0838** [comment]
Close stale issue. If there's new information it's still welcomed to leave a reply.
