### ISSUE TITLE
Capture Again clumsy interface

### ISSUE THREAD

**Issue by meghprkh** [danny0838/firefox-scrapbook#88]
IMHO the capture again has a clumsy interface. On pressing capture again should the page not be captured again without any dialogs, because I use scrapbook to maintain a collection of 5 pages offline which I need to be updated and it gets quite annoying updating them.

**Comment by danny0838** [comment]
In the current version (1.12.23), on pressing capture again it jumps a dialog for URLs and then a dialog for capture detail, doesn't it?

**Comment by meghprkh** [comment]
Yes

**Comment by danny0838** [comment]
You can try middle-clicking or shift-left-clicking on the capture again button, and the recapture will skip the capture detail dialog, but it only works when default capture settings are desired.

**Comment by meghprkh** [comment]
Oh okay, thanks
