### ISSUE TITLE
Firefox Android Support

### ISSUE THREAD

**Issue by fxshpac** [danny0838/firefox-scrapbook#9]
Does this extension supported by Firefox Android? If so that will be great because that make it possible to sync the same ScapBook collection between PC and my Android Phone.

**Comment by danny0838** [comment]
Close this issue as our policy is clear now: We won't add support of Firefox Android for ScrapBook X. Use the output tree method as above mentioned, or use [Web ScrapBook](https://github.com/danny0838/webscrapbook), which supports Firefox Android.
