### ISSUE TITLE
Information: About digital ScrapBooking

### ISSUE THREAD

**Issue by mseliger** [danny0838/firefox-scrapbook#91]
The Max Planck Institute of History has published an article about Digital ScrapBooking. 

[Digital Scrapbook – can we enable interlinked and recursive knowledge equilibrium?](http://www.mpiwg-berlin.mpg.de/Preprints/P474.PDF)

The article mentioned also Scrapbook X and discuss the function of it.

Mit freundlichen Grüßen / Greetings
Maria

**Comment by danny0838** [comment]
Thank you very much. Most of which you mentioned are the reason I start improving ScrapBook. We currently are facing new challenges, though. Hope we'll pass it and become stronger.

**Comment by pascallothar** [comment]
@danny0838 ,

Look, I have added a chapter in the **_Wikipedia_** article about ScrapBook, that talks about "**_ScrapBook X_**". It cites also 2 excerpts of the article mentioned by @mseliger .

[https://en.wikipedia.org/wiki/ScrapBook#Discontinuation_of_development._Takeover_by_.22ScrapBook_X.22.]

I hope you will like this chapter.

Pascal.

---

Here are the PermaLinks of the article mentioned by @mseliger :

Item Permalink: [http://hdl.handle.net/11858/00-001M-0000-002A-8082-D]
Version Permalink: [http://hdl.handle.net/11858/00-001M-0000-002A-8083-B]
File Permalink: [http://hdl.handle.net/11858/00-001M-0000-002A-8084-9]

**Comment by danny0838** [comment]
It's nice. Thank you.
