### ISSUE TITLE
Problems when sorting folders

### ISSUE THREAD

**Issue by mseliger** [danny0838/firefox-scrapbook#92]
Hello,

I have a problem with the feature "Sort folder" with ScrapBook 1.12.26 (it is possible that the problem is older ...). When I use the feature "Sort folder" it works fine on the ScrapBook Tree / Folder. But when I restart the underlying application (Firefox 38 or Pale Moon 26) then the sorting is mostly undone again.
Anywhere else with the problem?

Greetings Maria

**Comment by danny0838** [comment]
This is confirmed to be a bug, we'll fix it in the next release.

**Comment by danny0838** [comment]
Fixed in 2b3fbaf4372a337bcde2c129e9c7f24edb336172.
