### ISSUE TITLE
可否考虑做兼容chrome和firefox WebExtensions的扩展

### ISSUE THREAD

**Issue by yilksd** [danny0838/firefox-scrapbook#93]
非常感谢Danny兄的辛勤劳动，为scrapbook 这个经典扩展注入了新的活力。但是目前firefox颓势早已显明，频繁变动扩展体系，扩展开发者和普通用户都大量流失。mozilla 说要建立一个兼容chrome 的扩展体系，但这样firefox 就优势全无。opera 已被收购，mozilla 也离被收购不远了吧。
mozilla内部恐怕也很有问题，比如这条报料：
https://news.slashdot.org/comments.pl?sid=8836539&cid=51642315
相关讨论：
http://tieba.baidu.com/p/4395644212
在这种状况下，xul 能否存续是不容乐观的。即使有人说基于xul的扩展能够在接下来的版本的firefox中继续使用，也是可信度不高的。公开承诺尚且能违反，私下交流的消息又能有几分保证力呢？
Firefox是我长期使用的浏览器，它日渐衰败我也非常难过。但是我必须正视现实，不能在一棵树上吊死。我也多次尝试迁移到chrome或其他类似浏览器，但是种种不习惯。其中第一重要的原因就是，没有如scrapbook那样优秀的网页剪辑工具。有一个与scrapbook 有点类似的chrome 扩展，叫做singlefile ,但是剪辑效果没有scrapbook好。我还试过evernote ,wiz, firefox保存网页功能，chrome保存网页功能等，效果都不理想。剪辑功能最强的还是scrapbook 和unmht。
然而现在有一些笔记、资料管理、事务管理软件，它们的管理与搜索功能比scrapbook要完善很多。在xul这样前景不明的平台上再去开发复杂的管理功能，怕是举步维艰。所以我的建议是缩减管理功能，专注于网页剪辑，与onenote, zim, zotero ，还有文件管理器等软件配合。这样将来也就更容易兼容firefox WebExtensions 扩展体系和chrome扩展体系。 
目前WebExtensions功能还不是很明确，所以建议还是用add-on sdk 开发扩展，这样将来也容易迁移；也可以暂时继续用传统xul开发的方式，对scrapbook进行精简。

**Comment by danny0838** [comment]
不是沒考慮過，但目前看來 Chrome Extension 缺乏完整擷取網頁的某些必要功能，比如存取非同域 iframe 內容的權限（Single File 目前也沒辦法），因此無法勝任。至於非瀏覽器套件的其他程式語言，比如 Python、node.js、phantoms.js 等等，則是無法做到像瀏覽器套件那樣把目前瀏覽的內容擷取下來。

至於 Addon SDK 與 XUL/XPCOM 的問題，不曉得您是否看過 #85？目前會繼續使用 XUL/XPCOM 開發，理由有下：

1. 目前 Addon SDK 的 high level API 不能滿足網頁擷取的基本需求，最終還是得調用 low level API，實際上就是調用 XPCOM 元件。也就是說，完全脫離 XPCOM 開發是不可能的。

2. 有太多既有套件是使用 XUL/XPCOM 技術，如果 Firefox 只保留 high level API 而把所有底層架構換掉，首先就要讓舊套件全部無法使用，屆時還有多少人要用 Firefox？

3. Addon SDK 只有 Firefox 支援，使用 XUL/XPCOM 才能保有與其他應用程式如 Pale Moon 與 Sea Monkey 的相容與遷移能力。

至於八卦，那不是我能掌握的，只能說反正是開源專案，如果 Firefox 爛到極致，自然會有其他 Fork 取而代之。目前能做的就是盡量擴大跨應用程式間的相容性。

**Comment by danny0838** [comment]
Chrome 版本的 [Web ScrapBook](https://github.com/danny0838/webscrapbook) 已在開發中。
