### ISSUE TITLE
Archive multiple URLs problem

### ISSUE THREAD

**Issue by fleshi** [danny0838/firefox-scrapbook#94]
Hello,

when I open multiple tabs and chose then the option to save all tabs all the URLs are saved perfectly.
When I try to save a bunch of URLs with the 'archive multiple URLs'  command then just the 'frame' of the site is saved, but not the content. For saving a single page there is an options menu where I can set all the details what should be saved (e.g. link depth, graphics, etc.) but I cannot set all these options when I try to save a list of URLs.

Am I doing something wrong or is it a missing feature?

**Comment by danny0838** [comment]
For the first question: I cannot reproduce the issue according to your description. Could you provide some screenshots for it? Also, were you using the latest ScrapBook X version (currently 1.12.30) when you see this issue?

For the second question: Yes, it's a missing feature currently, which has been talked about before (e.g. #21). Unfortunately it would require a rather big structural code change which cannot be done easily and shortly.

**Comment by fleshi** [comment]
Hi Denny,

I've attached 2 files where you can see the difference.
I use the latest version 1.12.30.

What is 'the trigger' to save the URL? Would it really be a big thing to 
just implement a delay timer?
Normally the URL is loaded in a few seconds.

Cheers,

Holger

Am 10.05.2016 09:04 schrieb Danny Lin:

**Comment by danny0838** [comment]
GitHub doesn't support email attachments. You'd have to upload attachments via the web interface.

**Comment by danny0838** [comment]
@fleshi I still cannot see your attachments and cannot investigate on the issue you stated. Please provide the information if it's still an issue.

**Comment by danny0838** [comment]
Close stale issue since we are unable to reproduce and no further discussion for over a year.
