### ISSUE TITLE
Can no longer drag to reorder scraps in the scrapbook tree

### ISSUE THREAD

**Issue by jgm2** [danny0838/firefox-scrapbook#97]
FF 48.0b1
Left-click, drag, and drop seems to treat the event as a new capture, since the new capture dialog then opens up for me now.  Drag-drop reorder used to work correctly at some point in the past.

**Comment by danny0838** [comment]
Fixed in d659821a38560833d18264c2c8b0ee87be8c2584. Thank you for reporting.
